/* C code for program declTest, generated by snc from ../decl.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../decl.st"
#include <stdlib.h>
# line 15 "../decl.st"
static const EF_ID ef = 1;
# line 18 "../decl.st"
struct r { int x; } rv;

/* Variable declarations */
struct seqg_vars {
# line 13 "../decl.st"
	int *(*(*complicated)[2][3])[1];
# line 20 "../decl.st"
	TS_STAMP ts;
# line 22 "../decl.st"
	int var;
	struct seqg_vars_one {
# line 31 "../decl.st"
		char *a[4];
# line 35 "../decl.st"
		string b[4];
# line 42 "../decl.st"
		int c[2];
# line 48 "../decl.st"
		string s;
	} seqg_vars_one;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 13 "../decl.st"
	static int *(*(*seqg_initvar_complicated)[2][3])[1] = 0;
	memcpy(&seqg_var->complicated, &seqg_initvar_complicated, sizeof(seqg_initvar_complicated));
	}
	{
# line 31 "../decl.st"
	static char *seqg_initvar_a[4] = {"1", "2", "3"};
	memcpy(&seqg_var->seqg_vars_one.a, &seqg_initvar_a, sizeof(seqg_initvar_a));
	}
	{
# line 35 "../decl.st"
	static string seqg_initvar_b[4] = {"1234567890123456789012345678901234567890", "abcdefghijabcdefghijabcdefghijabcdefghij", "ABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJ", "123"};
	memcpy(&seqg_var->seqg_vars_one.b, &seqg_initvar_b, sizeof(seqg_initvar_b));
	}
	{
# line 42 "../decl.st"
	static int seqg_initvar_c[2] = {123, 456};
	memcpy(&seqg_var->seqg_vars_one.c, &seqg_initvar_c, sizeof(seqg_initvar_c));
	}
	{
# line 48 "../decl.st"
	static string seqg_initvar_s = "s";
	memcpy(&seqg_var->seqg_vars_one.s, &seqg_initvar_s, sizeof(seqg_initvar_s));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 26 "../decl.st"
	printf("%d\n", rv.x);
# line 27 "../decl.st"
	seqg_var->ts = seq_pvTimeStamp(seqg_env, 0/*var*/);
}

/****** Code for state "one" in state set "one" ******/

/* Entry function for state "one" in state set "one" */
static void seqg_entry_one_0_one(SS_ID seqg_env)
{
# line 52 "../decl.st"
	seq_pvPutTmo(seqg_env, 1/*b*/, DEFAULT, DEFAULT_TIMEOUT);
# line 53 "../decl.st"
	seq_pvPutTmo(seqg_env, 2/*c*/, DEFAULT, DEFAULT_TIMEOUT);
# line 54 "../decl.st"
	seq_pvPutTmo(seqg_env, 3/*s*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "one" in state set "one" */
static seqBool seqg_event_one_0_one(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 56 "../decl.st"
	if (seq_delay(seqg_env, 10))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 58 "../decl.st"
	if (seq_efTestAndClear(seqg_env, ef))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 66 "../decl.st"
	if (seq_delay(seqg_env, 0.1) && !seqg_var->complicated)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "one" in state set "one" */
static void seqg_action_one_0_one(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 59 "../decl.st"
			printf("Event on b or c\n");
			{
# line 62 "../decl.st"
				string s = "blub";
# line 63 "../decl.st"
				printf("s=%s\n", s);
			}
		}
		return;
	case 2:
		{
# line 67 "../decl.st"
			exit(0);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, var), "var", P_INT, 1, 2, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, seqg_vars_one.b), "b", P_STRING, 4, 3, 1, 1, 0, 0},
	{"", offsetof(struct seqg_vars, seqg_vars_one.c), "c", P_INT, 2, 4, 1, 1, 0, 0},
	{"", offsetof(struct seqg_vars, seqg_vars_one.s), "s", P_STRING, 1, 5, 0, 0, 0, 0},
};

/* Event masks for state set "one" */
static const seqMask seqg_mask_one_0_one[] = {
	0x00000002,
};

/* State table for state set "one" */
static seqState seqg_states_one[] = {
	{
	/* state name */        "one",
	/* action function */   seqg_action_one_0_one,
	/* event function */    seqg_event_one_0_one,
	/* entry function */    seqg_entry_one_0_one,
	/* exit function */     0,
	/* event mask array */  seqg_mask_one_0_one,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "one",
	/* states */            seqg_states_one,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram declTest = {
	/* magic number */      2002005,
	/* program name */      "declTest",
	/* channels */          seqg_chans,
	/* num. channels */     4,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  1,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME declTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void declTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&declTest);
}
epicsExportRegistrar(declTestRegistrar);
