/* C code for program delayTest, generated by snc from ../delay.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 11 "../delay.st"
#include "pv.h"

/* Variable declarations */
struct seqg_vars {
# line 13 "../delay.st"
	double v;
	struct seqg_vars_test {
# line 17 "../delay.st"
		double thr;
# line 18 "../delay.st"
		double hyst;
	} seqg_vars_test;
	struct seqg_vars_ramp {
# line 40 "../delay.st"
		double lo;
# line 41 "../delay.st"
		double hi;
# line 42 "../delay.st"
		double step;
# line 43 "../delay.st"
		double dt;
# line 44 "../delay.st"
		double t;
# line 45 "../delay.st"
		double start_time;
	} seqg_vars_ramp;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 13 "../delay.st"
	static double seqg_initvar_v = 0;
	memcpy(&seqg_var->v, &seqg_initvar_v, sizeof(seqg_initvar_v));
	}
	{
# line 17 "../delay.st"
	static double seqg_initvar_thr = 5.0;
	memcpy(&seqg_var->seqg_vars_test.thr, &seqg_initvar_thr, sizeof(seqg_initvar_thr));
	}
	{
# line 18 "../delay.st"
	static double seqg_initvar_hyst = 0.45;
	memcpy(&seqg_var->seqg_vars_test.hyst, &seqg_initvar_hyst, sizeof(seqg_initvar_hyst));
	}
	{
# line 40 "../delay.st"
	static double seqg_initvar_lo = 4.0;
	memcpy(&seqg_var->seqg_vars_ramp.lo, &seqg_initvar_lo, sizeof(seqg_initvar_lo));
	}
	{
# line 41 "../delay.st"
	static double seqg_initvar_hi = 6.0;
	memcpy(&seqg_var->seqg_vars_ramp.hi, &seqg_initvar_hi, sizeof(seqg_initvar_hi));
	}
	{
# line 42 "../delay.st"
	static double seqg_initvar_step = 0.1;
	memcpy(&seqg_var->seqg_vars_ramp.step, &seqg_initvar_step, sizeof(seqg_initvar_step));
	}
	{
# line 43 "../delay.st"
	static double seqg_initvar_dt = 0.1;
	memcpy(&seqg_var->seqg_vars_ramp.dt, &seqg_initvar_dt, sizeof(seqg_initvar_dt));
	}
	{
# line 44 "../delay.st"
	static double seqg_initvar_t = 0.0;
	memcpy(&seqg_var->seqg_vars_ramp.t, &seqg_initvar_t, sizeof(seqg_initvar_t));
	}
}

/****** Code for state "low" in state set "test" ******/

/* Entry function for state "low" in state set "test" */
static void seqg_entry_test_0_low(SS_ID seqg_env)
{
# line 21 "../delay.st"
	printf("state low: v = %g\n", seqg_var->v);
# line 22 "../delay.st"
	printf("state low: thr = %g, hyst = %g\n", seqg_var->seqg_vars_test.thr, seqg_var->seqg_vars_test.hyst);
}

/* Event function for state "low" in state set "test" */
static seqBool seqg_event_test_0_low(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 24 "../delay.st"
	if (seqg_var->v >= seqg_var->seqg_vars_test.thr + seqg_var->seqg_vars_test.hyst)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "low" in state set "test" */
static void seqg_action_test_0_low(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 25 "../delay.st"
			printf("low, v = %g, transition to high\n", seqg_var->v);
		}
		return;
	}
}

/****** Code for state "high" in state set "test" ******/

/* Entry function for state "high" in state set "test" */
static void seqg_entry_test_0_high(SS_ID seqg_env)
{
# line 30 "../delay.st"
	printf("state high: v = %g\n", seqg_var->v);
# line 31 "../delay.st"
	printf("state high: thr = %g, hyst = %g\n", seqg_var->seqg_vars_test.thr, seqg_var->seqg_vars_test.hyst);
}

/* Event function for state "high" in state set "test" */
static seqBool seqg_event_test_0_high(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 33 "../delay.st"
	if (seqg_var->v <= seqg_var->seqg_vars_test.thr - seqg_var->seqg_vars_test.hyst)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "high" in state set "test" */
static void seqg_action_test_0_high(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 34 "../delay.st"
			printf("high, v = %g, transition to low\n", seqg_var->v);
		}
		return;
	}
}

/****** Code for state "init" in state set "ramp" ******/

/* Event function for state "init" in state set "ramp" */
static seqBool seqg_event_ramp_1_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "ramp" */
static void seqg_action_ramp_1_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 48 "../delay.st"
			pvTimeGetCurrentDouble(&seqg_var->seqg_vars_ramp.start_time);
		}
		return;
	}
}

/****** Code for state "up" in state set "ramp" ******/

/* Event function for state "up" in state set "ramp" */
static seqBool seqg_event_ramp_1_up(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 52 "../delay.st"
	if (seqg_var->v >= seqg_var->seqg_vars_ramp.hi)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 59 "../delay.st"
	if (seq_delay(seqg_env, seqg_var->seqg_vars_ramp.dt))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "up" in state set "ramp" */
static void seqg_action_ramp_1_up(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 53 "../delay.st"
			double real_time;
# line 54 "../delay.st"
			pvTimeGetCurrentDouble(&real_time);
# line 55 "../delay.st"
			seqg_var->v = seqg_var->seqg_vars_ramp.hi;
# line 56 "../delay.st"
			printf("go down, v = %g, t = %g, rt = %g\n", seqg_var->v, seqg_var->seqg_vars_ramp.t, real_time - seqg_var->seqg_vars_ramp.start_time);
# line 57 "../delay.st"
			seq_pvPutTmo(seqg_env, 0/*v*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 60 "../delay.st"
			double real_time;
# line 61 "../delay.st"
			pvTimeGetCurrentDouble(&real_time);
# line 62 "../delay.st"
			seqg_var->seqg_vars_ramp.t += seqg_var->seqg_vars_ramp.dt;
# line 63 "../delay.st"
			seqg_var->v += seqg_var->seqg_vars_ramp.step;
# line 64 "../delay.st"
			printf("up, v = %g, t = %g, rt = %g\n", seqg_var->v, seqg_var->seqg_vars_ramp.t, real_time - seqg_var->seqg_vars_ramp.start_time);
# line 65 "../delay.st"
			seq_pvPutTmo(seqg_env, 0/*v*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "down" in state set "ramp" ******/

/* Event function for state "down" in state set "ramp" */
static seqBool seqg_event_ramp_1_down(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 69 "../delay.st"
	if (seqg_var->v <= seqg_var->seqg_vars_ramp.lo)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 76 "../delay.st"
	if (seq_delay(seqg_env, seqg_var->seqg_vars_ramp.dt))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "down" in state set "ramp" */
static void seqg_action_ramp_1_down(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 70 "../delay.st"
			double real_time;
# line 71 "../delay.st"
			pvTimeGetCurrentDouble(&real_time);
# line 72 "../delay.st"
			seqg_var->v = seqg_var->seqg_vars_ramp.lo;
# line 73 "../delay.st"
			printf("go up, v = %g, t = %g, rt = %g\n", seqg_var->v, seqg_var->seqg_vars_ramp.t, real_time - seqg_var->seqg_vars_ramp.start_time);
# line 74 "../delay.st"
			seq_pvPutTmo(seqg_env, 0/*v*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 77 "../delay.st"
			double real_time;
# line 78 "../delay.st"
			pvTimeGetCurrentDouble(&real_time);
# line 79 "../delay.st"
			seqg_var->v -= seqg_var->seqg_vars_ramp.step;
# line 80 "../delay.st"
			seqg_var->seqg_vars_ramp.t += seqg_var->seqg_vars_ramp.dt;
# line 81 "../delay.st"
			printf("down, v = %g, t = %g, rt = %g\n", seqg_var->v, seqg_var->seqg_vars_ramp.t, real_time - seqg_var->seqg_vars_ramp.start_time);
# line 82 "../delay.st"
			seq_pvPutTmo(seqg_env, 0/*v*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, v), "v", P_DOUBLE, 1, 1, 0, 0, 0, 0},
};

/* Event masks for state set "test" */
static const seqMask seqg_mask_test_0_low[] = {
	0x00000002,
};
static const seqMask seqg_mask_test_0_high[] = {
	0x00000002,
};

/* State table for state set "test" */
static seqState seqg_states_test[] = {
	{
	/* state name */        "low",
	/* action function */   seqg_action_test_0_low,
	/* event function */    seqg_event_test_0_low,
	/* entry function */    seqg_entry_test_0_low,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_low,
	/* state options */     (0)
	},
	{
	/* state name */        "high",
	/* action function */   seqg_action_test_0_high,
	/* event function */    seqg_event_test_0_high,
	/* entry function */    seqg_entry_test_0_high,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_high,
	/* state options */     (0)
	},
};

/* Event masks for state set "ramp" */
static const seqMask seqg_mask_ramp_1_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_ramp_1_up[] = {
	0x00000002,
};
static const seqMask seqg_mask_ramp_1_down[] = {
	0x00000002,
};

/* State table for state set "ramp" */
static seqState seqg_states_ramp[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_ramp_1_init,
	/* event function */    seqg_event_ramp_1_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_1_init,
	/* state options */     (0)
	},
	{
	/* state name */        "up",
	/* action function */   seqg_action_ramp_1_up,
	/* event function */    seqg_event_ramp_1_up,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_1_up,
	/* state options */     (0)
	},
	{
	/* state name */        "down",
	/* action function */   seqg_action_ramp_1_down,
	/* event function */    seqg_event_ramp_1_down,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_1_down,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "test",
	/* states */            seqg_states_test,
	/* number of states */  2
	},

	{
	/* state set name */    "ramp",
	/* states */            seqg_states_ramp,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram delayTest = {
	/* magic number */      2002005,
	/* program name */      "delayTest",
	/* channels */          seqg_chans,
	/* num. channels */     1,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME delayTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void delayTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&delayTest);
}
epicsExportRegistrar(delayTestRegistrar);
