/* C code for program versionTest, generated by snc from ../version.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 4 "../version.st"
#include <stdlib.h>    /* for exit() */

/* Variable declarations */


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 8 "../version.st"
	printf("conditional compilation in\n");
# line 10 "../version.st"
	printf("seq version is 2.2 or greater\n");
	

    printf("seq version is 2.2 or greater\n");


#line 22 "../version.st"

	/* an #include "seq_release.h" is not needed when testing inside escaped C code */
	#if 2002005 >= 2002000
	printf("seq version is 2.2 or greater\n");
	#else
	printf("seq version is 2.1 or less\n");
	#endif
}

/****** Code for state "x" in state set "x" ******/

/* Event function for state "x" in state set "x" */
static seqBool seqg_event_x_0_x(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 33 "../version.st"
	if (seq_delay(seqg_env, 1))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "x" in state set "x" */
static void seqg_action_x_0_x(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 33 "../version.st"
			exit(0);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "x" */
static const seqMask seqg_mask_x_0_x[] = {
	0x00000000,
};

/* State table for state set "x" */
static seqState seqg_states_x[] = {
	{
	/* state name */        "x",
	/* action function */   seqg_action_x_0_x,
	/* event function */    seqg_event_x_0_x,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_x_0_x,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "x",
	/* states */            seqg_states_x,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram versionTest = {
	/* magic number */      2002005,
	/* program name */      "versionTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME versionTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void versionTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&versionTest);
}
epicsExportRegistrar(versionTestRegistrar);
