/* C code for program demo, generated by snc from ../demo.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 36 "../demo.st"
#include "errlog.h"
# line 61 "../demo.st"
static const EF_ID loFlag = 1;
# line 67 "../demo.st"
static const EF_ID hiFlag = 2;

/* Variable declarations */
struct seqg_vars {
# line 42 "../demo.st"
	int light;
# line 45 "../demo.st"
	double lightOn;
# line 49 "../demo.st"
	double lightOff;
# line 54 "../demo.st"
	double voltage;
# line 58 "../demo.st"
	double loLimit;
# line 64 "../demo.st"
	double hiLimit;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "START" in state set "light" ******/

/* Event function for state "START" in state set "light" */
static seqBool seqg_event_light_0_START(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "START" in state set "light" */
static void seqg_action_light_0_START(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 75 "../demo.st"
			seqg_var->light = 0;
# line 76 "../demo.st"
			seq_pvPutTmo(seqg_env, 0/*light*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "LIGHT_OFF" in state set "light" ******/

/* Event function for state "LIGHT_OFF" in state set "light" */
static seqBool seqg_event_light_0_LIGHT_OFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 81 "../demo.st"
	if (seqg_var->voltage > seqg_var->lightOn)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "LIGHT_OFF" in state set "light" */
static void seqg_action_light_0_LIGHT_OFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 82 "../demo.st"
			seqg_var->light = 1;
# line 83 "../demo.st"
			seq_pvPutTmo(seqg_env, 0/*light*/, DEFAULT, DEFAULT_TIMEOUT);
# line 84 "../demo.st"
			errlogPrintf("light_off -> light_on\n");
		}
		return;
	}
}

/****** Code for state "LIGHT_ON" in state set "light" ******/

/* Event function for state "LIGHT_ON" in state set "light" */
static seqBool seqg_event_light_0_LIGHT_ON(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 89 "../demo.st"
	if (seqg_var->voltage < seqg_var->lightOff)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "LIGHT_ON" in state set "light" */
static void seqg_action_light_0_LIGHT_ON(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 90 "../demo.st"
			seqg_var->light = 0;
# line 91 "../demo.st"
			seq_pvPutTmo(seqg_env, 0/*light*/, DEFAULT, DEFAULT_TIMEOUT);
# line 92 "../demo.st"
			errlogPrintf("light_on -> light_off\n");
		}
		return;
	}
}

/****** Code for state "START" in state set "ramp" ******/

/* Event function for state "START" in state set "ramp" */
static seqBool seqg_event_ramp_1_START(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "START" in state set "ramp" */
static void seqg_action_ramp_1_START(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 101 "../demo.st"
			seqg_var->voltage = seqg_var->loLimit;
# line 102 "../demo.st"
			seq_pvPutTmo(seqg_env, 3/*voltage*/, DEFAULT, DEFAULT_TIMEOUT);
# line 103 "../demo.st"
			errlogPrintf("start -> ramp_up\n");
		}
		return;
	}
}

/****** Code for state "RAMP_UP" in state set "ramp" ******/

/* Event function for state "RAMP_UP" in state set "ramp" */
static seqBool seqg_event_ramp_1_RAMP_UP(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 108 "../demo.st"
	if (seqg_var->voltage > seqg_var->hiLimit)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 112 "../demo.st"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "RAMP_UP" in state set "ramp" */
static void seqg_action_ramp_1_RAMP_UP(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 109 "../demo.st"
			errlogPrintf("ramp_up -> ramp_down\n");
		}
		return;
	case 1:
		{
# line 113 "../demo.st"
			seqg_var->voltage += 0.1;
# line 114 "../demo.st"
			if (seq_pvPutTmo(seqg_env, 3/*voltage*/, DEFAULT, DEFAULT_TIMEOUT) < 0)
# line 115 "../demo.st"
				errlogPrintf("pvPut( voltage ) failed\n");
		}
		return;
	}
}

/****** Code for state "RAMP_DOWN" in state set "ramp" ******/

/* Event function for state "RAMP_DOWN" in state set "ramp" */
static seqBool seqg_event_ramp_1_RAMP_DOWN(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 121 "../demo.st"
	if (seqg_var->voltage < seqg_var->loLimit)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 125 "../demo.st"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "RAMP_DOWN" in state set "ramp" */
static void seqg_action_ramp_1_RAMP_DOWN(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 122 "../demo.st"
			errlogPrintf("ramp_down -> ramp_up\n");
		}
		return;
	case 1:
		{
# line 126 "../demo.st"
			seqg_var->voltage -= 0.1;
# line 127 "../demo.st"
			if (seq_pvPutTmo(seqg_env, 3/*voltage*/, DEFAULT, DEFAULT_TIMEOUT) < 0)
# line 128 "../demo.st"
				errlogPrintf("pvPut( voltage ) failed\n");
		}
		return;
	}
}

/****** Code for state "START" in state set "limit" ******/

/* Event function for state "START" in state set "limit" */
static seqBool seqg_event_limit_2_START(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 137 "../demo.st"
	if (seq_efTestAndClear(seqg_env, loFlag) && seqg_var->loLimit > seqg_var->hiLimit)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 142 "../demo.st"
	if (seq_efTestAndClear(seqg_env, hiFlag) && seqg_var->hiLimit < seqg_var->loLimit)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "START" in state set "limit" */
static void seqg_action_limit_2_START(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 138 "../demo.st"
			seqg_var->hiLimit = seqg_var->loLimit;
# line 139 "../demo.st"
			seq_pvPutTmo(seqg_env, 5/*hiLimit*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 143 "../demo.st"
			seqg_var->loLimit = seqg_var->hiLimit;
# line 144 "../demo.st"
			seq_pvPutTmo(seqg_env, 4/*loLimit*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{prefix}:light", offsetof(struct seqg_vars, light), "light", P_INT, 1, 3, 0, 0, 0, 0},
	{"{prefix}:lightOn", offsetof(struct seqg_vars, lightOn), "lightOn", P_DOUBLE, 1, 4, 0, 1, 0, 0},
	{"{prefix}:lightOff", offsetof(struct seqg_vars, lightOff), "lightOff", P_DOUBLE, 1, 5, 0, 1, 0, 0},
	{"{prefix}:voltage", offsetof(struct seqg_vars, voltage), "voltage", P_DOUBLE, 1, 6, 0, 1, 0, 0},
	{"{prefix}:loLimit", offsetof(struct seqg_vars, loLimit), "loLimit", P_DOUBLE, 1, 7, 1, 1, 0, 0},
	{"{prefix}:hiLimit", offsetof(struct seqg_vars, hiLimit), "hiLimit", P_DOUBLE, 1, 8, 2, 1, 0, 0},
};

/* Event masks for state set "light" */
static const seqMask seqg_mask_light_0_START[] = {
	0x00000000,
};
static const seqMask seqg_mask_light_0_LIGHT_OFF[] = {
	0x00000050,
};
static const seqMask seqg_mask_light_0_LIGHT_ON[] = {
	0x00000060,
};

/* State table for state set "light" */
static seqState seqg_states_light[] = {
	{
	/* state name */        "START",
	/* action function */   seqg_action_light_0_START,
	/* event function */    seqg_event_light_0_START,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_light_0_START,
	/* state options */     (0)
	},
	{
	/* state name */        "LIGHT_OFF",
	/* action function */   seqg_action_light_0_LIGHT_OFF,
	/* event function */    seqg_event_light_0_LIGHT_OFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_light_0_LIGHT_OFF,
	/* state options */     (0)
	},
	{
	/* state name */        "LIGHT_ON",
	/* action function */   seqg_action_light_0_LIGHT_ON,
	/* event function */    seqg_event_light_0_LIGHT_ON,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_light_0_LIGHT_ON,
	/* state options */     (0)
	},
};

/* Event masks for state set "ramp" */
static const seqMask seqg_mask_ramp_1_START[] = {
	0x00000000,
};
static const seqMask seqg_mask_ramp_1_RAMP_UP[] = {
	0x00000140,
};
static const seqMask seqg_mask_ramp_1_RAMP_DOWN[] = {
	0x000000c0,
};

/* State table for state set "ramp" */
static seqState seqg_states_ramp[] = {
	{
	/* state name */        "START",
	/* action function */   seqg_action_ramp_1_START,
	/* event function */    seqg_event_ramp_1_START,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_1_START,
	/* state options */     (0)
	},
	{
	/* state name */        "RAMP_UP",
	/* action function */   seqg_action_ramp_1_RAMP_UP,
	/* event function */    seqg_event_ramp_1_RAMP_UP,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_1_RAMP_UP,
	/* state options */     (0)
	},
	{
	/* state name */        "RAMP_DOWN",
	/* action function */   seqg_action_ramp_1_RAMP_DOWN,
	/* event function */    seqg_event_ramp_1_RAMP_DOWN,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_1_RAMP_DOWN,
	/* state options */     (0)
	},
};

/* Event masks for state set "limit" */
static const seqMask seqg_mask_limit_2_START[] = {
	0x00000186,
};

/* State table for state set "limit" */
static seqState seqg_states_limit[] = {
	{
	/* state name */        "START",
	/* action function */   seqg_action_limit_2_START,
	/* event function */    seqg_event_limit_2_START,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_limit_2_START,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "light",
	/* states */            seqg_states_light,
	/* number of states */  3
	},

	{
	/* state set name */    "ramp",
	/* states */            seqg_states_ramp,
	/* number of states */  3
	},

	{
	/* state set name */    "limit",
	/* states */            seqg_states_limit,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram demo = {
	/* magic number */      2002005,
	/* program name */      "demo",
	/* channels */          seqg_chans,
	/* num. channels */     6,
	/* state sets */        seqg_statesets,
	/* num. state sets */   3,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "pvsys=ca",
	/* num. event flags */  2,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void demoRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&demo);
}
epicsExportRegistrar(demoRegistrar);
