#define TOK_EQUAL                            1
#define TOK_ADDEQ                            2
#define TOK_SUBEQ                            3
#define TOK_ANDEQ                            4
#define TOK_OREQ                             5
#define TOK_DIVEQ                            6
#define TOK_MULEQ                            7
#define TOK_MODEQ                            8
#define TOK_LSHEQ                            9
#define TOK_RSHEQ                           10
#define TOK_XOREQ                           11
#define TOK_QUESTION                        12
#define TOK_COLON                           13
#define TOK_OROR                            14
#define TOK_ANDAND                          15
#define TOK_VBAR                            16
#define TOK_CARET                           17
#define TOK_AMPERSAND                       18
#define TOK_EQ                              19
#define TOK_NE                              20
#define TOK_GT                              21
#define TOK_GE                              22
#define TOK_LE                              23
#define TOK_LT                              24
#define TOK_LSHIFT                          25
#define TOK_RSHIFT                          26
#define TOK_ADD                             27
#define TOK_SUB                             28
#define TOK_ASTERISK                        29
#define TOK_SLASH                           30
#define TOK_MOD                             31
#define TOK_NOT                             32
#define TOK_TILDE                           33
#define TOK_INCR                            34
#define TOK_DECR                            35
#define TOK_SIZEOF                          36
#define TOK_PRE                             37
#define TOK_LBRACKET                        38
#define TOK_LPAREN                          39
#define TOK_POINTER                         40
#define TOK_PERIOD                          41
#define TOK_POST                            42
#define TOK_PROGRAM                         43
#define TOK_NAME                            44
#define TOK_RPAREN                          45
#define TOK_ASSIGN                          46
#define TOK_SEMICOLON                       47
#define TOK_LBRACE                          48
#define TOK_RBRACE                          49
#define TOK_TO                              50
#define TOK_COMMA                           51
#define TOK_MONITOR                         52
#define TOK_SYNC                            53
#define TOK_SYNCQ                           54
#define TOK_INTCON                          55
#define TOK_RBRACKET                        56
#define TOK_CONST                           57
#define TOK_FOREIGN                         58
#define TOK_CHAR                            59
#define TOK_SHORT                           60
#define TOK_INT                             61
#define TOK_LONG                            62
#define TOK_UNSIGNED                        63
#define TOK_INT8T                           64
#define TOK_UINT8T                          65
#define TOK_INT16T                          66
#define TOK_UINT16T                         67
#define TOK_INT32T                          68
#define TOK_UINT32T                         69
#define TOK_FLOAT                           70
#define TOK_DOUBLE                          71
#define TOK_STRING                          72
#define TOK_EVFLAG                          73
#define TOK_VOID                            74
#define TOK_ENUM                            75
#define TOK_STRUCT                          76
#define TOK_UNION                           77
#define TOK_TYPENAME                        78
#define TOK_OPTION                          79
#define TOK_SS                              80
#define TOK_STATE                           81
#define TOK_ENTRY                           82
#define TOK_EXIT                            83
#define TOK_WHEN                            84
#define TOK_BREAK                           85
#define TOK_CONTINUE                        86
#define TOK_RETURN                          87
#define TOK_IF                              88
#define TOK_ELSE                            89
#define TOK_WHILE                           90
#define TOK_FOR                             91
#define TOK_FPCON                           92
#define TOK_STRCON                          93
#define TOK_CCODE                           94
