/* C code for program funcdefTest, generated by snc from ../funcdef.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 8 "../funcdef.st"
static void *f1(SS_ID seqg_env)
{
# line 10 "../funcdef.st"
	seq_pvPutTmo(seqg_env, 0/*x*/, DEFAULT, DEFAULT_TIMEOUT);
	return 0;
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 14 "../funcdef.st"
static void *f1a(SS_ID seqg_env)
{
	return 0;
}
#undef seqg_var

/* Variable declarations */
struct seqg_vars {
# line 5 "../funcdef.st"
	int x;
};


/* Function declarations */
# line 8 "../funcdef.st"
static void *f1(SS_ID seqg_env);
# line 14 "../funcdef.st"
static void *f1a(SS_ID seqg_env);
# line 20 "../funcdef.st"
static void pvSetX(SS_ID seqg_env, int val);
# line 32 "../funcdef.st"
static void *f2(SS_ID seqg_env, void *x, double **d);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "simple" in state set "simple" ******/

/* Event function for state "simple" in state set "simple" */
static seqBool seqg_event_simple_0_simple(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "simple" in state set "simple" */
static void seqg_action_simple_0_simple(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 25 "../funcdef.st"
			void *p = f1(seqg_env);
# line 26 "../funcdef.st"
			p = f2(seqg_env, p, (double **)f1a);
# line 27 "../funcdef.st"
			pvSetX(seqg_env, 1.0);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, x), "x", P_INT, 1, 1, 0, 0, 0, 0},
};

/* Event masks for state set "simple" */
static const seqMask seqg_mask_simple_0_simple[] = {
	0x00000000,
};

/* State table for state set "simple" */
static seqState seqg_states_simple[] = {
	{
	/* state name */        "simple",
	/* action function */   seqg_action_simple_0_simple,
	/* event function */    seqg_event_simple_0_simple,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_simple_0_simple,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "simple",
	/* states */            seqg_states_simple,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram funcdefTest = {
	/* magic number */      2002005,
	/* program name */      "funcdefTest",
	/* channels */          seqg_chans,
	/* num. channels */     1,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 32 "../funcdef.st"
static void *f2(SS_ID seqg_env, void *x, double **d)
{
# line 34 "../funcdef.st"
	void *(*f)(SS_ID seqg_env) = (void *(*)(SS_ID seqg_env))x;
	return f(seqg_env);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 38 "../funcdef.st"
static void pvSetX(SS_ID seqg_env, int val)
{
# line 40 "../funcdef.st"
	seq_pvPutTmo(seqg_env, 0/*x*/, val, DEFAULT_TIMEOUT);
# line 41 "../funcdef.st"
	printf("x=%d, val=%d\n", seqg_var->x, val);
}
#undef seqg_var

#define PROG_NAME funcdefTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void funcdefTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&funcdefTest);
}
epicsExportRegistrar(funcdefTestRegistrar);
