/* C code for program namingConflictTest, generated by snc from ../namingConflict.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "y_z" in state set "x" ******/

/* Event function for state "y_z" in state set "x" */
static seqBool seqg_event_x_0_y_z(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "y_z" in state set "x" */
static void seqg_action_x_0_y_z(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "z" in state set "x_y" ******/

/* Event function for state "z" in state set "x_y" */
static seqBool seqg_event_x_y_1_z(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "z" in state set "x_y" */
static void seqg_action_x_y_1_z(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "x" */
static const seqMask seqg_mask_x_0_y_z[] = {
	0x00000000,
};

/* State table for state set "x" */
static seqState seqg_states_x[] = {
	{
	/* state name */        "y_z",
	/* action function */   seqg_action_x_0_y_z,
	/* event function */    seqg_event_x_0_y_z,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_x_0_y_z,
	/* state options */     (0)
	},
};

/* Event masks for state set "x_y" */
static const seqMask seqg_mask_x_y_1_z[] = {
	0x00000000,
};

/* State table for state set "x_y" */
static seqState seqg_states_x_y[] = {
	{
	/* state name */        "z",
	/* action function */   seqg_action_x_y_1_z,
	/* event function */    seqg_event_x_y_1_z,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_x_y_1_z,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "x",
	/* states */            seqg_states_x,
	/* number of states */  1
	},

	{
	/* state set name */    "x_y",
	/* states */            seqg_states_x_y,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram namingConflictTest = {
	/* magic number */      2002005,
	/* program name */      "namingConflictTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME namingConflictTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void namingConflictTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&namingConflictTest);
}
epicsExportRegistrar(namingConflictTestRegistrar);
