/* C code for program type_exprTest, generated by snc from ../type_expr.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */
struct seqg_vars {
	char seqg_dummy;
	char dummy;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 12 "../type_expr.st"
	long n = 0;
# line 13 "../type_expr.st"
	void *p = (void *)n;
# line 14 "../type_expr.st"
	void **pp = (void **)n;
# line 15 "../type_expr.st"
	void (*pf1)(SS_ID seqg_env) = (void (*)(SS_ID seqg_env))n;
# line 16 "../type_expr.st"
	void (*pf2)(SS_ID seqg_env, int x, int) = (void (*)(SS_ID seqg_env, int, int))n;
# line 17 "../type_expr.st"
	void (*pf3)(SS_ID seqg_env, int *) = (void (*)(SS_ID seqg_env, int *))n;
# line 18 "../type_expr.st"
	void (*pf4)(SS_ID seqg_env, int **) = (void (*)(SS_ID seqg_env, int **))n;
# line 19 "../type_expr.st"
	void (*pf5)(SS_ID seqg_env, double **, int) = (void (*)(SS_ID seqg_env, double **, int))n;
# line 20 "../type_expr.st"
	void (*pf6)(SS_ID seqg_env, double **, int (**)[2]) = (void (*)(SS_ID seqg_env, double **, int (**)[2]))n;
# line 21 "../type_expr.st"
	int const c = (int const)n;
# line 22 "../type_expr.st"
	int const *pc = (int const *)n;
# line 23 "../type_expr.st"
	unsigned long *const cp = (unsigned long *const)n;
# line 24 "../type_expr.st"
	double **pd = (double **)(int *)n;
# line 25 "../type_expr.st"
	double **ppd = (double **)(int (*)[3])n;
# line 26 "../type_expr.st"
	void (*lf)(SS_ID seqg_env, void *p, void **pp, void (*pf1)(SS_ID seqg_env), void (*pf2)(SS_ID seqg_env, int x, int), void (*pf3)(SS_ID seqg_env, int *), void (*pf4)(SS_ID seqg_env, int **), void (*pf5)(SS_ID seqg_env, double **, int), void (*pf6)(SS_ID seqg_env, double **, int (**)[2]), int const c, int const *pc, unsigned long *const cp, double **pd, double **ppd) = (void (*)(SS_ID seqg_env, void *p, void **pp, void (*pf1)(SS_ID seqg_env), void (*pf2)(SS_ID seqg_env, int x, int), void (*pf3)(SS_ID seqg_env, int *), void (*pf4)(SS_ID seqg_env, int **), void (*pf5)(SS_ID seqg_env, double **, int), void (*pf6)(SS_ID seqg_env, double **, int (**)[2]), int const c, int const *pc, unsigned long *const cp, double **pd, double **ppd))n;
# line 55 "../type_expr.st"
	lf(seqg_env, p, pp, pf1, pf2, pf3, pf4, pf5, pf6, c, pc, cp, pd, ppd);
}

/****** Code for state "simple" in state set "simple" ******/

/* Event function for state "simple" in state set "simple" */
static seqBool seqg_event_simple_0_simple(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "simple" in state set "simple" */
static void seqg_action_simple_0_simple(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "simple" */
static const seqMask seqg_mask_simple_0_simple[] = {
	0x00000000,
};

/* State table for state set "simple" */
static seqState seqg_states_simple[] = {
	{
	/* state name */        "simple",
	/* action function */   seqg_action_simple_0_simple,
	/* event function */    seqg_event_simple_0_simple,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_simple_0_simple,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "simple",
	/* states */            seqg_states_simple,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram type_exprTest = {
	/* magic number */      2002005,
	/* program name */      "type_exprTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME type_exprTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void type_exprTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&type_exprTest);
}
epicsExportRegistrar(type_exprTestRegistrar);
