/* C code for program johng, generated by snc from ../johng.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 18 "../johng.st"
static const EF_ID utcFlag = 1;

/* Variable declarations */
struct seqg_vars {
# line 13 "../johng.st"
	double utc;
# line 22 "../johng.st"
	double telfocus;
# line 27 "../johng.st"
	char *ring_str;
	struct seqg_vars_utc {
# line 35 "../johng.st"
		double telfocusSave;
		struct {
# line 40 "../johng.st"
			int count;
		} seqg_vars_start;
	} seqg_vars_utc;
	struct seqg_vars_RING {
		struct {
# line 84 "../johng.st"
			int count2;
		} seqg_vars_start;
	} seqg_vars_RING;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 27 "../johng.st"
	static char *seqg_initvar_ring_str = "ring...\n";
	memcpy(&seqg_var->ring_str, &seqg_initvar_ring_str, sizeof(seqg_initvar_ring_str));
	}
	{
# line 40 "../johng.st"
	static int seqg_initvar_count = 0;
	memcpy(&seqg_var->seqg_vars_utc.seqg_vars_start.count, &seqg_initvar_count, sizeof(seqg_initvar_count));
	}
	{
# line 84 "../johng.st"
	static int seqg_initvar_count2 = 1;
	memcpy(&seqg_var->seqg_vars_RING.seqg_vars_start.count2, &seqg_initvar_count2, sizeof(seqg_initvar_count2));
	}
}

/****** Code for state "start" in state set "utc" ******/

/* Event function for state "start" in state set "utc" */
static seqBool seqg_event_utc_0_start(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 43 "../johng.st"
	if (seq_efTestAndClear(seqg_env, utcFlag))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 49 "../johng.st"
	if (seqg_var->seqg_vars_utc.seqg_vars_start.count == 10)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "start" in state set "utc" */
static void seqg_action_utc_0_start(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 44 "../johng.st"
			printf("utc = %.3f\n", seqg_var->utc);
# line 45 "../johng.st"
			seqg_var->seqg_vars_utc.seqg_vars_start.count++;
		}
		return;
	case 1:
		{
# line 50 "../johng.st"
			printf("count has hit limit (telfocus = %g)\n", seqg_var->telfocus);
# line 51 "../johng.st"
			seqg_var->seqg_vars_utc.telfocusSave = seqg_var->telfocus;
# line 52 "../johng.st"
			seqg_var->seqg_vars_utc.seqg_vars_start.count = 0;
		}
		return;
	}
}

/****** Code for state "next" in state set "utc" ******/

/* Event function for state "next" in state set "utc" */
static seqBool seqg_event_utc_0_next(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 60 "../johng.st"
	if (seqg_var->telfocus > seqg_var->seqg_vars_utc.telfocusSave)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 66 "../johng.st"
	if (seq_delay(seqg_env, 5))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "next" in state set "utc" */
static void seqg_action_utc_0_next(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 61 "../johng.st"
			printf("telfocus = %g\n", seqg_var->telfocus);
# line 62 "../johng.st"
			seqg_var->seqg_vars_utc.telfocusSave = seqg_var->telfocus;
		}
		return;
	case 1:
		{
# line 67 "../johng.st"
			printf("timeout (telfocus didn't increase)\n");
		}
		return;
	}
}

/****** Code for state "start" in state set "ring" ******/

/* Event function for state "start" in state set "ring" */
static seqBool seqg_event_ring_1_start(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 75 "../johng.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "start" in state set "ring" */
static void seqg_action_ring_1_start(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 76 "../johng.st"
			printf("%s", seqg_var->ring_str);
		}
		return;
	}
}

/****** Code for state "start" in state set "RING" ******/

/* Entry function for state "start" in state set "RING" */
static void seqg_entry_RING_2_start(SS_ID seqg_env)
{
# line 89 "../johng.st"
	seqg_var->ring_str = "RING...\n";
}

/* Event function for state "start" in state set "RING" */
static seqBool seqg_event_RING_2_start(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 91 "../johng.st"
	if (seq_delay(seqg_env, seqg_var->seqg_vars_RING.seqg_vars_start.count2))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "start" in state set "RING" */
static void seqg_action_RING_2_start(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 92 "../johng.st"
			printf("%s", seqg_var->ring_str);
# line 93 "../johng.st"
			if (seqg_var->seqg_vars_RING.seqg_vars_start.count2 < 16)
# line 93 "../johng.st"
				seqg_var->seqg_vars_RING.seqg_vars_start.count2 = 2 * seqg_var->seqg_vars_RING.seqg_vars_start.count2;
			else
# line 93 "../johng.st"
				seqg_var->seqg_vars_RING.seqg_vars_start.count2 = 1;
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"dcs0.utc", offsetof(struct seqg_vars, utc), "utc", P_DOUBLE, 1, 2, 1, 1, 0, 0},
	{"dcs0.telfocus", offsetof(struct seqg_vars, telfocus), "telfocus", P_DOUBLE, 1, 3, 0, 1, 0, 0},
};

/* Event masks for state set "utc" */
static const seqMask seqg_mask_utc_0_start[] = {
	0x00000002,
};
static const seqMask seqg_mask_utc_0_next[] = {
	0x00000008,
};

/* State table for state set "utc" */
static seqState seqg_states_utc[] = {
	{
	/* state name */        "start",
	/* action function */   seqg_action_utc_0_start,
	/* event function */    seqg_event_utc_0_start,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_utc_0_start,
	/* state options */     (0)
	},
	{
	/* state name */        "next",
	/* action function */   seqg_action_utc_0_next,
	/* event function */    seqg_event_utc_0_next,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_utc_0_next,
	/* state options */     (0)
	},
};

/* Event masks for state set "ring" */
static const seqMask seqg_mask_ring_1_start[] = {
	0x00000000,
};

/* State table for state set "ring" */
static seqState seqg_states_ring[] = {
	{
	/* state name */        "start",
	/* action function */   seqg_action_ring_1_start,
	/* event function */    seqg_event_ring_1_start,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ring_1_start,
	/* state options */     (0)
	},
};

/* Event masks for state set "RING" */
static const seqMask seqg_mask_RING_2_start[] = {
	0x00000000,
};

/* State table for state set "RING" */
static seqState seqg_states_RING[] = {
	{
	/* state name */        "start",
	/* action function */   seqg_action_RING_2_start,
	/* event function */    seqg_event_RING_2_start,
	/* entry function */    seqg_entry_RING_2_start,
	/* exit function */     0,
	/* event mask array */  seqg_mask_RING_2_start,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "utc",
	/* states */            seqg_states_utc,
	/* number of states */  2
	},

	{
	/* state set name */    "ring",
	/* states */            seqg_states_ring,
	/* number of states */  1
	},

	{
	/* state set name */    "RING",
	/* states */            seqg_states_RING,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram johng = {
	/* magic number */      2002005,
	/* program name */      "johng",
	/* channels */          seqg_chans,
	/* num. channels */     2,
	/* state sets */        seqg_statesets,
	/* num. state sets */   3,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  1,
	/* encoded options */   (0 | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME johng
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void johngRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&johng);
}
epicsExportRegistrar(johngRegistrar);
