/* C code for program assignTest, generated by snc from ../assign.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 11 "../assign.st"
#include "../testSupport.h"

/* Variable declarations */
struct seqg_vars {
# line 13 "../assign.st"
	int x;
	struct seqg_vars_w {
# line 23 "../assign.st"
		int n;
	} seqg_vars_w;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 13 "../assign.st"
	static int seqg_initvar_x = 0;
	memcpy(&seqg_var->x, &seqg_initvar_x, sizeof(seqg_initvar_x));
	}
	{
# line 23 "../assign.st"
	static int seqg_initvar_n = 1;
	memcpy(&seqg_var->seqg_vars_w.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 19 "../assign.st"
	seq_test_init(3);
}

/****** Code for state "w" in state set "w" ******/

/* Event function for state "w" in state set "w" */
static seqBool seqg_event_w_0_w(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 25 "../assign.st"
	if (seqg_var->seqg_vars_w.n > 3)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 27 "../assign.st"
	if (seq_delay(seqg_env, 0.01))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "w" in state set "w" */
static void seqg_action_w_0_w(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 28 "../assign.st"
			int status;
# line 29 "../assign.st"
			seqg_var->x = !seqg_var->x;
# line 30 "../assign.st"
			status = seq_pvPutTmo(seqg_env, 0/*x*/, DEFAULT, DEFAULT_TIMEOUT);
# line 31 "../assign.st"
			testOk1(status == pvStatERROR);
# line 32 "../assign.st"
			seqg_var->seqg_vars_w.n++;
		}
		return;
	}
}

/****** Code for state "yes" in state set "r" ******/

/* Event function for state "yes" in state set "r" */
static seqBool seqg_event_r_1_yes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 39 "../assign.st"
	if (!seqg_var->x)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "yes" in state set "r" */
static void seqg_action_r_1_yes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "no" in state set "r" ******/

/* Event function for state "no" in state set "r" */
static seqBool seqg_event_r_1_no(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 43 "../assign.st"
	if (seqg_var->x)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "no" in state set "r" */
static void seqg_action_r_1_no(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 49 "../assign.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, x), "x", P_INT, 1, 1, 0, 0, 0, 0},
};

/* Event masks for state set "w" */
static const seqMask seqg_mask_w_0_w[] = {
	0x00000000,
};

/* State table for state set "w" */
static seqState seqg_states_w[] = {
	{
	/* state name */        "w",
	/* action function */   seqg_action_w_0_w,
	/* event function */    seqg_event_w_0_w,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_w_0_w,
	/* state options */     (0)
	},
};

/* Event masks for state set "r" */
static const seqMask seqg_mask_r_1_yes[] = {
	0x00000002,
};
static const seqMask seqg_mask_r_1_no[] = {
	0x00000002,
};

/* State table for state set "r" */
static seqState seqg_states_r[] = {
	{
	/* state name */        "yes",
	/* action function */   seqg_action_r_1_yes,
	/* event function */    seqg_event_r_1_yes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_r_1_yes,
	/* state options */     (0)
	},
	{
	/* state name */        "no",
	/* action function */   seqg_action_r_1_no,
	/* event function */    seqg_event_r_1_no,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_r_1_no,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "w",
	/* states */            seqg_states_w,
	/* number of states */  1
	},

	{
	/* state set name */    "r",
	/* states */            seqg_states_r,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram assignTest = {
	/* magic number */      2002005,
	/* program name */      "assignTest",
	/* channels */          seqg_chans,
	/* num. channels */     1,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME assignTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void assignTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&assignTest);
}
epicsExportRegistrar(assignTestRegistrar);
