/* C code for program bittypesTest, generated by snc from ../bittypes.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../bittypes.st"
#include "../testSupport.h"

/* Variable declarations */
# line 11 "../bittypes.st"
static	epicsInt8 i8;
# line 12 "../bittypes.st"
static	epicsUInt8 ui8;
# line 13 "../bittypes.st"
static	epicsInt16 i16;
# line 14 "../bittypes.st"
static	epicsUInt16 ui16;
# line 15 "../bittypes.st"
static	epicsInt32 i32;
# line 16 "../bittypes.st"
static	epicsUInt32 ui32;
struct seqg_vars_test {
	struct {
# line 41 "../bittypes.st"
		epicsInt8 xi8;
# line 42 "../bittypes.st"
		epicsUInt8 xui8;
# line 43 "../bittypes.st"
		epicsInt16 xi16;
# line 44 "../bittypes.st"
		epicsUInt16 xui16;
# line 45 "../bittypes.st"
		epicsInt32 xi32;
# line 46 "../bittypes.st"
		epicsUInt32 xui32;
	} seqg_vars_conversion;
} seqg_vars_test;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 41 "../bittypes.st"
	static epicsInt8 seqg_initvar_xi8 = -1;
	memcpy(&seqg_vars_test.seqg_vars_conversion.xi8, &seqg_initvar_xi8, sizeof(seqg_initvar_xi8));
	}
	{
# line 42 "../bittypes.st"
	static epicsUInt8 seqg_initvar_xui8 = -1;
	memcpy(&seqg_vars_test.seqg_vars_conversion.xui8, &seqg_initvar_xui8, sizeof(seqg_initvar_xui8));
	}
	{
# line 43 "../bittypes.st"
	static epicsInt16 seqg_initvar_xi16 = -1;
	memcpy(&seqg_vars_test.seqg_vars_conversion.xi16, &seqg_initvar_xi16, sizeof(seqg_initvar_xi16));
	}
	{
# line 44 "../bittypes.st"
	static epicsUInt16 seqg_initvar_xui16 = -1;
	memcpy(&seqg_vars_test.seqg_vars_conversion.xui16, &seqg_initvar_xui16, sizeof(seqg_initvar_xui16));
	}
	{
# line 45 "../bittypes.st"
	static epicsInt32 seqg_initvar_xi32 = -1;
	memcpy(&seqg_vars_test.seqg_vars_conversion.xi32, &seqg_initvar_xi32, sizeof(seqg_initvar_xi32));
	}
	{
# line 46 "../bittypes.st"
	static epicsUInt32 seqg_initvar_xui32 = -1;
	memcpy(&seqg_vars_test.seqg_vars_conversion.xui32, &seqg_initvar_xui32, sizeof(seqg_initvar_xui32));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 26 "../bittypes.st"
	seq_test_init(24);
}

/****** Code for state "sizes" in state set "test" ******/

/* Event function for state "sizes" in state set "test" */
static seqBool seqg_event_test_0_sizes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "sizes" in state set "test" */
static void seqg_action_test_0_sizes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 32 "../bittypes.st"
			testOk1(sizeof((i8)) == 1);
# line 33 "../bittypes.st"
			testOk1(sizeof((ui8)) == 1);
# line 34 "../bittypes.st"
			testOk1(sizeof((i16)) == 2);
# line 35 "../bittypes.st"
			testOk1(sizeof((ui16)) == 2);
# line 36 "../bittypes.st"
			testOk1(sizeof((i32)) == 4);
# line 37 "../bittypes.st"
			testOk1(sizeof((ui32)) == 4);
		}
		return;
	}
}

/****** Code for state "conversion" in state set "test" ******/

/* Event function for state "conversion" in state set "test" */
static seqBool seqg_event_test_0_conversion(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "conversion" in state set "test" */
static void seqg_action_test_0_conversion(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 48 "../bittypes.st"
			int pvstat;
# line 49 "../bittypes.st"
			i8 = seqg_vars_test.seqg_vars_conversion.xi8;
# line 50 "../bittypes.st"
			pvstat = seq_pvPutTmo(seqg_env, 0/*i8*/, SYNC, DEFAULT_TIMEOUT);
# line 51 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 52 "../bittypes.st"
			pvstat = seq_pvGetTmo(seqg_env, 0/*i8*/, DEFAULT, DEFAULT_TIMEOUT);
# line 53 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 54 "../bittypes.st"
			testOk1(i8 == seqg_vars_test.seqg_vars_conversion.xi8);
# line 55 "../bittypes.st"
			ui8 = seqg_vars_test.seqg_vars_conversion.xui8;
# line 56 "../bittypes.st"
			pvstat = seq_pvPutTmo(seqg_env, 1/*ui8*/, SYNC, DEFAULT_TIMEOUT);
# line 57 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 58 "../bittypes.st"
			pvstat = seq_pvGetTmo(seqg_env, 1/*ui8*/, DEFAULT, DEFAULT_TIMEOUT);
# line 59 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 60 "../bittypes.st"
			testOk1(ui8 == seqg_vars_test.seqg_vars_conversion.xui8);
# line 61 "../bittypes.st"
			i16 = seqg_vars_test.seqg_vars_conversion.xi16;
# line 62 "../bittypes.st"
			pvstat = seq_pvPutTmo(seqg_env, 2/*i16*/, SYNC, DEFAULT_TIMEOUT);
# line 63 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 64 "../bittypes.st"
			pvstat = seq_pvGetTmo(seqg_env, 2/*i16*/, DEFAULT, DEFAULT_TIMEOUT);
# line 65 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 66 "../bittypes.st"
			testOk1(i16 == seqg_vars_test.seqg_vars_conversion.xi16);
# line 67 "../bittypes.st"
			ui16 = seqg_vars_test.seqg_vars_conversion.xui16;
# line 68 "../bittypes.st"
			pvstat = seq_pvPutTmo(seqg_env, 3/*ui16*/, SYNC, DEFAULT_TIMEOUT);
# line 69 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 70 "../bittypes.st"
			pvstat = seq_pvGetTmo(seqg_env, 3/*ui16*/, DEFAULT, DEFAULT_TIMEOUT);
# line 71 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 72 "../bittypes.st"
			testOk1(ui16 == seqg_vars_test.seqg_vars_conversion.xui16);
# line 73 "../bittypes.st"
			i32 = seqg_vars_test.seqg_vars_conversion.xi32;
# line 74 "../bittypes.st"
			pvstat = seq_pvPutTmo(seqg_env, 4/*i32*/, SYNC, DEFAULT_TIMEOUT);
# line 75 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 76 "../bittypes.st"
			pvstat = seq_pvGetTmo(seqg_env, 4/*i32*/, DEFAULT, DEFAULT_TIMEOUT);
# line 77 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 78 "../bittypes.st"
			testOk1(i32 != seqg_vars_test.seqg_vars_conversion.xi32);
# line 79 "../bittypes.st"
			ui32 = seqg_vars_test.seqg_vars_conversion.xui32;
# line 80 "../bittypes.st"
			pvstat = seq_pvPutTmo(seqg_env, 5/*ui32*/, SYNC, DEFAULT_TIMEOUT);
# line 81 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 82 "../bittypes.st"
			pvstat = seq_pvGetTmo(seqg_env, 5/*ui32*/, DEFAULT, DEFAULT_TIMEOUT);
# line 83 "../bittypes.st"
			testOk1(pvstat == pvStatOK);
# line 84 "../bittypes.st"
			testOk1(ui32 != seqg_vars_test.seqg_vars_conversion.xui32);
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 90 "../bittypes.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"ushort", (size_t)&i8, "i8", P_INT8T, 1, 1, 0, 0, 0, 0},
	{"ushort", (size_t)&ui8, "ui8", P_UINT8T, 1, 2, 0, 0, 0, 0},
	{"ushort", (size_t)&i16, "i16", P_INT16T, 1, 3, 0, 0, 0, 0},
	{"ushort", (size_t)&ui16, "ui16", P_UINT16T, 1, 4, 0, 0, 0, 0},
	{"ushort", (size_t)&i32, "i32", P_INT32T, 1, 5, 0, 0, 0, 0},
	{"ushort", (size_t)&ui32, "ui32", P_UINT32T, 1, 6, 0, 0, 0, 0},
};

/* Event masks for state set "test" */
static const seqMask seqg_mask_test_0_sizes[] = {
	0x00000000,
};
static const seqMask seqg_mask_test_0_conversion[] = {
	0x00000000,
};

/* State table for state set "test" */
static seqState seqg_states_test[] = {
	{
	/* state name */        "sizes",
	/* action function */   seqg_action_test_0_sizes,
	/* event function */    seqg_event_test_0_sizes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_sizes,
	/* state options */     (0)
	},
	{
	/* state name */        "conversion",
	/* action function */   seqg_action_test_0_conversion,
	/* event function */    seqg_event_test_0_conversion,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_conversion,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "test",
	/* states */            seqg_states_test,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram bittypesTest = {
	/* magic number */      2002005,
	/* program name */      "bittypesTest",
	/* channels */          seqg_chans,
	/* num. channels */     6,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME bittypesTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void bittypesTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&bittypesTest);
}
epicsExportRegistrar(bittypesTestRegistrar);
