/* C code for program changeTest, generated by snc from ../change.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 12 "../change.st"
#include <time.h>
# line 13 "../change.st"
#include <stdlib.h>
# line 14 "../change.st"
#include "../testSupport.h"

/* Variable declarations */
struct seqg_vars {
	char seqg_dummy;
	struct seqg_vars_main {
# line 25 "../change.st"
		int x;
# line 26 "../change.st"
		int n;
	} seqg_vars_main;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 25 "../change.st"
	static int seqg_initvar_x = 0;
	memcpy(&seqg_var->seqg_vars_main.x, &seqg_initvar_x, sizeof(seqg_initvar_x));
	}
	{
# line 26 "../change.st"
	static int seqg_initvar_n = 1;
	memcpy(&seqg_var->seqg_vars_main.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 19 "../change.st"
	seq_test_init(50);
}

/****** Code for state "zero" in state set "main" ******/

/* Event function for state "zero" in state set "main" */
static seqBool seqg_event_main_0_zero(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 28 "../change.st"
	if (seqg_var->seqg_vars_main.n > 50)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 30 "../change.st"
	if (seq_delay(seqg_env, 0.01))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "zero" in state set "main" */
static void seqg_action_main_0_zero(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 31 "../change.st"
			testOk(seqg_var->seqg_vars_main.x == 0, "state=zero, x=%d", seqg_var->seqg_vars_main.x);
# line 32 "../change.st"
			seqg_var->seqg_vars_main.x = rand() % 10 - 5;
# line 33 "../change.st"
			testDiag("new random x=%d", seqg_var->seqg_vars_main.x);
# line 34 "../change.st"
			seqg_var->seqg_vars_main.n++;
# line 35 "../change.st"
			if (seqg_var->seqg_vars_main.x > 0)
			{
				{*seqg_pnst = 1; return;}
			}
			else
# line 37 "../change.st"
				if (seqg_var->seqg_vars_main.x < 0)
				{
					{*seqg_pnst = 2; return;}
				}
		}
		return;
	}
}

/****** Code for state "pos" in state set "main" ******/

/* Event function for state "pos" in state set "main" */
static seqBool seqg_event_main_0_pos(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 43 "../change.st"
	if (seqg_var->seqg_vars_main.n > 50)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 45 "../change.st"
	if (seq_delay(seqg_env, 0.01))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "pos" in state set "main" */
static void seqg_action_main_0_pos(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 46 "../change.st"
			testOk(seqg_var->seqg_vars_main.x > 0, "state=pos, x=%d", seqg_var->seqg_vars_main.x);
# line 47 "../change.st"
			seqg_var->seqg_vars_main.n++;
# line 48 "../change.st"
			seqg_var->seqg_vars_main.x--;
# line 49 "../change.st"
			if (seqg_var->seqg_vars_main.x == 0)
				{*seqg_pnst = 0; return;}
		}
		return;
	}
}

/****** Code for state "neg" in state set "main" ******/

/* Event function for state "neg" in state set "main" */
static seqBool seqg_event_main_0_neg(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 53 "../change.st"
	if (seqg_var->seqg_vars_main.n > 50)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 55 "../change.st"
	if (seq_delay(seqg_env, 0.01))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "neg" in state set "main" */
static void seqg_action_main_0_neg(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 56 "../change.st"
			testOk(seqg_var->seqg_vars_main.x < 0, "state=neg, x=%d", seqg_var->seqg_vars_main.x);
# line 57 "../change.st"
			seqg_var->seqg_vars_main.n++;
# line 58 "../change.st"
			seqg_var->seqg_vars_main.x++;
# line 59 "../change.st"
			if (seqg_var->seqg_vars_main.x == 0)
				{*seqg_pnst = 0; return;}
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 65 "../change.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "main" */
static const seqMask seqg_mask_main_0_zero[] = {
	0x00000000,
};
static const seqMask seqg_mask_main_0_pos[] = {
	0x00000000,
};
static const seqMask seqg_mask_main_0_neg[] = {
	0x00000000,
};

/* State table for state set "main" */
static seqState seqg_states_main[] = {
	{
	/* state name */        "zero",
	/* action function */   seqg_action_main_0_zero,
	/* event function */    seqg_event_main_0_zero,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_main_0_zero,
	/* state options */     (0)
	},
	{
	/* state name */        "pos",
	/* action function */   seqg_action_main_0_pos,
	/* event function */    seqg_event_main_0_pos,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_main_0_pos,
	/* state options */     (0)
	},
	{
	/* state name */        "neg",
	/* action function */   seqg_action_main_0_neg,
	/* event function */    seqg_event_main_0_neg,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_main_0_neg,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "main",
	/* states */            seqg_states_main,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram changeTest = {
	/* magic number */      2002005,
	/* program name */      "changeTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME changeTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void changeTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&changeTest);
}
epicsExportRegistrar(changeTestRegistrar);
