/* C code for program evflagExtTest, generated by snc from ../evflagExt.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../evflagExt.st"
#include "../testSupport.h"
# line 5 "../evflagExt.st"
static const EF_ID e = 1;
# line 7 "../evflagExt.st"
static void extfun(SS_ID ssid);

/* Variable declarations */


/* Function declarations */
# line 50 "../evflagExt.st"
static void fun(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 10 "../evflagExt.st"
	seq_test_init(2);
# line 11 "../evflagExt.st"
	seq_efClear(seqg_env, e);
}

/****** Code for state "testExt" in state set "test" ******/

/* Entry function for state "testExt" in state set "test" */
static void seqg_entry_test_0_testExt(SS_ID seqg_env)
{
# line 17 "../evflagExt.st"
	extfun(ssId);
}

/* Event function for state "testExt" in state set "test" */
static seqBool seqg_event_test_0_testExt(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 19 "../evflagExt.st"
	if (seq_efTestAndClear(seqg_env, e))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 22 "../evflagExt.st"
	if (seq_delay(seqg_env, 0.2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "testExt" in state set "test" */
static void seqg_action_test_0_testExt(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 20 "../evflagExt.st"
			testPass("got the event");
		}
		return;
	case 1:
		{
# line 23 "../evflagExt.st"
			testFail("timeout waiting for event");
		}
		return;
	}
}

/****** Code for state "testInt" in state set "test" ******/

/* Entry function for state "testInt" in state set "test" */
static void seqg_entry_test_0_testInt(SS_ID seqg_env)
{
# line 28 "../evflagExt.st"
	fun(seqg_env);
}

/* Event function for state "testInt" in state set "test" */
static seqBool seqg_event_test_0_testInt(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 30 "../evflagExt.st"
	if (seq_efTestAndClear(seqg_env, e))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 33 "../evflagExt.st"
	if (seq_delay(seqg_env, 0.2))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "testInt" in state set "test" */
static void seqg_action_test_0_testInt(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 31 "../evflagExt.st"
			testPass("got the event");
		}
		return;
	case 1:
		{
# line 34 "../evflagExt.st"
			testFail("timeout waiting for event");
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 40 "../evflagExt.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "test" */
static const seqMask seqg_mask_test_0_testExt[] = {
	0x00000002,
};
static const seqMask seqg_mask_test_0_testInt[] = {
	0x00000002,
};

/* State table for state set "test" */
static seqState seqg_states_test[] = {
	{
	/* state name */        "testExt",
	/* action function */   seqg_action_test_0_testExt,
	/* event function */    seqg_event_test_0_testExt,
	/* entry function */    seqg_entry_test_0_testExt,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_testExt,
	/* state options */     (0)
	},
	{
	/* state name */        "testInt",
	/* action function */   seqg_action_test_0_testInt,
	/* event function */    seqg_event_test_0_testInt,
	/* entry function */    seqg_entry_test_0_testInt,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_testInt,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "test",
	/* states */            seqg_states_test,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram evflagExtTest = {
	/* magic number */      2002005,
	/* program name */      "evflagExtTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  1,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};
# line 43 "../evflagExt.st"

static void extfun(SS_ID ssid)
{
    seq_efSet(ssid, e);
}


#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 50 "../evflagExt.st"
static void fun(SS_ID seqg_env)
{
# line 52 "../evflagExt.st"
	seq_efSet(seqg_env, e);
}
#undef seqg_var

#define PROG_NAME evflagExtTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void evflagExtTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&evflagExtTest);
}
epicsExportRegistrar(evflagExtTestRegistrar);
