/* C code for program evflagTest, generated by snc from ../evflag.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 17 "../evflag.st"
#include "../testSupport.h"
# line 21 "../evflag.st"
static const EF_ID ef_named = 1;
# line 21 "../evflag.st"
static const EF_ID ef_anonymous = 2;

/* Variable declarations */
struct seqg_vars {
# line 23 "../evflag.st"
	double anonymous;
	struct seqg_vars_read {
# line 34 "../evflag.st"
		double named;
	} seqg_vars_read;
	struct seqg_vars_write {
# line 51 "../evflag.st"
		double named;
# line 53 "../evflag.st"
		int n;
	} seqg_vars_write;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 51 "../evflag.st"
	static double seqg_initvar_named = 1.0;
	memcpy(&seqg_var->seqg_vars_write.named, &seqg_initvar_named, sizeof(seqg_initvar_named));
	}
	{
# line 53 "../evflag.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_var->seqg_vars_write.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 29 "../evflag.st"
	seq_test_init(44);
# line 30 "../evflag.st"
	seq_efClear(seqg_env, ef_named);
}

/****** Code for state "wait" in state set "read" ******/

/* Event function for state "wait" in state set "read" */
static seqBool seqg_event_read_0_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 39 "../evflag.st"
	if (seq_efTestAndClear(seqg_env, ef_named))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "read" */
static void seqg_action_read_0_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 40 "../evflag.st"
			seqg_var->anonymous = seqg_var->seqg_vars_read.named;
# line 41 "../evflag.st"
			seq_pvPutTmo(seqg_env, 0/*anonymous*/, DEFAULT, DEFAULT_TIMEOUT);
# line 42 "../evflag.st"
			testDiag("read: pvPut(anonymous=%.1f)", seqg_var->anonymous);
# line 43 "../evflag.st"
			epicsThreadSleep(0.1);
# line 45 "../evflag.st"
			testOk(seqg_var->seqg_vars_read.named == seqg_var->anonymous, "read: named=%.1f==%.1f=anonymous", seqg_var->seqg_vars_read.named, seqg_var->anonymous);
		}
		return;
	}
}

/****** Code for state "send" in state set "write" ******/

/* Event function for state "send" in state set "write" */
static seqBool seqg_event_write_1_send(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 55 "../evflag.st"
	if (seqg_var->seqg_vars_write.n > 10)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 57 "../evflag.st"
	if (seq_delay(seqg_env, 0.01))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "send" in state set "write" */
static void seqg_action_write_1_send(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 58 "../evflag.st"
			seqg_var->seqg_vars_write.named = seqg_var->seqg_vars_write.n;
# line 59 "../evflag.st"
			seq_pvPutTmo(seqg_env, 2/*named*/, DEFAULT, DEFAULT_TIMEOUT);
# line 60 "../evflag.st"
			testDiag("write: pvPut(named=%.1f)", seqg_var->seqg_vars_write.named);
# line 61 "../evflag.st"
			seqg_var->anonymous = seqg_var->seqg_vars_write.named;
		}
		return;
	}
}

/****** Code for state "recv" in state set "write" ******/

/* Event function for state "recv" in state set "write" */
static seqBool seqg_event_write_1_recv(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 65 "../evflag.st"
	if (seq_efTestAndClear(seqg_env, ef_anonymous))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recv" in state set "write" */
static void seqg_action_write_1_recv(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 66 "../evflag.st"
			testOk(seqg_var->seqg_vars_write.named == seqg_var->anonymous, "write: named=%.1f==%.1f=anonymous", seqg_var->seqg_vars_write.named, seqg_var->anonymous);
# line 67 "../evflag.st"
			epicsThreadSleep(0.1);
# line 68 "../evflag.st"
			testOk(seqg_var->seqg_vars_write.named == seqg_var->anonymous, "write: named=%.1f==%.1f=anonymous", seqg_var->seqg_vars_write.named, seqg_var->anonymous);
# line 69 "../evflag.st"
			seq_pvGetTmo(seqg_env, 0/*anonymous*/, DEFAULT, DEFAULT_TIMEOUT);
# line 70 "../evflag.st"
			testOk(seqg_var->seqg_vars_write.named == seqg_var->anonymous, "write: named=%.1f==%.1f=anonymous", seqg_var->seqg_vars_write.named, seqg_var->anonymous);
# line 71 "../evflag.st"
			seqg_var->seqg_vars_write.n++;
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 77 "../evflag.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, anonymous), "anonymous", P_DOUBLE, 1, 3, 2, 1, 0, 0},
	{"evflag", offsetof(struct seqg_vars, seqg_vars_read.named), "named", P_DOUBLE, 1, 4, 1, 1, 0, 0},
	{"evflag", offsetof(struct seqg_vars, seqg_vars_write.named), "named", P_DOUBLE, 1, 5, 0, 0, 0, 0},
};

/* Event masks for state set "read" */
static const seqMask seqg_mask_read_0_wait[] = {
	0x00000002,
};

/* State table for state set "read" */
static seqState seqg_states_read[] = {
	{
	/* state name */        "wait",
	/* action function */   seqg_action_read_0_wait,
	/* event function */    seqg_event_read_0_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_0_wait,
	/* state options */     (0)
	},
};

/* Event masks for state set "write" */
static const seqMask seqg_mask_write_1_send[] = {
	0x00000000,
};
static const seqMask seqg_mask_write_1_recv[] = {
	0x00000004,
};

/* State table for state set "write" */
static seqState seqg_states_write[] = {
	{
	/* state name */        "send",
	/* action function */   seqg_action_write_1_send,
	/* event function */    seqg_event_write_1_send,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_write_1_send,
	/* state options */     (0)
	},
	{
	/* state name */        "recv",
	/* action function */   seqg_action_write_1_recv,
	/* event function */    seqg_event_write_1_recv,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_write_1_recv,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "read",
	/* states */            seqg_states_read,
	/* number of states */  1
	},

	{
	/* state set name */    "write",
	/* states */            seqg_states_write,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram evflagTest = {
	/* magic number */      2002005,
	/* program name */      "evflagTest",
	/* channels */          seqg_chans,
	/* num. channels */     3,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  2,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME evflagTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void evflagTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&evflagTest);
}
epicsExportRegistrar(evflagTestRegistrar);
