/* C code for program functionInStructTest, generated by snc from ../functionInStruct.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../functionInStruct.st"
#include "../testSupport.h"
# line 7 "../functionInStruct.st"
#include <stdlib.h>

struct mystruct {
# line 10 "../functionInStruct.st"
	double val;
# line 11 "../functionInStruct.st"
	int *phi;
# line 12 "../functionInStruct.st"
	int *plo;
# line 13 "../functionInStruct.st"
	void (*cfun)(struct mystruct *ps);   /* without implicit parameters */
# line 14 "../functionInStruct.st"
	void (*fun)(SS_ID seqg_env, struct mystruct *ps);
# line 15 "../functionInStruct.st"
	struct mystruct *children[3];
};
# line 21 "../functionInStruct.st"

void mycfun(struct mystruct *p);


/* Variable declarations */
# line 18 "../functionInStruct.st"
static	int hilo;
# line 19 "../functionInStruct.st"
static	struct mystruct s;


/* Function declarations */
# line 48 "../functionInStruct.st"
static void myfun(SS_ID seqg_env, struct mystruct *p);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 18 "../functionInStruct.st"
	static int seqg_initvar_hilo = 33;
	memcpy(&hilo, &seqg_initvar_hilo, sizeof(seqg_initvar_hilo));
	}
	{
# line 19 "../functionInStruct.st"
	static struct mystruct seqg_initvar_s = {42.23, &hilo, &hilo, mycfun, myfun, {&s, &s, &s}};
	memcpy(&s, &seqg_initvar_s, sizeof(seqg_initvar_s));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 26 "../functionInStruct.st"
	struct mystruct *ps = *(&s.children[0] + 1);
# line 28 "../functionInStruct.st"
	seq_test_init(15);
# line 30 "../functionInStruct.st"
	myfun(seqg_env, ps);
# line 31 "../functionInStruct.st"
	ps->fun(seqg_env, ps);
# line 32 "../functionInStruct.st"
	s.fun(seqg_env, ps);
# line 33 "../functionInStruct.st"
	if (s.cfun)
# line 34 "../functionInStruct.st"
		s.cfun(ps);
# line 35 "../functionInStruct.st"
	ps->children[1]->fun(seqg_env, ps->children[0]);
}

/****** Code for state "trivial" in state set "trivial" ******/

/* Event function for state "trivial" in state set "trivial" */
static seqBool seqg_event_trivial_0_trivial(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "trivial" in state set "trivial" */
static void seqg_action_trivial_0_trivial(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 45 "../functionInStruct.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "trivial" */
static const seqMask seqg_mask_trivial_0_trivial[] = {
	0x00000000,
};

/* State table for state set "trivial" */
static seqState seqg_states_trivial[] = {
	{
	/* state name */        "trivial",
	/* action function */   seqg_action_trivial_0_trivial,
	/* event function */    seqg_event_trivial_0_trivial,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_trivial_0_trivial,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "trivial",
	/* states */            seqg_states_trivial,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram functionInStructTest = {
	/* magic number */      2002005,
	/* program name */      "functionInStructTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 48 "../functionInStruct.st"
static void myfun(SS_ID seqg_env, struct mystruct *p)
{
# line 49 "../functionInStruct.st"
	testDiag("myfun says: val=%f, *phi = %d, *plo=%d\n", p->val, *p->phi, *p->plo);
# line 50 "../functionInStruct.st"
	testOk1(p->val == s.val);
# line 51 "../functionInStruct.st"
	testOk1(*p->phi == hilo);
# line 52 "../functionInStruct.st"
	testOk1(*p->plo == hilo);
}
#undef seqg_var
# line 55 "../functionInStruct.st"

void mycfun(struct mystruct *p) {
    testDiag("mycfun says: val=%f, *phi = %d, *plo=%d\n", p->val, *p->phi, *p->plo);
    testOk1(p->val==s.val);
    testOk1(*p->phi==hilo);
    testOk1(*p->plo==hilo);
}


#define PROG_NAME functionInStructTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void functionInStructTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&functionInStructTest);
}
epicsExportRegistrar(functionInStructTestRegistrar);
