/* C code for program indirectCallTest, generated by snc from ../indirectCall.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 11 "../indirectCall.st"
#include "../testSupport.h"
# line 13 "../indirectCall.st"

typedef int fun_t(int);
struct s {
    fun_t *f;
};
int id(int x) {
    return x;
}
int inc(int x) {
    return x + 1;
}


/* Variable declarations */
struct seqg_vars {
# line 26 "../indirectCall.st"
	struct s gx;
# line 27 "../indirectCall.st"
	struct s *p;
	struct seqg_vars_test {
# line 34 "../indirectCall.st"
		struct s ssx;
		struct {
# line 37 "../indirectCall.st"
			struct s stx;
		} seqg_vars_test;
	} seqg_vars_test;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 30 "../indirectCall.st"
	seq_test_init(3 * 8);
}

/****** Code for state "test" in state set "test" ******/

/* Event function for state "test" in state set "test" */
static seqBool seqg_event_test_0_test(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "test" in state set "test" */
static void seqg_action_test_0_test(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 40 "../indirectCall.st"
			seqg_var->p = &seqg_var->gx;
# line 41 "../indirectCall.st"
			seqg_var->gx.f = id;
# line 42 "../indirectCall.st"
			testOk1(42 == seqg_var->p->f(42));
# line 43 "../indirectCall.st"
			testOk1(42 == (*seqg_var->p->f)(42));
# line 44 "../indirectCall.st"
			testOk1(42 == seqg_var->gx.f(42));
# line 45 "../indirectCall.st"
			testOk1(42 == (*seqg_var->gx.f)(42));
# line 46 "../indirectCall.st"
			seqg_var->gx.f = inc;
# line 47 "../indirectCall.st"
			testOk1(1 == seqg_var->p->f(0));
# line 48 "../indirectCall.st"
			testOk1(1 == (*seqg_var->p->f)(0));
# line 49 "../indirectCall.st"
			testOk1(1 == seqg_var->gx.f(0));
# line 50 "../indirectCall.st"
			testOk1(1 == (*seqg_var->gx.f)(0));
# line 52 "../indirectCall.st"
			seqg_var->p = &seqg_var->seqg_vars_test.ssx;
# line 53 "../indirectCall.st"
			seqg_var->seqg_vars_test.ssx.f = id;
# line 54 "../indirectCall.st"
			testOk1(42 == seqg_var->p->f(42));
# line 55 "../indirectCall.st"
			testOk1(42 == (*seqg_var->p->f)(42));
# line 56 "../indirectCall.st"
			testOk1(42 == seqg_var->seqg_vars_test.ssx.f(42));
# line 57 "../indirectCall.st"
			testOk1(42 == (*seqg_var->seqg_vars_test.ssx.f)(42));
# line 58 "../indirectCall.st"
			seqg_var->seqg_vars_test.ssx.f = inc;
# line 59 "../indirectCall.st"
			testOk1(1 == seqg_var->p->f(0));
# line 60 "../indirectCall.st"
			testOk1(1 == (*seqg_var->p->f)(0));
# line 61 "../indirectCall.st"
			testOk1(1 == seqg_var->seqg_vars_test.ssx.f(0));
# line 62 "../indirectCall.st"
			testOk1(1 == (*seqg_var->seqg_vars_test.ssx.f)(0));
# line 64 "../indirectCall.st"
			seqg_var->p = &seqg_var->seqg_vars_test.seqg_vars_test.stx;
# line 65 "../indirectCall.st"
			seqg_var->seqg_vars_test.seqg_vars_test.stx.f = id;
# line 66 "../indirectCall.st"
			testOk1(42 == seqg_var->p->f(42));
# line 67 "../indirectCall.st"
			testOk1(42 == (*seqg_var->p->f)(42));
# line 68 "../indirectCall.st"
			testOk1(42 == seqg_var->seqg_vars_test.seqg_vars_test.stx.f(42));
# line 69 "../indirectCall.st"
			testOk1(42 == (*seqg_var->seqg_vars_test.seqg_vars_test.stx.f)(42));
# line 70 "../indirectCall.st"
			seqg_var->seqg_vars_test.seqg_vars_test.stx.f = inc;
# line 71 "../indirectCall.st"
			testOk1(1 == seqg_var->p->f(0));
# line 72 "../indirectCall.st"
			testOk1(1 == (*seqg_var->p->f)(0));
# line 73 "../indirectCall.st"
			testOk1(1 == seqg_var->seqg_vars_test.seqg_vars_test.stx.f(0));
# line 74 "../indirectCall.st"
			testOk1(1 == (*seqg_var->seqg_vars_test.seqg_vars_test.stx.f)(0));
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 81 "../indirectCall.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "test" */
static const seqMask seqg_mask_test_0_test[] = {
	0x00000000,
};

/* State table for state set "test" */
static seqState seqg_states_test[] = {
	{
	/* state name */        "test",
	/* action function */   seqg_action_test_0_test,
	/* event function */    seqg_event_test_0_test,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_test,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "test",
	/* states */            seqg_states_test,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram indirectCallTest = {
	/* magic number */      2002005,
	/* program name */      "indirectCallTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME indirectCallTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void indirectCallTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&indirectCallTest);
}
epicsExportRegistrar(indirectCallTestRegistrar);
