/* C code for program monitorEvflagTest, generated by snc from ../monitorEvflag.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 5 "../monitorEvflag.st"
#include "../testSupport.h"
# line 6 "../monitorEvflag.st"
#include <stdio.h>
# line 19 "../monitorEvflag.st"
static const EF_ID actualChanged = 1;

/* Variable declarations */
struct seqg_vars {
# line 12 "../monitorEvflag.st"
	int requested;
# line 15 "../monitorEvflag.st"
	int actual;
	struct seqg_vars_monitorEvflagTest {
# line 27 "../monitorEvflag.st"
		int cycleCount;
# line 28 "../monitorEvflag.st"
		int error;
	} seqg_vars_monitorEvflagTest;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 27 "../monitorEvflag.st"
	static int seqg_initvar_cycleCount = 1;
	memcpy(&seqg_var->seqg_vars_monitorEvflagTest.cycleCount, &seqg_initvar_cycleCount, sizeof(seqg_initvar_cycleCount));
	}
	{
# line 28 "../monitorEvflag.st"
	static int seqg_initvar_error = 0;
	memcpy(&seqg_var->seqg_vars_monitorEvflagTest.error, &seqg_initvar_error, sizeof(seqg_initvar_error));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 23 "../monitorEvflag.st"
	seq_test_init(1);
}

/****** Code for state "init" in state set "monitorEvflagTest" ******/

/* Event function for state "init" in state set "monitorEvflagTest" */
static seqBool seqg_event_monitorEvflagTest_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 30 "../monitorEvflag.st"
	if (seq_delay(seqg_env, 1.0))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "monitorEvflagTest" */
static void seqg_action_monitorEvflagTest_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 31 "../monitorEvflag.st"
			seq_efClear(seqg_env, actualChanged);
		}
		return;
	}
}

/****** Code for state "makeRequest" in state set "monitorEvflagTest" ******/

/* Event function for state "makeRequest" in state set "monitorEvflagTest" */
static seqBool seqg_event_monitorEvflagTest_0_makeRequest(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 35 "../monitorEvflag.st"
	if (seqg_var->seqg_vars_monitorEvflagTest.error)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 37 "../monitorEvflag.st"
	if (seqg_var->seqg_vars_monitorEvflagTest.cycleCount > (20 * 500))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 40 "../monitorEvflag.st"
	if (seqg_var->seqg_vars_monitorEvflagTest.cycleCount <= (20 * 500))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "makeRequest" in state set "monitorEvflagTest" */
static void seqg_action_monitorEvflagTest_0_makeRequest(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 38 "../monitorEvflag.st"
			testPass("no error in %d cycles", (20 * 500));
		}
		return;
	case 2:
		{
# line 41 "../monitorEvflag.st"
			seqg_var->requested = seqg_var->seqg_vars_monitorEvflagTest.cycleCount;
# line 42 "../monitorEvflag.st"
			seq_pvPutTmo(seqg_env, 0/*requested*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "waitForActualToEqualRequested" in state set "monitorEvflagTest" ******/

/* Event function for state "waitForActualToEqualRequested" in state set "monitorEvflagTest" */
static seqBool seqg_event_monitorEvflagTest_0_waitForActualToEqualRequested(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 46 "../monitorEvflag.st"
	if (seq_efTestAndClear(seqg_env, actualChanged) && seqg_var->actual == seqg_var->requested)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 55 "../monitorEvflag.st"
	if (seq_delay(seqg_env, 1.0))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitForActualToEqualRequested" in state set "monitorEvflagTest" */
static void seqg_action_monitorEvflagTest_0_waitForActualToEqualRequested(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 47 "../monitorEvflag.st"
			if (seqg_var->actual != seqg_var->requested)
			{
# line 48 "../monitorEvflag.st"
				testFail("requested(%d)!=actual(%d)", seqg_var->requested, seqg_var->actual);
# line 49 "../monitorEvflag.st"
				seqg_var->seqg_vars_monitorEvflagTest.error = TRUE;
			}
			else
# line 50 "../monitorEvflag.st"
				if (seqg_var->seqg_vars_monitorEvflagTest.cycleCount % 500 == 0)
				{
# line 51 "../monitorEvflag.st"
					testDiag("passed %d cycles", seqg_var->seqg_vars_monitorEvflagTest.cycleCount);
				}
# line 53 "../monitorEvflag.st"
			seqg_var->seqg_vars_monitorEvflagTest.cycleCount++;
		}
		return;
	case 1:
		{
# line 57 "../monitorEvflag.st"
			testFail("timeout in cycle %d/%d (requested=%d, actual=%d)", seqg_var->seqg_vars_monitorEvflagTest.cycleCount + 1, (20 * 500), seqg_var->requested, seqg_var->actual);
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 63 "../monitorEvflag.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"requested", offsetof(struct seqg_vars, requested), "requested", P_INT, 1, 2, 0, 0, 0, 0},
	{"actual", offsetof(struct seqg_vars, actual), "actual", P_INT, 1, 3, 1, 1, 0, 0},
};

/* Event masks for state set "monitorEvflagTest" */
static const seqMask seqg_mask_monitorEvflagTest_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_monitorEvflagTest_0_makeRequest[] = {
	0x00000000,
};
static const seqMask seqg_mask_monitorEvflagTest_0_waitForActualToEqualRequested[] = {
	0x0000000e,
};

/* State table for state set "monitorEvflagTest" */
static seqState seqg_states_monitorEvflagTest[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_monitorEvflagTest_0_init,
	/* event function */    seqg_event_monitorEvflagTest_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_monitorEvflagTest_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "makeRequest",
	/* action function */   seqg_action_monitorEvflagTest_0_makeRequest,
	/* event function */    seqg_event_monitorEvflagTest_0_makeRequest,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_monitorEvflagTest_0_makeRequest,
	/* state options */     (0)
	},
	{
	/* state name */        "waitForActualToEqualRequested",
	/* action function */   seqg_action_monitorEvflagTest_0_waitForActualToEqualRequested,
	/* event function */    seqg_event_monitorEvflagTest_0_waitForActualToEqualRequested,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_monitorEvflagTest_0_waitForActualToEqualRequested,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "monitorEvflagTest",
	/* states */            seqg_states_monitorEvflagTest,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram monitorEvflagTest = {
	/* magic number */      2002005,
	/* program name */      "monitorEvflagTest",
	/* channels */          seqg_chans,
	/* num. channels */     2,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  1,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME monitorEvflagTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void monitorEvflagTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&monitorEvflagTest);
}
epicsExportRegistrar(monitorEvflagTestRegistrar);
