/* C code for program opttVarTest, generated by snc from ../opttVar.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 7 "../opttVar.st"
#include "../testSupport.h"

/* Variable declarations */
struct seqg_vars {
# line 20 "../opttVar.st"
	char msg[60];
	struct seqg_vars_low_high {
		struct {
# line 31 "../opttVar.st"
			double d;
		} seqg_vars_low;
		struct {
# line 56 "../opttVar.st"
			int v;
		} seqg_vars_high;
	} seqg_vars_low_high;
	struct seqg_vars_check {
# line 77 "../opttVar.st"
		char *expected[20];
# line 99 "../opttVar.st"
		char **xp;
# line 100 "../opttVar.st"
		int repeat;
	} seqg_vars_check;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 77 "../opttVar.st"
	static char *seqg_initvar_expected[20] = {"Entered low, initialize delay to 0.4 sec.", "low, delay timeout, reenter low", "low, waiting 0.6 secs to iterate", "low, delay timeout, reenter low", "low, waiting 0.8 secs to iterate", "low, delay timeout, reenter low", "low, waiting 1 secs to iterate", "low, delay timeout, reenter low", "low, waiting 1.2 secs to iterate", "low, delay = 1.2, now changing to high", "low, print this on exit of low", "Entered high", "high, delay 0.3 timeout, decr v and re-enter high", "v = 2", "high, delay 0.3 timeout, decr v and re-enter high", "v = 1", "high, delay 0.3 timeout, decr v and re-enter high", "v = 0", "changing to low", 0};
	memcpy(&seqg_var->seqg_vars_check.expected, &seqg_initvar_expected, sizeof(seqg_initvar_expected));
	}
	{
# line 100 "../opttVar.st"
	static int seqg_initvar_repeat = 1;
	memcpy(&seqg_var->seqg_vars_check.repeat, &seqg_initvar_repeat, sizeof(seqg_initvar_repeat));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 26 "../opttVar.st"
	seq_test_init(40);
}

/****** Code for state "low" in state set "low_high" ******/

/* Entry function for state "low" in state set "low_high" */
static void seqg_entry_low_high_0_low(SS_ID seqg_env)
{
# line 34 "../opttVar.st"
	seqg_var->seqg_vars_low_high.seqg_vars_low.d = 0.4;
# line 35 "../opttVar.st"
	sprintf(seqg_var->msg, "Entered low, initialize delay to %g sec.", seqg_var->seqg_vars_low_high.seqg_vars_low.d);
# line 36 "../opttVar.st"
	seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Exit function for state "low" in state set "low_high" */
static void seqg_exit_low_high_0_low(SS_ID seqg_env)
{
# line 50 "../opttVar.st"
	sprintf(seqg_var->msg, "low, print this on exit of low");
# line 51 "../opttVar.st"
	seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "low" in state set "low_high" */
static seqBool seqg_event_low_high_0_low(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 38 "../opttVar.st"
	if (seqg_var->seqg_vars_low_high.seqg_vars_low.d > 1.1)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 42 "../opttVar.st"
	if (seq_delay(seqg_env, seqg_var->seqg_vars_low_high.seqg_vars_low.d))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "low" in state set "low_high" */
static void seqg_action_low_high_0_low(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 39 "../opttVar.st"
			sprintf(seqg_var->msg, "low, delay = %g, now changing to high", seqg_var->seqg_vars_low_high.seqg_vars_low.d);
# line 40 "../opttVar.st"
			seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 43 "../opttVar.st"
			sprintf(seqg_var->msg, "low, delay timeout, reenter low");
# line 44 "../opttVar.st"
			seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 45 "../opttVar.st"
			seqg_var->seqg_vars_low_high.seqg_vars_low.d += 0.2;
# line 46 "../opttVar.st"
			sprintf(seqg_var->msg, "low, waiting %g secs to iterate", seqg_var->seqg_vars_low_high.seqg_vars_low.d);
# line 47 "../opttVar.st"
			seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "high" in state set "low_high" ******/

/* Entry function for state "high" in state set "low_high" */
static void seqg_entry_low_high_0_high(SS_ID seqg_env)
{
# line 58 "../opttVar.st"
	seqg_var->seqg_vars_low_high.seqg_vars_high.v = 3;
# line 59 "../opttVar.st"
	sprintf(seqg_var->msg, "Entered high");
# line 60 "../opttVar.st"
	seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "high" in state set "low_high" */
static seqBool seqg_event_low_high_0_high(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 62 "../opttVar.st"
	if (seqg_var->seqg_vars_low_high.seqg_vars_high.v == 0)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 66 "../opttVar.st"
	if (seq_delay(seqg_env, 0.3))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "high" in state set "low_high" */
static void seqg_action_low_high_0_high(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 63 "../opttVar.st"
			sprintf(seqg_var->msg, "changing to low");
# line 64 "../opttVar.st"
			seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 67 "../opttVar.st"
			sprintf(seqg_var->msg, "high, delay 0.3 timeout, decr v and re-enter high");
# line 68 "../opttVar.st"
			seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
# line 69 "../opttVar.st"
			seqg_var->seqg_vars_low_high.seqg_vars_high.v -= 1;
# line 70 "../opttVar.st"
			sprintf(seqg_var->msg, "v = %d", seqg_var->seqg_vars_low_high.seqg_vars_high.v);
# line 71 "../opttVar.st"
			seq_pvPutTmo(seqg_env, 0/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "check_msg" in state set "check" ******/

/* Entry function for state "check_msg" in state set "check" */
static void seqg_entry_check_1_check_msg(SS_ID seqg_env)
{
# line 103 "../opttVar.st"
	seqg_var->seqg_vars_check.xp = seqg_var->seqg_vars_check.expected;
# line 104 "../opttVar.st"
	testPass("start 1st round...");
}

/* Event function for state "check_msg" in state set "check" */
static seqBool seqg_event_check_1_check_msg(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 106 "../opttVar.st"
	if (seqg_var->seqg_vars_check.repeat && !*seqg_var->seqg_vars_check.xp)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 111 "../opttVar.st"
	if (!*seqg_var->seqg_vars_check.xp)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 113 "../opttVar.st"
	if (seq_pvGetQ(seqg_env, 0/*msg*/))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "check_msg" in state set "check" */
static void seqg_action_check_1_check_msg(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 107 "../opttVar.st"
			seqg_var->seqg_vars_check.xp = seqg_var->seqg_vars_check.expected;
# line 108 "../opttVar.st"
			testPass("one more time...");
# line 109 "../opttVar.st"
			seqg_var->seqg_vars_check.repeat = 0;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 114 "../opttVar.st"
			testOk(strcmp(*seqg_var->seqg_vars_check.xp, seqg_var->msg) == 0, "msg=%s", seqg_var->msg);
# line 115 "../opttVar.st"
			seqg_var->seqg_vars_check.xp++;
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 121 "../opttVar.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, msg), "msg", P_CHAR, 60, 1, 0, 1, 40, 0},
};

/* Event masks for state set "low_high" */
static const seqMask seqg_mask_low_high_0_low[] = {
	0x00000000,
};
static const seqMask seqg_mask_low_high_0_high[] = {
	0x00000000,
};

/* State table for state set "low_high" */
static seqState seqg_states_low_high[] = {
	{
	/* state name */        "low",
	/* action function */   seqg_action_low_high_0_low,
	/* event function */    seqg_event_low_high_0_low,
	/* entry function */    seqg_entry_low_high_0_low,
	/* exit function */     seqg_exit_low_high_0_low,
	/* event mask array */  seqg_mask_low_high_0_low,
	/* state options */     (0 | OPT_NORESETTIMERS)
	},
	{
	/* state name */        "high",
	/* action function */   seqg_action_low_high_0_high,
	/* event function */    seqg_event_low_high_0_high,
	/* entry function */    seqg_entry_low_high_0_high,
	/* exit function */     0,
	/* event mask array */  seqg_mask_low_high_0_high,
	/* state options */     (0)
	},
};

/* Event masks for state set "check" */
static const seqMask seqg_mask_check_1_check_msg[] = {
	0x00000002,
};

/* State table for state set "check" */
static seqState seqg_states_check[] = {
	{
	/* state name */        "check_msg",
	/* action function */   seqg_action_check_1_check_msg,
	/* event function */    seqg_event_check_1_check_msg,
	/* entry function */    seqg_entry_check_1_check_msg,
	/* exit function */     0,
	/* event mask array */  seqg_mask_check_1_check_msg,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "low_high",
	/* states */            seqg_states_low_high,
	/* number of states */  2
	},

	{
	/* state set name */    "check",
	/* states */            seqg_states_check,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram opttVarTest = {
	/* magic number */      2002005,
	/* program name */      "opttVarTest",
	/* channels */          seqg_chans,
	/* num. channels */     1,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       1
};

#define PROG_NAME opttVarTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void opttVarTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&opttVarTest);
}
epicsExportRegistrar(opttVarTestRegistrar);
