/* C code for program pvGetCancelTest, generated by snc from ../pvGetCancel.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 11 "../pvGetCancel.st"
#include "../testSupport.h"

/* Variable declarations */
struct seqg_vars_pvGetCancel {
# line 21 "../pvGetCancel.st"
	int x[2];
# line 22 "../pvGetCancel.st"
	int y[2];
# line 25 "../pvGetCancel.st"
	pvStat status;
# line 26 "../pvGetCancel.st"
	int n;
} seqg_vars_pvGetCancel;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 22 "../pvGetCancel.st"
	static int seqg_initvar_y[2] = {1, 2};
	memcpy(&seqg_vars_pvGetCancel.y, &seqg_initvar_y, sizeof(seqg_initvar_y));
	}
	{
# line 26 "../pvGetCancel.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_vars_pvGetCancel.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 16 "../pvGetCancel.st"
	seq_test_init(8 * 50);
# line 17 "../pvGetCancel.st"
	testDiag("start");
}

/****** Code for state "done" in state set "pvGetCancel" ******/

/* Event function for state "done" in state set "pvGetCancel" */
static seqBool seqg_event_pvGetCancel_0_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 29 "../pvGetCancel.st"
	if (seqg_vars_pvGetCancel.n < 50)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 32 "../pvGetCancel.st"
	if (seq_delay(seqg_env, 0.2))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "pvGetCancel" */
static void seqg_action_pvGetCancel_0_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 30 "../pvGetCancel.st"
			seqg_vars_pvGetCancel.n++;
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "test" in state set "pvGetCancel" ******/

/* Entry function for state "test" in state set "pvGetCancel" */
static void seqg_entry_pvGetCancel_0_test(SS_ID seqg_env)
{
# line 37 "../pvGetCancel.st"
	testOk1(seq_pvGetTmo(seqg_env, 0/*x*/ + (CH_ID)(0), ASYNC, DEFAULT_TIMEOUT) == pvStatOK);
# line 38 "../pvGetCancel.st"
	testOk1(seq_pvGetTmo(seqg_env, 0/*x*/ + (CH_ID)(1), ASYNC, DEFAULT_TIMEOUT) == pvStatOK);
# line 39 "../pvGetCancel.st"
	seq_pvArrayGetCancel(seqg_env, 0/*x*/, 2);
# line 40 "../pvGetCancel.st"
	seqg_vars_pvGetCancel.x[0] = seqg_vars_pvGetCancel.x[1] = 0;
# line 41 "../pvGetCancel.st"
	seqg_vars_pvGetCancel.y[0] = seqg_vars_pvGetCancel.y[1] = 1;
# line 42 "../pvGetCancel.st"
	testOk1(seq_pvPutTmo(seqg_env, 2/*y*/ + (CH_ID)(0), SYNC, DEFAULT_TIMEOUT) == pvStatOK);
# line 43 "../pvGetCancel.st"
	testOk1(seq_pvPutTmo(seqg_env, 2/*y*/ + (CH_ID)(1), SYNC, DEFAULT_TIMEOUT) == pvStatOK);
# line 44 "../pvGetCancel.st"
	testOk1(seq_pvGetTmo(seqg_env, 0/*x*/ + (CH_ID)(0), ASYNC, DEFAULT_TIMEOUT) == pvStatOK);
# line 45 "../pvGetCancel.st"
	testOk1(seq_pvGetTmo(seqg_env, 0/*x*/ + (CH_ID)(1), ASYNC, DEFAULT_TIMEOUT) == pvStatOK);
}

/* Event function for state "test" in state set "pvGetCancel" */
static seqBool seqg_event_pvGetCancel_0_test(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 47 "../pvGetCancel.st"
	if (seq_delay(seqg_env, 5.0))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 51 "../pvGetCancel.st"
	if (seq_pvArrayGetComplete(seqg_env, 0/*x*/, 2, FALSE, NULL))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "test" in state set "pvGetCancel" */
static void seqg_action_pvGetCancel_0_test(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 48 "../pvGetCancel.st"
			testFail("pvGet completion timeout");
# line 49 "../pvGetCancel.st"
			testSkip(1, "further tests aborted");
		}
		return;
	case 1:
		{
# line 52 "../pvGetCancel.st"
			testOk1(seqg_vars_pvGetCancel.x[0] == seqg_vars_pvGetCancel.y[0]);
# line 53 "../pvGetCancel.st"
			testOk1(seqg_vars_pvGetCancel.x[1] == seqg_vars_pvGetCancel.y[1]);
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 59 "../pvGetCancel.st"
	testDiag("exit");
# line 60 "../pvGetCancel.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"pvGetCancel1", (size_t)&seqg_vars_pvGetCancel.x[0], "x[0]", P_INT, 1, 1, 0, 0, 0, 0},
	{"pvGetCancel2", (size_t)&seqg_vars_pvGetCancel.x[1], "x[1]", P_INT, 1, 2, 0, 0, 0, 0},
	{"pvGetCancel1", (size_t)&seqg_vars_pvGetCancel.y[0], "y[0]", P_INT, 1, 3, 0, 0, 0, 0},
	{"pvGetCancel2", (size_t)&seqg_vars_pvGetCancel.y[1], "y[1]", P_INT, 1, 4, 0, 0, 0, 0},
};

/* Event masks for state set "pvGetCancel" */
static const seqMask seqg_mask_pvGetCancel_0_done[] = {
	0x00000000,
};
static const seqMask seqg_mask_pvGetCancel_0_test[] = {
	0x00000006,
};

/* State table for state set "pvGetCancel" */
static seqState seqg_states_pvGetCancel[] = {
	{
	/* state name */        "done",
	/* action function */   seqg_action_pvGetCancel_0_done,
	/* event function */    seqg_event_pvGetCancel_0_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvGetCancel_0_done,
	/* state options */     (0)
	},
	{
	/* state name */        "test",
	/* action function */   seqg_action_pvGetCancel_0_test,
	/* event function */    seqg_event_pvGetCancel_0_test,
	/* entry function */    seqg_entry_pvGetCancel_0_test,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvGetCancel_0_test,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "pvGetCancel",
	/* states */            seqg_states_pvGetCancel,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram pvGetCancelTest = {
	/* magic number */      2002005,
	/* program name */      "pvGetCancelTest",
	/* channels */          seqg_chans,
	/* num. channels */     4,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME pvGetCancelTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void pvGetCancelTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&pvGetCancelTest);
}
epicsExportRegistrar(pvGetCancelTestRegistrar);
