/* C code for program pvGetCompleteTest, generated by snc from ../pvGetComplete.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../pvGetComplete.st"
#include "../testSupport.h"

/* Variable declarations */
struct seqg_vars_pvGetComplete {
# line 19 "../pvGetComplete.st"
	int r[2];
# line 20 "../pvGetComplete.st"
	int w[2];
# line 23 "../pvGetComplete.st"
	int n;
} seqg_vars_pvGetComplete;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 23 "../pvGetComplete.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_vars_pvGetComplete.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 14 "../pvGetComplete.st"
	seq_test_init(1);
# line 15 "../pvGetComplete.st"
	testDiag("start");
}

/****** Code for state "count" in state set "pvGetComplete" ******/

/* Event function for state "count" in state set "pvGetComplete" */
static seqBool seqg_event_pvGetComplete_0_count(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 26 "../pvGetComplete.st"
	if (seqg_vars_pvGetComplete.n < 20000)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "count" in state set "pvGetComplete" */
static void seqg_action_pvGetComplete_0_count(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 27 "../pvGetComplete.st"
			seqg_vars_pvGetComplete.n++;
# line 28 "../pvGetComplete.st"
			if (seqg_vars_pvGetComplete.n % 1000 == 0)
			{
# line 29 "../pvGetComplete.st"
				testDiag("passed %d runs", seqg_vars_pvGetComplete.n);
			}
		}
		return;
	case 1:
		{
# line 33 "../pvGetComplete.st"
			testPass("%d pvGets completed in time and results agree with predictions", 2 * 20000);
		}
		return;
	}
}

/****** Code for state "test" in state set "pvGetComplete" ******/

/* Entry function for state "test" in state set "pvGetComplete" */
static void seqg_entry_pvGetComplete_0_test(SS_ID seqg_env)
{
# line 38 "../pvGetComplete.st"
	int i;
# line 39 "../pvGetComplete.st"
	seqg_vars_pvGetComplete.w[0] = seqg_vars_pvGetComplete.n;
# line 40 "../pvGetComplete.st"
	seqg_vars_pvGetComplete.w[1] = -seqg_vars_pvGetComplete.n;
# line 41 "../pvGetComplete.st"
	for (i = 0; i < 2; i++)
	{
# line 42 "../pvGetComplete.st"
		seqg_vars_pvGetComplete.r[i] = 0;
# line 43 "../pvGetComplete.st"
		seq_pvPutTmo(seqg_env, 2/*w*/ + (CH_ID)(i), SYNC, DEFAULT_TIMEOUT);
	}
# line 45 "../pvGetComplete.st"
	for (i = 0; i < 2; i++)
	{
# line 46 "../pvGetComplete.st"
		seq_pvGetTmo(seqg_env, 0/*r*/ + (CH_ID)(i), ASYNC, DEFAULT_TIMEOUT);
	}
}

/* Event function for state "test" in state set "pvGetComplete" */
static seqBool seqg_event_pvGetComplete_0_test(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 49 "../pvGetComplete.st"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 52 "../pvGetComplete.st"
	if (seq_pvGetComplete(seqg_env, 0/*r*/ + (CH_ID)(0)) && seq_pvGetComplete(seqg_env, 0/*r*/ + (CH_ID)(1)))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "test" in state set "pvGetComplete" */
static void seqg_action_pvGetComplete_0_test(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 50 "../pvGetComplete.st"
			testFail("pvGet completion timeout");
		}
		return;
	case 1:
		{
# line 53 "../pvGetComplete.st"
			int i;
# line 54 "../pvGetComplete.st"
			for (i = 0; i < 2; i++)
			{
# line 55 "../pvGetComplete.st"
				if (seqg_vars_pvGetComplete.r[i] != seqg_vars_pvGetComplete.w[i])
				{
# line 56 "../pvGetComplete.st"
					testFail("n=%d, i=%d, w=%d, r=%d", seqg_vars_pvGetComplete.n, i, seqg_vars_pvGetComplete.w[i], seqg_vars_pvGetComplete.r[i]);
					{*seqg_pnst = 2; return;}
				}
			}
		}
		return;
	}
}

/****** Code for state "fail" in state set "pvGetComplete" ******/

/* Event function for state "fail" in state set "pvGetComplete" */
static seqBool seqg_event_pvGetComplete_0_fail(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "fail" in state set "pvGetComplete" */
static void seqg_action_pvGetComplete_0_fail(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 69 "../pvGetComplete.st"
	testDiag("exit");
# line 70 "../pvGetComplete.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"pvGetComplete1", (size_t)&seqg_vars_pvGetComplete.r[0], "r[0]", P_INT, 1, 1, 0, 0, 0, 0},
	{"pvGetComplete2", (size_t)&seqg_vars_pvGetComplete.r[1], "r[1]", P_INT, 1, 2, 0, 0, 0, 0},
	{"pvGetComplete1", (size_t)&seqg_vars_pvGetComplete.w[0], "w[0]", P_INT, 1, 3, 0, 0, 0, 0},
	{"pvGetComplete2", (size_t)&seqg_vars_pvGetComplete.w[1], "w[1]", P_INT, 1, 4, 0, 0, 0, 0},
};

/* Event masks for state set "pvGetComplete" */
static const seqMask seqg_mask_pvGetComplete_0_count[] = {
	0x00000000,
};
static const seqMask seqg_mask_pvGetComplete_0_test[] = {
	0x00000006,
};
static const seqMask seqg_mask_pvGetComplete_0_fail[] = {
	0x00000000,
};

/* State table for state set "pvGetComplete" */
static seqState seqg_states_pvGetComplete[] = {
	{
	/* state name */        "count",
	/* action function */   seqg_action_pvGetComplete_0_count,
	/* event function */    seqg_event_pvGetComplete_0_count,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvGetComplete_0_count,
	/* state options */     (0)
	},
	{
	/* state name */        "test",
	/* action function */   seqg_action_pvGetComplete_0_test,
	/* event function */    seqg_event_pvGetComplete_0_test,
	/* entry function */    seqg_entry_pvGetComplete_0_test,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvGetComplete_0_test,
	/* state options */     (0)
	},
	{
	/* state name */        "fail",
	/* action function */   seqg_action_pvGetComplete_0_fail,
	/* event function */    seqg_event_pvGetComplete_0_fail,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvGetComplete_0_fail,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "pvGetComplete",
	/* states */            seqg_states_pvGetComplete,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram pvGetCompleteTest = {
	/* magic number */      2002005,
	/* program name */      "pvGetCompleteTest",
	/* channels */          seqg_chans,
	/* num. channels */     4,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME pvGetCompleteTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void pvGetCompleteTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&pvGetCompleteTest);
}
epicsExportRegistrar(pvGetCompleteTestRegistrar);
