/* C code for program pvGetTest, generated by snc from ../pvGet.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../pvGet.st"
#include "../testSupport.h"
# line 14 "../pvGet.st"
int shared = 0;
# line 15 "../pvGet.st"
epicsMutexId mutex;
# line 22 "../pvGet.st"
static const EF_ID ef_read_named = 1;
# line 22 "../pvGet.st"
static const EF_ID ef_read_anon = 2;
# line 22 "../pvGet.st"
static const EF_ID ef_read_named_sync = 3;
# line 22 "../pvGet.st"
static const EF_ID ef_read_anon_sync = 4;

/* Variable declarations */
struct seqg_vars {
# line 17 "../pvGet.st"
	int anon;
	struct seqg_vars_read_named {
# line 30 "../pvGet.st"
		int named;
# line 32 "../pvGet.st"
		int expected;
# line 33 "../pvGet.st"
		int n;
	} seqg_vars_read_named;
	struct seqg_vars_read_anon {
# line 72 "../pvGet.st"
		int expected;
# line 73 "../pvGet.st"
		int n;
	} seqg_vars_read_anon;
	struct seqg_vars_read_named_sync {
# line 112 "../pvGet.st"
		int named;
# line 114 "../pvGet.st"
		int expected;
# line 115 "../pvGet.st"
		int n;
	} seqg_vars_read_named_sync;
	struct seqg_vars_read_anon_sync {
# line 150 "../pvGet.st"
		int expected;
# line 151 "../pvGet.st"
		int n;
	} seqg_vars_read_anon_sync;
	struct seqg_vars_write {
# line 186 "../pvGet.st"
		int out;
	} seqg_vars_write;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 33 "../pvGet.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_var->seqg_vars_read_named.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
	{
# line 73 "../pvGet.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_var->seqg_vars_read_anon.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
	{
# line 115 "../pvGet.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_var->seqg_vars_read_named_sync.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
	{
# line 151 "../pvGet.st"
	static int seqg_initvar_n = 0;
	memcpy(&seqg_var->seqg_vars_read_anon_sync.n, &seqg_initvar_n, sizeof(seqg_initvar_n));
	}
	{
# line 186 "../pvGet.st"
	static int seqg_initvar_out = 0;
	memcpy(&seqg_var->seqg_vars_write.out, &seqg_initvar_out, sizeof(seqg_initvar_out));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 25 "../pvGet.st"
	seq_test_init(5 * 4 * 3);
# line 26 "../pvGet.st"
	mutex = epicsMutexMustCreate();
}

/****** Code for state "get" in state set "read_named" ******/

/* Event function for state "get" in state set "read_named" */
static seqBool seqg_event_read_named_0_get(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 36 "../pvGet.st"
	if (seqg_var->seqg_vars_read_named.n == 5)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 39 "../pvGet.st"
	if (seq_delay(seqg_env, 0.2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "get" in state set "read_named" */
static void seqg_action_read_named_0_get(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 37 "../pvGet.st"
			seq_efSet(seqg_env, ef_read_named);
		}
		return;
	case 1:
		{
# line 40 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 41 "../pvGet.st"
			seqg_var->seqg_vars_read_named.expected = shared;
# line 42 "../pvGet.st"
			seq_pvGetTmo(seqg_env, 1/*named*/, ASYNC, DEFAULT_TIMEOUT);
# line 43 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 44 "../pvGet.st"
			if (seq_pvGetComplete(seqg_env, 1/*named*/))
			{
# line 46 "../pvGet.st"
				testOk(seqg_var->seqg_vars_read_named.expected == seqg_var->seqg_vars_read_named.named, "immediate completion:      expected=%d==%d=named", seqg_var->seqg_vars_read_named.expected, seqg_var->seqg_vars_read_named.named);
			}
			else
			{
# line 48 "../pvGet.st"
				testPass("no immediate completion");
			}
# line 50 "../pvGet.st"
			epicsThreadSleep(0.1);
# line 51 "../pvGet.st"
			if (seq_pvGetComplete(seqg_env, 1/*named*/))
			{
# line 53 "../pvGet.st"
				testOk(seqg_var->seqg_vars_read_named.expected == seqg_var->seqg_vars_read_named.named, "completion after delay:    expected=%d==%d=named", seqg_var->seqg_vars_read_named.expected, seqg_var->seqg_vars_read_named.named);
			}
			else
			{
# line 55 "../pvGet.st"
				testPass("no completion after delay");
			}
		}
		return;
	}
}

/****** Code for state "wait" in state set "read_named" ******/

/* Event function for state "wait" in state set "read_named" */
static seqBool seqg_event_read_named_0_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 60 "../pvGet.st"
	if (seq_pvGetComplete(seqg_env, 1/*named*/))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "read_named" */
static void seqg_action_read_named_0_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 62 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_named.expected == seqg_var->seqg_vars_read_named.named, "completion after sync:     expected=%d==%d=named", seqg_var->seqg_vars_read_named.expected, seqg_var->seqg_vars_read_named.named);
# line 63 "../pvGet.st"
			seqg_var->seqg_vars_read_named.n++;
		}
		return;
	}
}

/****** Code for state "done" in state set "read_named" ******/

/* Event function for state "done" in state set "read_named" */
static seqBool seqg_event_read_named_0_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 67 "../pvGet.st"
	if (FALSE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "read_named" */
static void seqg_action_read_named_0_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "get" in state set "read_anon" ******/

/* Event function for state "get" in state set "read_anon" */
static seqBool seqg_event_read_anon_1_get(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 76 "../pvGet.st"
	if (seqg_var->seqg_vars_read_anon.n == 5)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 79 "../pvGet.st"
	if (seq_delay(seqg_env, 0.2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "get" in state set "read_anon" */
static void seqg_action_read_anon_1_get(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 77 "../pvGet.st"
			seq_efSet(seqg_env, ef_read_anon);
		}
		return;
	case 1:
		{
# line 80 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 81 "../pvGet.st"
			seqg_var->seqg_vars_read_anon.expected = shared;
# line 82 "../pvGet.st"
			seq_pvGetTmo(seqg_env, 0/*anon*/, ASYNC, DEFAULT_TIMEOUT);
# line 83 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 84 "../pvGet.st"
			if (seq_pvGetComplete(seqg_env, 0/*anon*/))
			{
# line 86 "../pvGet.st"
				testOk(seqg_var->seqg_vars_read_anon.expected == seqg_var->anon, "immediate completion:      expected=%d==%d=anon", seqg_var->seqg_vars_read_anon.expected, seqg_var->anon);
			}
			else
			{
# line 88 "../pvGet.st"
				testPass("no immediate completion");
			}
# line 90 "../pvGet.st"
			epicsThreadSleep(0.1);
# line 91 "../pvGet.st"
			if (seq_pvGetComplete(seqg_env, 0/*anon*/))
			{
# line 93 "../pvGet.st"
				testOk(seqg_var->seqg_vars_read_anon.expected == seqg_var->anon, "completion after delay:    expected=%d==%d=anon", seqg_var->seqg_vars_read_anon.expected, seqg_var->anon);
			}
			else
			{
# line 95 "../pvGet.st"
				testPass("no completion after delay");
			}
		}
		return;
	}
}

/****** Code for state "wait" in state set "read_anon" ******/

/* Event function for state "wait" in state set "read_anon" */
static seqBool seqg_event_read_anon_1_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 100 "../pvGet.st"
	if (seq_pvGetComplete(seqg_env, 0/*anon*/))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "read_anon" */
static void seqg_action_read_anon_1_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 102 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_anon.expected == seqg_var->anon, "completion after sync:     expected=%d==%d=anon", seqg_var->seqg_vars_read_anon.expected, seqg_var->anon);
# line 103 "../pvGet.st"
			seqg_var->seqg_vars_read_anon.n++;
		}
		return;
	}
}

/****** Code for state "done" in state set "read_anon" ******/

/* Event function for state "done" in state set "read_anon" */
static seqBool seqg_event_read_anon_1_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 107 "../pvGet.st"
	if (FALSE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "read_anon" */
static void seqg_action_read_anon_1_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "get" in state set "read_named_sync" ******/

/* Event function for state "get" in state set "read_named_sync" */
static seqBool seqg_event_read_named_sync_2_get(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 118 "../pvGet.st"
	if (seqg_var->seqg_vars_read_named_sync.n == 5)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 121 "../pvGet.st"
	if (seq_delay(seqg_env, 0.2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "get" in state set "read_named_sync" */
static void seqg_action_read_named_sync_2_get(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 119 "../pvGet.st"
			seq_efSet(seqg_env, ef_read_named_sync);
		}
		return;
	case 1:
		{
# line 122 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 123 "../pvGet.st"
			seqg_var->seqg_vars_read_named_sync.expected = shared;
# line 124 "../pvGet.st"
			seq_pvGetTmo(seqg_env, 2/*named*/, SYNC, DEFAULT_TIMEOUT);
# line 125 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 127 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_named_sync.expected == seqg_var->seqg_vars_read_named_sync.named, "synchronous get:           expected=%d==%d=named", seqg_var->seqg_vars_read_named_sync.expected, seqg_var->seqg_vars_read_named_sync.named);
# line 128 "../pvGet.st"
			epicsThreadSleep(0.1);
# line 129 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 130 "../pvGet.st"
			seqg_var->seqg_vars_read_named_sync.expected = shared;
# line 131 "../pvGet.st"
			seq_pvGetTmo(seqg_env, 2/*named*/, SYNC, DEFAULT_TIMEOUT);
# line 132 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 134 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_named_sync.expected == seqg_var->seqg_vars_read_named_sync.named, "repeat get after delay:    expected=%d==%d=named", seqg_var->seqg_vars_read_named_sync.expected, seqg_var->seqg_vars_read_named_sync.named);
		}
		return;
	}
}

/****** Code for state "wait" in state set "read_named_sync" ******/

/* Event function for state "wait" in state set "read_named_sync" */
static seqBool seqg_event_read_named_sync_2_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "read_named_sync" */
static void seqg_action_read_named_sync_2_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 140 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_named_sync.expected == seqg_var->seqg_vars_read_named_sync.named, "after sync:                expected=%d==%d=named", seqg_var->seqg_vars_read_named_sync.expected, seqg_var->seqg_vars_read_named_sync.named);
# line 141 "../pvGet.st"
			seqg_var->seqg_vars_read_named_sync.n++;
		}
		return;
	}
}

/****** Code for state "done" in state set "read_named_sync" ******/

/* Event function for state "done" in state set "read_named_sync" */
static seqBool seqg_event_read_named_sync_2_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 145 "../pvGet.st"
	if (FALSE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "read_named_sync" */
static void seqg_action_read_named_sync_2_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "get" in state set "read_anon_sync" ******/

/* Event function for state "get" in state set "read_anon_sync" */
static seqBool seqg_event_read_anon_sync_3_get(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 154 "../pvGet.st"
	if (seqg_var->seqg_vars_read_anon_sync.n == 5)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 157 "../pvGet.st"
	if (seq_delay(seqg_env, 0.2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "get" in state set "read_anon_sync" */
static void seqg_action_read_anon_sync_3_get(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 155 "../pvGet.st"
			seq_efSet(seqg_env, ef_read_anon_sync);
		}
		return;
	case 1:
		{
# line 158 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 159 "../pvGet.st"
			seqg_var->seqg_vars_read_anon_sync.expected = shared;
# line 160 "../pvGet.st"
			seq_pvGetTmo(seqg_env, 0/*anon*/, SYNC, DEFAULT_TIMEOUT);
# line 161 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 163 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_anon_sync.expected == seqg_var->anon, "synchronous get:           expected=%d==%d=anon", seqg_var->seqg_vars_read_anon_sync.expected, seqg_var->anon);
# line 164 "../pvGet.st"
			epicsThreadSleep(0.1);
# line 165 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 166 "../pvGet.st"
			seqg_var->seqg_vars_read_anon_sync.expected = shared;
# line 167 "../pvGet.st"
			seq_pvGetTmo(seqg_env, 0/*anon*/, SYNC, DEFAULT_TIMEOUT);
# line 168 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 170 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_anon_sync.expected == seqg_var->anon, "repeat get after delay:    expected=%d==%d=anon", seqg_var->seqg_vars_read_anon_sync.expected, seqg_var->anon);
		}
		return;
	}
}

/****** Code for state "wait" in state set "read_anon_sync" ******/

/* Event function for state "wait" in state set "read_anon_sync" */
static seqBool seqg_event_read_anon_sync_3_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "read_anon_sync" */
static void seqg_action_read_anon_sync_3_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 176 "../pvGet.st"
			testOk(seqg_var->seqg_vars_read_anon_sync.expected == seqg_var->anon, "after sync:                expected=%d==%d=anon", seqg_var->seqg_vars_read_anon_sync.expected, seqg_var->anon);
# line 177 "../pvGet.st"
			seqg_var->seqg_vars_read_anon_sync.n++;
		}
		return;
	}
}

/****** Code for state "done" in state set "read_anon_sync" ******/

/* Event function for state "done" in state set "read_anon_sync" */
static seqBool seqg_event_read_anon_sync_3_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 181 "../pvGet.st"
	if (FALSE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "read_anon_sync" */
static void seqg_action_read_anon_sync_3_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "run" in state set "write" ******/

/* Event function for state "run" in state set "write" */
static seqBool seqg_event_write_4_run(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 191 "../pvGet.st"
	if (seq_efTest(seqg_env, ef_read_named) && seq_efTest(seqg_env, ef_read_anon) && seq_efTest(seqg_env, ef_read_named_sync) && seq_efTest(seqg_env, ef_read_anon_sync))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 193 "../pvGet.st"
	if (seq_delay(seqg_env, 0.07))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "run" in state set "write" */
static void seqg_action_write_4_run(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 194 "../pvGet.st"
			epicsMutexMustLock(mutex);
# line 195 "../pvGet.st"
			shared = seqg_var->seqg_vars_write.out;
# line 196 "../pvGet.st"
			seq_pvPutTmo(seqg_env, 3/*out*/, DEFAULT, DEFAULT_TIMEOUT);
# line 197 "../pvGet.st"
			seqg_var->anon = seqg_var->seqg_vars_write.out;
# line 198 "../pvGet.st"
			seq_pvPutTmo(seqg_env, 0/*anon*/, DEFAULT, DEFAULT_TIMEOUT);
# line 199 "../pvGet.st"
			epicsMutexUnlock(mutex);
# line 200 "../pvGet.st"
			seqg_var->seqg_vars_write.out++;
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 206 "../pvGet.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, anon), "anon", P_INT, 1, 5, 0, 0, 0, 0},
	{"pvGet1", offsetof(struct seqg_vars, seqg_vars_read_named.named), "named", P_INT, 1, 6, 0, 0, 0, 0},
	{"pvGet1", offsetof(struct seqg_vars, seqg_vars_read_named_sync.named), "named", P_INT, 1, 7, 0, 0, 0, 0},
	{"pvGet1", offsetof(struct seqg_vars, seqg_vars_write.out), "out", P_INT, 1, 8, 0, 0, 0, 0},
};

/* Event masks for state set "read_named" */
static const seqMask seqg_mask_read_named_0_get[] = {
	0x00000000,
};
static const seqMask seqg_mask_read_named_0_wait[] = {
	0x00000040,
};
static const seqMask seqg_mask_read_named_0_done[] = {
	0x00000000,
};

/* State table for state set "read_named" */
static seqState seqg_states_read_named[] = {
	{
	/* state name */        "get",
	/* action function */   seqg_action_read_named_0_get,
	/* event function */    seqg_event_read_named_0_get,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_named_0_get,
	/* state options */     (0)
	},
	{
	/* state name */        "wait",
	/* action function */   seqg_action_read_named_0_wait,
	/* event function */    seqg_event_read_named_0_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_named_0_wait,
	/* state options */     (0)
	},
	{
	/* state name */        "done",
	/* action function */   seqg_action_read_named_0_done,
	/* event function */    seqg_event_read_named_0_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_named_0_done,
	/* state options */     (0)
	},
};

/* Event masks for state set "read_anon" */
static const seqMask seqg_mask_read_anon_1_get[] = {
	0x00000000,
};
static const seqMask seqg_mask_read_anon_1_wait[] = {
	0x00000020,
};
static const seqMask seqg_mask_read_anon_1_done[] = {
	0x00000000,
};

/* State table for state set "read_anon" */
static seqState seqg_states_read_anon[] = {
	{
	/* state name */        "get",
	/* action function */   seqg_action_read_anon_1_get,
	/* event function */    seqg_event_read_anon_1_get,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_anon_1_get,
	/* state options */     (0)
	},
	{
	/* state name */        "wait",
	/* action function */   seqg_action_read_anon_1_wait,
	/* event function */    seqg_event_read_anon_1_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_anon_1_wait,
	/* state options */     (0)
	},
	{
	/* state name */        "done",
	/* action function */   seqg_action_read_anon_1_done,
	/* event function */    seqg_event_read_anon_1_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_anon_1_done,
	/* state options */     (0)
	},
};

/* Event masks for state set "read_named_sync" */
static const seqMask seqg_mask_read_named_sync_2_get[] = {
	0x00000000,
};
static const seqMask seqg_mask_read_named_sync_2_wait[] = {
	0x00000000,
};
static const seqMask seqg_mask_read_named_sync_2_done[] = {
	0x00000000,
};

/* State table for state set "read_named_sync" */
static seqState seqg_states_read_named_sync[] = {
	{
	/* state name */        "get",
	/* action function */   seqg_action_read_named_sync_2_get,
	/* event function */    seqg_event_read_named_sync_2_get,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_named_sync_2_get,
	/* state options */     (0)
	},
	{
	/* state name */        "wait",
	/* action function */   seqg_action_read_named_sync_2_wait,
	/* event function */    seqg_event_read_named_sync_2_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_named_sync_2_wait,
	/* state options */     (0)
	},
	{
	/* state name */        "done",
	/* action function */   seqg_action_read_named_sync_2_done,
	/* event function */    seqg_event_read_named_sync_2_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_named_sync_2_done,
	/* state options */     (0)
	},
};

/* Event masks for state set "read_anon_sync" */
static const seqMask seqg_mask_read_anon_sync_3_get[] = {
	0x00000000,
};
static const seqMask seqg_mask_read_anon_sync_3_wait[] = {
	0x00000000,
};
static const seqMask seqg_mask_read_anon_sync_3_done[] = {
	0x00000000,
};

/* State table for state set "read_anon_sync" */
static seqState seqg_states_read_anon_sync[] = {
	{
	/* state name */        "get",
	/* action function */   seqg_action_read_anon_sync_3_get,
	/* event function */    seqg_event_read_anon_sync_3_get,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_anon_sync_3_get,
	/* state options */     (0)
	},
	{
	/* state name */        "wait",
	/* action function */   seqg_action_read_anon_sync_3_wait,
	/* event function */    seqg_event_read_anon_sync_3_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_anon_sync_3_wait,
	/* state options */     (0)
	},
	{
	/* state name */        "done",
	/* action function */   seqg_action_read_anon_sync_3_done,
	/* event function */    seqg_event_read_anon_sync_3_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_anon_sync_3_done,
	/* state options */     (0)
	},
};

/* Event masks for state set "write" */
static const seqMask seqg_mask_write_4_run[] = {
	0x0000001e,
};

/* State table for state set "write" */
static seqState seqg_states_write[] = {
	{
	/* state name */        "run",
	/* action function */   seqg_action_write_4_run,
	/* event function */    seqg_event_write_4_run,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_write_4_run,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "read_named",
	/* states */            seqg_states_read_named,
	/* number of states */  3
	},

	{
	/* state set name */    "read_anon",
	/* states */            seqg_states_read_anon,
	/* number of states */  3
	},

	{
	/* state set name */    "read_named_sync",
	/* states */            seqg_states_read_named_sync,
	/* number of states */  3
	},

	{
	/* state set name */    "read_anon_sync",
	/* states */            seqg_states_read_anon_sync,
	/* number of states */  3
	},

	{
	/* state set name */    "write",
	/* states */            seqg_states_write,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram pvGetTest = {
	/* magic number */      2002005,
	/* program name */      "pvGetTest",
	/* channels */          seqg_chans,
	/* num. channels */     4,
	/* state sets */        seqg_statesets,
	/* num. state sets */   5,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  4,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME pvGetTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void pvGetTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&pvGetTest);
}
epicsExportRegistrar(pvGetTestRegistrar);
