/* C code for program pvSyncNoDbTest, generated by snc from ../pvSyncNoDb.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 7 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
#include "../testSupport.h"
# line 29 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
static const EF_ID ef_x = 1;
# line 29 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
static const EF_ID ef_a = 2;
# line 29 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
static const EF_ID ef_i = 3;
# line 29 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
static const EF_ID ef_putx = 4;

/* Variable declarations */
struct seqg_vars {
# line 13 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	int x;
# line 17 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	int i;
# line 21 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	double a[1000];
	struct seqg_vars_pvSyncMonitor {
		struct {
# line 55 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			int y;
		} seqg_vars_idle;
	} seqg_vars_pvSyncMonitor;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 13 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	static int seqg_initvar_x = 0;
	memcpy(&seqg_var->x, &seqg_initvar_x, sizeof(seqg_initvar_x));
	}
	{
# line 55 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	static int seqg_initvar_y = 0;
	memcpy(&seqg_var->seqg_vars_pvSyncMonitor.seqg_vars_idle.y, &seqg_initvar_y, sizeof(seqg_initvar_y));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 36 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	seq_test_init(5 * 1000);
# line 37 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	seq_pvSync(seqg_env, 0/*x*/, ef_x);
# line 38 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	seq_efSet(seqg_env, ef_putx);
# line 39 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	seq_efClear(seqg_env, ef_i);
# line 40 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	seq_efClear(seqg_env, ef_a);
}

/****** Code for state "one" in state set "pvSyncPut" ******/

/* Event function for state "one" in state set "pvSyncPut" */
static seqBool seqg_event_pvSyncPut_0_one(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 45 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	if (seq_efTestAndClear(seqg_env, ef_putx))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "one" in state set "pvSyncPut" */
static void seqg_action_pvSyncPut_0_one(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 46 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seqg_var->x++;
# line 47 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testDiag("set: x=%d", seqg_var->x);
# line 48 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seq_pvPutTmo(seqg_env, 0/*x*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "idle" in state set "pvSyncMonitor" ******/

/* Event function for state "idle" in state set "pvSyncMonitor" */
static seqBool seqg_event_pvSyncMonitor_1_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 56 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	if (seq_efTestAndClear(seqg_env, ef_x))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "pvSyncMonitor" */
static void seqg_action_pvSyncMonitor_1_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 57 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seqg_var->seqg_vars_pvSyncMonitor.seqg_vars_idle.y++;
# line 58 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testDiag("test: x=%d", seqg_var->x);
# line 59 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testOk(seqg_var->x == seqg_var->seqg_vars_pvSyncMonitor.seqg_vars_idle.y, "test: x=%d==%d=y", seqg_var->x, seqg_var->seqg_vars_pvSyncMonitor.seqg_vars_idle.y);
# line 60 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seqg_var->i = seqg_var->x - 1;
# line 61 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seq_pvPutTmo(seqg_env, 1/*i*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "pvSync" in state set "pvSyncY" ******/

/* Event function for state "pvSync" in state set "pvSyncY" */
static seqBool seqg_event_pvSyncY_2_pvSync(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 68 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	if (seq_efTestAndClear(seqg_env, ef_i))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "pvSync" in state set "pvSyncY" */
static void seqg_action_pvSyncY_2_pvSync(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 69 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testPass("event on i=%d", seqg_var->i);
# line 70 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seq_pvArraySync(seqg_env, 2/*a*/, 1000, ef_a);
# line 71 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testDiag("after pvArraySync(a, NTESTS, ef_a)");
# line 72 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seqg_var->a[seqg_var->i] = seqg_var->i;
# line 73 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testOk1(seq_pvPutTmo(seqg_env, 2/*a*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT) == pvStatOK);
# line 74 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testDiag("after pvPut(a[i])");
		}
		return;
	}
}

/****** Code for state "pvUnsync" in state set "pvSyncY" ******/

/* Event function for state "pvUnsync" in state set "pvSyncY" */
static seqBool seqg_event_pvSyncY_2_pvUnsync(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 78 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	if (seq_efTestAndClear(seqg_env, ef_a) && testOk1(seqg_var->a[seqg_var->i] == seqg_var->i))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "pvUnsync" in state set "pvSyncY" */
static void seqg_action_pvSyncY_2_pvUnsync(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 79 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			testOk1(seqg_var->a[seqg_var->i] == seqg_var->i);
# line 80 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			if (seqg_var->i >= 1000 - 1)
			{
				{*seqg_pnst = 2; return;}
			}
# line 83 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seq_pvArraySync(seqg_env, 2/*a*/, 1000, NOEVFLAG);
# line 84 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
			seq_efSet(seqg_env, ef_putx);
		}
		return;
	}
}

/****** Code for state "done" in state set "pvSyncY" ******/

/* Event function for state "done" in state set "pvSyncY" */
static seqBool seqg_event_pvSyncY_2_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 88 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	if (seq_delay(seqg_env, 0.5))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "pvSyncY" */
static void seqg_action_pvSyncY_2_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 94 "d:\\epics\\ad\\seq-2.2.5\\test\\validate\\pvSync.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, x), "x", P_INT, 1, 5, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, i), "i", P_INT, 1, 6, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[0]), "a[0]", P_DOUBLE, 1, 7, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[1]), "a[1]", P_DOUBLE, 1, 8, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[2]), "a[2]", P_DOUBLE, 1, 9, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[3]), "a[3]", P_DOUBLE, 1, 10, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[4]), "a[4]", P_DOUBLE, 1, 11, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[5]), "a[5]", P_DOUBLE, 1, 12, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[6]), "a[6]", P_DOUBLE, 1, 13, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[7]), "a[7]", P_DOUBLE, 1, 14, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[8]), "a[8]", P_DOUBLE, 1, 15, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[9]), "a[9]", P_DOUBLE, 1, 16, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[10]), "a[10]", P_DOUBLE, 1, 17, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[11]), "a[11]", P_DOUBLE, 1, 18, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[12]), "a[12]", P_DOUBLE, 1, 19, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[13]), "a[13]", P_DOUBLE, 1, 20, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[14]), "a[14]", P_DOUBLE, 1, 21, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[15]), "a[15]", P_DOUBLE, 1, 22, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[16]), "a[16]", P_DOUBLE, 1, 23, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[17]), "a[17]", P_DOUBLE, 1, 24, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[18]), "a[18]", P_DOUBLE, 1, 25, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[19]), "a[19]", P_DOUBLE, 1, 26, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[20]), "a[20]", P_DOUBLE, 1, 27, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[21]), "a[21]", P_DOUBLE, 1, 28, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[22]), "a[22]", P_DOUBLE, 1, 29, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[23]), "a[23]", P_DOUBLE, 1, 30, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[24]), "a[24]", P_DOUBLE, 1, 31, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[25]), "a[25]", P_DOUBLE, 1, 32, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[26]), "a[26]", P_DOUBLE, 1, 33, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[27]), "a[27]", P_DOUBLE, 1, 34, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[28]), "a[28]", P_DOUBLE, 1, 35, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[29]), "a[29]", P_DOUBLE, 1, 36, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[30]), "a[30]", P_DOUBLE, 1, 37, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[31]), "a[31]", P_DOUBLE, 1, 38, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[32]), "a[32]", P_DOUBLE, 1, 39, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[33]), "a[33]", P_DOUBLE, 1, 40, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[34]), "a[34]", P_DOUBLE, 1, 41, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[35]), "a[35]", P_DOUBLE, 1, 42, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[36]), "a[36]", P_DOUBLE, 1, 43, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[37]), "a[37]", P_DOUBLE, 1, 44, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[38]), "a[38]", P_DOUBLE, 1, 45, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[39]), "a[39]", P_DOUBLE, 1, 46, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[40]), "a[40]", P_DOUBLE, 1, 47, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[41]), "a[41]", P_DOUBLE, 1, 48, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[42]), "a[42]", P_DOUBLE, 1, 49, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[43]), "a[43]", P_DOUBLE, 1, 50, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[44]), "a[44]", P_DOUBLE, 1, 51, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[45]), "a[45]", P_DOUBLE, 1, 52, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[46]), "a[46]", P_DOUBLE, 1, 53, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[47]), "a[47]", P_DOUBLE, 1, 54, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[48]), "a[48]", P_DOUBLE, 1, 55, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[49]), "a[49]", P_DOUBLE, 1, 56, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[50]), "a[50]", P_DOUBLE, 1, 57, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[51]), "a[51]", P_DOUBLE, 1, 58, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[52]), "a[52]", P_DOUBLE, 1, 59, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[53]), "a[53]", P_DOUBLE, 1, 60, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[54]), "a[54]", P_DOUBLE, 1, 61, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[55]), "a[55]", P_DOUBLE, 1, 62, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[56]), "a[56]", P_DOUBLE, 1, 63, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[57]), "a[57]", P_DOUBLE, 1, 64, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[58]), "a[58]", P_DOUBLE, 1, 65, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[59]), "a[59]", P_DOUBLE, 1, 66, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[60]), "a[60]", P_DOUBLE, 1, 67, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[61]), "a[61]", P_DOUBLE, 1, 68, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[62]), "a[62]", P_DOUBLE, 1, 69, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[63]), "a[63]", P_DOUBLE, 1, 70, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[64]), "a[64]", P_DOUBLE, 1, 71, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[65]), "a[65]", P_DOUBLE, 1, 72, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[66]), "a[66]", P_DOUBLE, 1, 73, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[67]), "a[67]", P_DOUBLE, 1, 74, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[68]), "a[68]", P_DOUBLE, 1, 75, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[69]), "a[69]", P_DOUBLE, 1, 76, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[70]), "a[70]", P_DOUBLE, 1, 77, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[71]), "a[71]", P_DOUBLE, 1, 78, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[72]), "a[72]", P_DOUBLE, 1, 79, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[73]), "a[73]", P_DOUBLE, 1, 80, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[74]), "a[74]", P_DOUBLE, 1, 81, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[75]), "a[75]", P_DOUBLE, 1, 82, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[76]), "a[76]", P_DOUBLE, 1, 83, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[77]), "a[77]", P_DOUBLE, 1, 84, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[78]), "a[78]", P_DOUBLE, 1, 85, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[79]), "a[79]", P_DOUBLE, 1, 86, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[80]), "a[80]", P_DOUBLE, 1, 87, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[81]), "a[81]", P_DOUBLE, 1, 88, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[82]), "a[82]", P_DOUBLE, 1, 89, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[83]), "a[83]", P_DOUBLE, 1, 90, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[84]), "a[84]", P_DOUBLE, 1, 91, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[85]), "a[85]", P_DOUBLE, 1, 92, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[86]), "a[86]", P_DOUBLE, 1, 93, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[87]), "a[87]", P_DOUBLE, 1, 94, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[88]), "a[88]", P_DOUBLE, 1, 95, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[89]), "a[89]", P_DOUBLE, 1, 96, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[90]), "a[90]", P_DOUBLE, 1, 97, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[91]), "a[91]", P_DOUBLE, 1, 98, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[92]), "a[92]", P_DOUBLE, 1, 99, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[93]), "a[93]", P_DOUBLE, 1, 100, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[94]), "a[94]", P_DOUBLE, 1, 101, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[95]), "a[95]", P_DOUBLE, 1, 102, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[96]), "a[96]", P_DOUBLE, 1, 103, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[97]), "a[97]", P_DOUBLE, 1, 104, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[98]), "a[98]", P_DOUBLE, 1, 105, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[99]), "a[99]", P_DOUBLE, 1, 106, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[100]), "a[100]", P_DOUBLE, 1, 107, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[101]), "a[101]", P_DOUBLE, 1, 108, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[102]), "a[102]", P_DOUBLE, 1, 109, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[103]), "a[103]", P_DOUBLE, 1, 110, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[104]), "a[104]", P_DOUBLE, 1, 111, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[105]), "a[105]", P_DOUBLE, 1, 112, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[106]), "a[106]", P_DOUBLE, 1, 113, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[107]), "a[107]", P_DOUBLE, 1, 114, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[108]), "a[108]", P_DOUBLE, 1, 115, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[109]), "a[109]", P_DOUBLE, 1, 116, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[110]), "a[110]", P_DOUBLE, 1, 117, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[111]), "a[111]", P_DOUBLE, 1, 118, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[112]), "a[112]", P_DOUBLE, 1, 119, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[113]), "a[113]", P_DOUBLE, 1, 120, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[114]), "a[114]", P_DOUBLE, 1, 121, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[115]), "a[115]", P_DOUBLE, 1, 122, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[116]), "a[116]", P_DOUBLE, 1, 123, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[117]), "a[117]", P_DOUBLE, 1, 124, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[118]), "a[118]", P_DOUBLE, 1, 125, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[119]), "a[119]", P_DOUBLE, 1, 126, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[120]), "a[120]", P_DOUBLE, 1, 127, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[121]), "a[121]", P_DOUBLE, 1, 128, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[122]), "a[122]", P_DOUBLE, 1, 129, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[123]), "a[123]", P_DOUBLE, 1, 130, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[124]), "a[124]", P_DOUBLE, 1, 131, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[125]), "a[125]", P_DOUBLE, 1, 132, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[126]), "a[126]", P_DOUBLE, 1, 133, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[127]), "a[127]", P_DOUBLE, 1, 134, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[128]), "a[128]", P_DOUBLE, 1, 135, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[129]), "a[129]", P_DOUBLE, 1, 136, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[130]), "a[130]", P_DOUBLE, 1, 137, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[131]), "a[131]", P_DOUBLE, 1, 138, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[132]), "a[132]", P_DOUBLE, 1, 139, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[133]), "a[133]", P_DOUBLE, 1, 140, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[134]), "a[134]", P_DOUBLE, 1, 141, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[135]), "a[135]", P_DOUBLE, 1, 142, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[136]), "a[136]", P_DOUBLE, 1, 143, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[137]), "a[137]", P_DOUBLE, 1, 144, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[138]), "a[138]", P_DOUBLE, 1, 145, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[139]), "a[139]", P_DOUBLE, 1, 146, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[140]), "a[140]", P_DOUBLE, 1, 147, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[141]), "a[141]", P_DOUBLE, 1, 148, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[142]), "a[142]", P_DOUBLE, 1, 149, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[143]), "a[143]", P_DOUBLE, 1, 150, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[144]), "a[144]", P_DOUBLE, 1, 151, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[145]), "a[145]", P_DOUBLE, 1, 152, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[146]), "a[146]", P_DOUBLE, 1, 153, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[147]), "a[147]", P_DOUBLE, 1, 154, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[148]), "a[148]", P_DOUBLE, 1, 155, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[149]), "a[149]", P_DOUBLE, 1, 156, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[150]), "a[150]", P_DOUBLE, 1, 157, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[151]), "a[151]", P_DOUBLE, 1, 158, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[152]), "a[152]", P_DOUBLE, 1, 159, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[153]), "a[153]", P_DOUBLE, 1, 160, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[154]), "a[154]", P_DOUBLE, 1, 161, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[155]), "a[155]", P_DOUBLE, 1, 162, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[156]), "a[156]", P_DOUBLE, 1, 163, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[157]), "a[157]", P_DOUBLE, 1, 164, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[158]), "a[158]", P_DOUBLE, 1, 165, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[159]), "a[159]", P_DOUBLE, 1, 166, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[160]), "a[160]", P_DOUBLE, 1, 167, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[161]), "a[161]", P_DOUBLE, 1, 168, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[162]), "a[162]", P_DOUBLE, 1, 169, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[163]), "a[163]", P_DOUBLE, 1, 170, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[164]), "a[164]", P_DOUBLE, 1, 171, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[165]), "a[165]", P_DOUBLE, 1, 172, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[166]), "a[166]", P_DOUBLE, 1, 173, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[167]), "a[167]", P_DOUBLE, 1, 174, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[168]), "a[168]", P_DOUBLE, 1, 175, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[169]), "a[169]", P_DOUBLE, 1, 176, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[170]), "a[170]", P_DOUBLE, 1, 177, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[171]), "a[171]", P_DOUBLE, 1, 178, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[172]), "a[172]", P_DOUBLE, 1, 179, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[173]), "a[173]", P_DOUBLE, 1, 180, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[174]), "a[174]", P_DOUBLE, 1, 181, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[175]), "a[175]", P_DOUBLE, 1, 182, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[176]), "a[176]", P_DOUBLE, 1, 183, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[177]), "a[177]", P_DOUBLE, 1, 184, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[178]), "a[178]", P_DOUBLE, 1, 185, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[179]), "a[179]", P_DOUBLE, 1, 186, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[180]), "a[180]", P_DOUBLE, 1, 187, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[181]), "a[181]", P_DOUBLE, 1, 188, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[182]), "a[182]", P_DOUBLE, 1, 189, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[183]), "a[183]", P_DOUBLE, 1, 190, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[184]), "a[184]", P_DOUBLE, 1, 191, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[185]), "a[185]", P_DOUBLE, 1, 192, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[186]), "a[186]", P_DOUBLE, 1, 193, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[187]), "a[187]", P_DOUBLE, 1, 194, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[188]), "a[188]", P_DOUBLE, 1, 195, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[189]), "a[189]", P_DOUBLE, 1, 196, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[190]), "a[190]", P_DOUBLE, 1, 197, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[191]), "a[191]", P_DOUBLE, 1, 198, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[192]), "a[192]", P_DOUBLE, 1, 199, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[193]), "a[193]", P_DOUBLE, 1, 200, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[194]), "a[194]", P_DOUBLE, 1, 201, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[195]), "a[195]", P_DOUBLE, 1, 202, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[196]), "a[196]", P_DOUBLE, 1, 203, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[197]), "a[197]", P_DOUBLE, 1, 204, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[198]), "a[198]", P_DOUBLE, 1, 205, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[199]), "a[199]", P_DOUBLE, 1, 206, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[200]), "a[200]", P_DOUBLE, 1, 207, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[201]), "a[201]", P_DOUBLE, 1, 208, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[202]), "a[202]", P_DOUBLE, 1, 209, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[203]), "a[203]", P_DOUBLE, 1, 210, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[204]), "a[204]", P_DOUBLE, 1, 211, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[205]), "a[205]", P_DOUBLE, 1, 212, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[206]), "a[206]", P_DOUBLE, 1, 213, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[207]), "a[207]", P_DOUBLE, 1, 214, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[208]), "a[208]", P_DOUBLE, 1, 215, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[209]), "a[209]", P_DOUBLE, 1, 216, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[210]), "a[210]", P_DOUBLE, 1, 217, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[211]), "a[211]", P_DOUBLE, 1, 218, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[212]), "a[212]", P_DOUBLE, 1, 219, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[213]), "a[213]", P_DOUBLE, 1, 220, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[214]), "a[214]", P_DOUBLE, 1, 221, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[215]), "a[215]", P_DOUBLE, 1, 222, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[216]), "a[216]", P_DOUBLE, 1, 223, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[217]), "a[217]", P_DOUBLE, 1, 224, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[218]), "a[218]", P_DOUBLE, 1, 225, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[219]), "a[219]", P_DOUBLE, 1, 226, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[220]), "a[220]", P_DOUBLE, 1, 227, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[221]), "a[221]", P_DOUBLE, 1, 228, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[222]), "a[222]", P_DOUBLE, 1, 229, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[223]), "a[223]", P_DOUBLE, 1, 230, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[224]), "a[224]", P_DOUBLE, 1, 231, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[225]), "a[225]", P_DOUBLE, 1, 232, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[226]), "a[226]", P_DOUBLE, 1, 233, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[227]), "a[227]", P_DOUBLE, 1, 234, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[228]), "a[228]", P_DOUBLE, 1, 235, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[229]), "a[229]", P_DOUBLE, 1, 236, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[230]), "a[230]", P_DOUBLE, 1, 237, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[231]), "a[231]", P_DOUBLE, 1, 238, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[232]), "a[232]", P_DOUBLE, 1, 239, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[233]), "a[233]", P_DOUBLE, 1, 240, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[234]), "a[234]", P_DOUBLE, 1, 241, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[235]), "a[235]", P_DOUBLE, 1, 242, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[236]), "a[236]", P_DOUBLE, 1, 243, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[237]), "a[237]", P_DOUBLE, 1, 244, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[238]), "a[238]", P_DOUBLE, 1, 245, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[239]), "a[239]", P_DOUBLE, 1, 246, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[240]), "a[240]", P_DOUBLE, 1, 247, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[241]), "a[241]", P_DOUBLE, 1, 248, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[242]), "a[242]", P_DOUBLE, 1, 249, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[243]), "a[243]", P_DOUBLE, 1, 250, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[244]), "a[244]", P_DOUBLE, 1, 251, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[245]), "a[245]", P_DOUBLE, 1, 252, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[246]), "a[246]", P_DOUBLE, 1, 253, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[247]), "a[247]", P_DOUBLE, 1, 254, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[248]), "a[248]", P_DOUBLE, 1, 255, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[249]), "a[249]", P_DOUBLE, 1, 256, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[250]), "a[250]", P_DOUBLE, 1, 257, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[251]), "a[251]", P_DOUBLE, 1, 258, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[252]), "a[252]", P_DOUBLE, 1, 259, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[253]), "a[253]", P_DOUBLE, 1, 260, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[254]), "a[254]", P_DOUBLE, 1, 261, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[255]), "a[255]", P_DOUBLE, 1, 262, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[256]), "a[256]", P_DOUBLE, 1, 263, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[257]), "a[257]", P_DOUBLE, 1, 264, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[258]), "a[258]", P_DOUBLE, 1, 265, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[259]), "a[259]", P_DOUBLE, 1, 266, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[260]), "a[260]", P_DOUBLE, 1, 267, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[261]), "a[261]", P_DOUBLE, 1, 268, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[262]), "a[262]", P_DOUBLE, 1, 269, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[263]), "a[263]", P_DOUBLE, 1, 270, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[264]), "a[264]", P_DOUBLE, 1, 271, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[265]), "a[265]", P_DOUBLE, 1, 272, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[266]), "a[266]", P_DOUBLE, 1, 273, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[267]), "a[267]", P_DOUBLE, 1, 274, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[268]), "a[268]", P_DOUBLE, 1, 275, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[269]), "a[269]", P_DOUBLE, 1, 276, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[270]), "a[270]", P_DOUBLE, 1, 277, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[271]), "a[271]", P_DOUBLE, 1, 278, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[272]), "a[272]", P_DOUBLE, 1, 279, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[273]), "a[273]", P_DOUBLE, 1, 280, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[274]), "a[274]", P_DOUBLE, 1, 281, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[275]), "a[275]", P_DOUBLE, 1, 282, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[276]), "a[276]", P_DOUBLE, 1, 283, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[277]), "a[277]", P_DOUBLE, 1, 284, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[278]), "a[278]", P_DOUBLE, 1, 285, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[279]), "a[279]", P_DOUBLE, 1, 286, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[280]), "a[280]", P_DOUBLE, 1, 287, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[281]), "a[281]", P_DOUBLE, 1, 288, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[282]), "a[282]", P_DOUBLE, 1, 289, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[283]), "a[283]", P_DOUBLE, 1, 290, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[284]), "a[284]", P_DOUBLE, 1, 291, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[285]), "a[285]", P_DOUBLE, 1, 292, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[286]), "a[286]", P_DOUBLE, 1, 293, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[287]), "a[287]", P_DOUBLE, 1, 294, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[288]), "a[288]", P_DOUBLE, 1, 295, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[289]), "a[289]", P_DOUBLE, 1, 296, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[290]), "a[290]", P_DOUBLE, 1, 297, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[291]), "a[291]", P_DOUBLE, 1, 298, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[292]), "a[292]", P_DOUBLE, 1, 299, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[293]), "a[293]", P_DOUBLE, 1, 300, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[294]), "a[294]", P_DOUBLE, 1, 301, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[295]), "a[295]", P_DOUBLE, 1, 302, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[296]), "a[296]", P_DOUBLE, 1, 303, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[297]), "a[297]", P_DOUBLE, 1, 304, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[298]), "a[298]", P_DOUBLE, 1, 305, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[299]), "a[299]", P_DOUBLE, 1, 306, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[300]), "a[300]", P_DOUBLE, 1, 307, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[301]), "a[301]", P_DOUBLE, 1, 308, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[302]), "a[302]", P_DOUBLE, 1, 309, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[303]), "a[303]", P_DOUBLE, 1, 310, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[304]), "a[304]", P_DOUBLE, 1, 311, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[305]), "a[305]", P_DOUBLE, 1, 312, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[306]), "a[306]", P_DOUBLE, 1, 313, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[307]), "a[307]", P_DOUBLE, 1, 314, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[308]), "a[308]", P_DOUBLE, 1, 315, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[309]), "a[309]", P_DOUBLE, 1, 316, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[310]), "a[310]", P_DOUBLE, 1, 317, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[311]), "a[311]", P_DOUBLE, 1, 318, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[312]), "a[312]", P_DOUBLE, 1, 319, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[313]), "a[313]", P_DOUBLE, 1, 320, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[314]), "a[314]", P_DOUBLE, 1, 321, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[315]), "a[315]", P_DOUBLE, 1, 322, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[316]), "a[316]", P_DOUBLE, 1, 323, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[317]), "a[317]", P_DOUBLE, 1, 324, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[318]), "a[318]", P_DOUBLE, 1, 325, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[319]), "a[319]", P_DOUBLE, 1, 326, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[320]), "a[320]", P_DOUBLE, 1, 327, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[321]), "a[321]", P_DOUBLE, 1, 328, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[322]), "a[322]", P_DOUBLE, 1, 329, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[323]), "a[323]", P_DOUBLE, 1, 330, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[324]), "a[324]", P_DOUBLE, 1, 331, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[325]), "a[325]", P_DOUBLE, 1, 332, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[326]), "a[326]", P_DOUBLE, 1, 333, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[327]), "a[327]", P_DOUBLE, 1, 334, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[328]), "a[328]", P_DOUBLE, 1, 335, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[329]), "a[329]", P_DOUBLE, 1, 336, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[330]), "a[330]", P_DOUBLE, 1, 337, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[331]), "a[331]", P_DOUBLE, 1, 338, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[332]), "a[332]", P_DOUBLE, 1, 339, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[333]), "a[333]", P_DOUBLE, 1, 340, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[334]), "a[334]", P_DOUBLE, 1, 341, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[335]), "a[335]", P_DOUBLE, 1, 342, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[336]), "a[336]", P_DOUBLE, 1, 343, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[337]), "a[337]", P_DOUBLE, 1, 344, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[338]), "a[338]", P_DOUBLE, 1, 345, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[339]), "a[339]", P_DOUBLE, 1, 346, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[340]), "a[340]", P_DOUBLE, 1, 347, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[341]), "a[341]", P_DOUBLE, 1, 348, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[342]), "a[342]", P_DOUBLE, 1, 349, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[343]), "a[343]", P_DOUBLE, 1, 350, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[344]), "a[344]", P_DOUBLE, 1, 351, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[345]), "a[345]", P_DOUBLE, 1, 352, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[346]), "a[346]", P_DOUBLE, 1, 353, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[347]), "a[347]", P_DOUBLE, 1, 354, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[348]), "a[348]", P_DOUBLE, 1, 355, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[349]), "a[349]", P_DOUBLE, 1, 356, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[350]), "a[350]", P_DOUBLE, 1, 357, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[351]), "a[351]", P_DOUBLE, 1, 358, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[352]), "a[352]", P_DOUBLE, 1, 359, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[353]), "a[353]", P_DOUBLE, 1, 360, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[354]), "a[354]", P_DOUBLE, 1, 361, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[355]), "a[355]", P_DOUBLE, 1, 362, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[356]), "a[356]", P_DOUBLE, 1, 363, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[357]), "a[357]", P_DOUBLE, 1, 364, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[358]), "a[358]", P_DOUBLE, 1, 365, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[359]), "a[359]", P_DOUBLE, 1, 366, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[360]), "a[360]", P_DOUBLE, 1, 367, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[361]), "a[361]", P_DOUBLE, 1, 368, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[362]), "a[362]", P_DOUBLE, 1, 369, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[363]), "a[363]", P_DOUBLE, 1, 370, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[364]), "a[364]", P_DOUBLE, 1, 371, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[365]), "a[365]", P_DOUBLE, 1, 372, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[366]), "a[366]", P_DOUBLE, 1, 373, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[367]), "a[367]", P_DOUBLE, 1, 374, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[368]), "a[368]", P_DOUBLE, 1, 375, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[369]), "a[369]", P_DOUBLE, 1, 376, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[370]), "a[370]", P_DOUBLE, 1, 377, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[371]), "a[371]", P_DOUBLE, 1, 378, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[372]), "a[372]", P_DOUBLE, 1, 379, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[373]), "a[373]", P_DOUBLE, 1, 380, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[374]), "a[374]", P_DOUBLE, 1, 381, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[375]), "a[375]", P_DOUBLE, 1, 382, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[376]), "a[376]", P_DOUBLE, 1, 383, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[377]), "a[377]", P_DOUBLE, 1, 384, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[378]), "a[378]", P_DOUBLE, 1, 385, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[379]), "a[379]", P_DOUBLE, 1, 386, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[380]), "a[380]", P_DOUBLE, 1, 387, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[381]), "a[381]", P_DOUBLE, 1, 388, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[382]), "a[382]", P_DOUBLE, 1, 389, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[383]), "a[383]", P_DOUBLE, 1, 390, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[384]), "a[384]", P_DOUBLE, 1, 391, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[385]), "a[385]", P_DOUBLE, 1, 392, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[386]), "a[386]", P_DOUBLE, 1, 393, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[387]), "a[387]", P_DOUBLE, 1, 394, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[388]), "a[388]", P_DOUBLE, 1, 395, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[389]), "a[389]", P_DOUBLE, 1, 396, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[390]), "a[390]", P_DOUBLE, 1, 397, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[391]), "a[391]", P_DOUBLE, 1, 398, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[392]), "a[392]", P_DOUBLE, 1, 399, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[393]), "a[393]", P_DOUBLE, 1, 400, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[394]), "a[394]", P_DOUBLE, 1, 401, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[395]), "a[395]", P_DOUBLE, 1, 402, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[396]), "a[396]", P_DOUBLE, 1, 403, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[397]), "a[397]", P_DOUBLE, 1, 404, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[398]), "a[398]", P_DOUBLE, 1, 405, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[399]), "a[399]", P_DOUBLE, 1, 406, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[400]), "a[400]", P_DOUBLE, 1, 407, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[401]), "a[401]", P_DOUBLE, 1, 408, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[402]), "a[402]", P_DOUBLE, 1, 409, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[403]), "a[403]", P_DOUBLE, 1, 410, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[404]), "a[404]", P_DOUBLE, 1, 411, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[405]), "a[405]", P_DOUBLE, 1, 412, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[406]), "a[406]", P_DOUBLE, 1, 413, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[407]), "a[407]", P_DOUBLE, 1, 414, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[408]), "a[408]", P_DOUBLE, 1, 415, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[409]), "a[409]", P_DOUBLE, 1, 416, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[410]), "a[410]", P_DOUBLE, 1, 417, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[411]), "a[411]", P_DOUBLE, 1, 418, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[412]), "a[412]", P_DOUBLE, 1, 419, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[413]), "a[413]", P_DOUBLE, 1, 420, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[414]), "a[414]", P_DOUBLE, 1, 421, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[415]), "a[415]", P_DOUBLE, 1, 422, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[416]), "a[416]", P_DOUBLE, 1, 423, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[417]), "a[417]", P_DOUBLE, 1, 424, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[418]), "a[418]", P_DOUBLE, 1, 425, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[419]), "a[419]", P_DOUBLE, 1, 426, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[420]), "a[420]", P_DOUBLE, 1, 427, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[421]), "a[421]", P_DOUBLE, 1, 428, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[422]), "a[422]", P_DOUBLE, 1, 429, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[423]), "a[423]", P_DOUBLE, 1, 430, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[424]), "a[424]", P_DOUBLE, 1, 431, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[425]), "a[425]", P_DOUBLE, 1, 432, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[426]), "a[426]", P_DOUBLE, 1, 433, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[427]), "a[427]", P_DOUBLE, 1, 434, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[428]), "a[428]", P_DOUBLE, 1, 435, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[429]), "a[429]", P_DOUBLE, 1, 436, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[430]), "a[430]", P_DOUBLE, 1, 437, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[431]), "a[431]", P_DOUBLE, 1, 438, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[432]), "a[432]", P_DOUBLE, 1, 439, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[433]), "a[433]", P_DOUBLE, 1, 440, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[434]), "a[434]", P_DOUBLE, 1, 441, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[435]), "a[435]", P_DOUBLE, 1, 442, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[436]), "a[436]", P_DOUBLE, 1, 443, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[437]), "a[437]", P_DOUBLE, 1, 444, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[438]), "a[438]", P_DOUBLE, 1, 445, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[439]), "a[439]", P_DOUBLE, 1, 446, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[440]), "a[440]", P_DOUBLE, 1, 447, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[441]), "a[441]", P_DOUBLE, 1, 448, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[442]), "a[442]", P_DOUBLE, 1, 449, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[443]), "a[443]", P_DOUBLE, 1, 450, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[444]), "a[444]", P_DOUBLE, 1, 451, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[445]), "a[445]", P_DOUBLE, 1, 452, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[446]), "a[446]", P_DOUBLE, 1, 453, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[447]), "a[447]", P_DOUBLE, 1, 454, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[448]), "a[448]", P_DOUBLE, 1, 455, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[449]), "a[449]", P_DOUBLE, 1, 456, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[450]), "a[450]", P_DOUBLE, 1, 457, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[451]), "a[451]", P_DOUBLE, 1, 458, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[452]), "a[452]", P_DOUBLE, 1, 459, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[453]), "a[453]", P_DOUBLE, 1, 460, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[454]), "a[454]", P_DOUBLE, 1, 461, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[455]), "a[455]", P_DOUBLE, 1, 462, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[456]), "a[456]", P_DOUBLE, 1, 463, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[457]), "a[457]", P_DOUBLE, 1, 464, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[458]), "a[458]", P_DOUBLE, 1, 465, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[459]), "a[459]", P_DOUBLE, 1, 466, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[460]), "a[460]", P_DOUBLE, 1, 467, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[461]), "a[461]", P_DOUBLE, 1, 468, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[462]), "a[462]", P_DOUBLE, 1, 469, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[463]), "a[463]", P_DOUBLE, 1, 470, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[464]), "a[464]", P_DOUBLE, 1, 471, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[465]), "a[465]", P_DOUBLE, 1, 472, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[466]), "a[466]", P_DOUBLE, 1, 473, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[467]), "a[467]", P_DOUBLE, 1, 474, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[468]), "a[468]", P_DOUBLE, 1, 475, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[469]), "a[469]", P_DOUBLE, 1, 476, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[470]), "a[470]", P_DOUBLE, 1, 477, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[471]), "a[471]", P_DOUBLE, 1, 478, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[472]), "a[472]", P_DOUBLE, 1, 479, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[473]), "a[473]", P_DOUBLE, 1, 480, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[474]), "a[474]", P_DOUBLE, 1, 481, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[475]), "a[475]", P_DOUBLE, 1, 482, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[476]), "a[476]", P_DOUBLE, 1, 483, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[477]), "a[477]", P_DOUBLE, 1, 484, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[478]), "a[478]", P_DOUBLE, 1, 485, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[479]), "a[479]", P_DOUBLE, 1, 486, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[480]), "a[480]", P_DOUBLE, 1, 487, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[481]), "a[481]", P_DOUBLE, 1, 488, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[482]), "a[482]", P_DOUBLE, 1, 489, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[483]), "a[483]", P_DOUBLE, 1, 490, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[484]), "a[484]", P_DOUBLE, 1, 491, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[485]), "a[485]", P_DOUBLE, 1, 492, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[486]), "a[486]", P_DOUBLE, 1, 493, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[487]), "a[487]", P_DOUBLE, 1, 494, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[488]), "a[488]", P_DOUBLE, 1, 495, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[489]), "a[489]", P_DOUBLE, 1, 496, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[490]), "a[490]", P_DOUBLE, 1, 497, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[491]), "a[491]", P_DOUBLE, 1, 498, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[492]), "a[492]", P_DOUBLE, 1, 499, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[493]), "a[493]", P_DOUBLE, 1, 500, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[494]), "a[494]", P_DOUBLE, 1, 501, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[495]), "a[495]", P_DOUBLE, 1, 502, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[496]), "a[496]", P_DOUBLE, 1, 503, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[497]), "a[497]", P_DOUBLE, 1, 504, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[498]), "a[498]", P_DOUBLE, 1, 505, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[499]), "a[499]", P_DOUBLE, 1, 506, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[500]), "a[500]", P_DOUBLE, 1, 507, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[501]), "a[501]", P_DOUBLE, 1, 508, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[502]), "a[502]", P_DOUBLE, 1, 509, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[503]), "a[503]", P_DOUBLE, 1, 510, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[504]), "a[504]", P_DOUBLE, 1, 511, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[505]), "a[505]", P_DOUBLE, 1, 512, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[506]), "a[506]", P_DOUBLE, 1, 513, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[507]), "a[507]", P_DOUBLE, 1, 514, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[508]), "a[508]", P_DOUBLE, 1, 515, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[509]), "a[509]", P_DOUBLE, 1, 516, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[510]), "a[510]", P_DOUBLE, 1, 517, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[511]), "a[511]", P_DOUBLE, 1, 518, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[512]), "a[512]", P_DOUBLE, 1, 519, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[513]), "a[513]", P_DOUBLE, 1, 520, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[514]), "a[514]", P_DOUBLE, 1, 521, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[515]), "a[515]", P_DOUBLE, 1, 522, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[516]), "a[516]", P_DOUBLE, 1, 523, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[517]), "a[517]", P_DOUBLE, 1, 524, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[518]), "a[518]", P_DOUBLE, 1, 525, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[519]), "a[519]", P_DOUBLE, 1, 526, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[520]), "a[520]", P_DOUBLE, 1, 527, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[521]), "a[521]", P_DOUBLE, 1, 528, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[522]), "a[522]", P_DOUBLE, 1, 529, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[523]), "a[523]", P_DOUBLE, 1, 530, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[524]), "a[524]", P_DOUBLE, 1, 531, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[525]), "a[525]", P_DOUBLE, 1, 532, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[526]), "a[526]", P_DOUBLE, 1, 533, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[527]), "a[527]", P_DOUBLE, 1, 534, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[528]), "a[528]", P_DOUBLE, 1, 535, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[529]), "a[529]", P_DOUBLE, 1, 536, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[530]), "a[530]", P_DOUBLE, 1, 537, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[531]), "a[531]", P_DOUBLE, 1, 538, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[532]), "a[532]", P_DOUBLE, 1, 539, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[533]), "a[533]", P_DOUBLE, 1, 540, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[534]), "a[534]", P_DOUBLE, 1, 541, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[535]), "a[535]", P_DOUBLE, 1, 542, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[536]), "a[536]", P_DOUBLE, 1, 543, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[537]), "a[537]", P_DOUBLE, 1, 544, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[538]), "a[538]", P_DOUBLE, 1, 545, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[539]), "a[539]", P_DOUBLE, 1, 546, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[540]), "a[540]", P_DOUBLE, 1, 547, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[541]), "a[541]", P_DOUBLE, 1, 548, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[542]), "a[542]", P_DOUBLE, 1, 549, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[543]), "a[543]", P_DOUBLE, 1, 550, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[544]), "a[544]", P_DOUBLE, 1, 551, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[545]), "a[545]", P_DOUBLE, 1, 552, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[546]), "a[546]", P_DOUBLE, 1, 553, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[547]), "a[547]", P_DOUBLE, 1, 554, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[548]), "a[548]", P_DOUBLE, 1, 555, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[549]), "a[549]", P_DOUBLE, 1, 556, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[550]), "a[550]", P_DOUBLE, 1, 557, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[551]), "a[551]", P_DOUBLE, 1, 558, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[552]), "a[552]", P_DOUBLE, 1, 559, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[553]), "a[553]", P_DOUBLE, 1, 560, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[554]), "a[554]", P_DOUBLE, 1, 561, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[555]), "a[555]", P_DOUBLE, 1, 562, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[556]), "a[556]", P_DOUBLE, 1, 563, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[557]), "a[557]", P_DOUBLE, 1, 564, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[558]), "a[558]", P_DOUBLE, 1, 565, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[559]), "a[559]", P_DOUBLE, 1, 566, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[560]), "a[560]", P_DOUBLE, 1, 567, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[561]), "a[561]", P_DOUBLE, 1, 568, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[562]), "a[562]", P_DOUBLE, 1, 569, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[563]), "a[563]", P_DOUBLE, 1, 570, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[564]), "a[564]", P_DOUBLE, 1, 571, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[565]), "a[565]", P_DOUBLE, 1, 572, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[566]), "a[566]", P_DOUBLE, 1, 573, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[567]), "a[567]", P_DOUBLE, 1, 574, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[568]), "a[568]", P_DOUBLE, 1, 575, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[569]), "a[569]", P_DOUBLE, 1, 576, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[570]), "a[570]", P_DOUBLE, 1, 577, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[571]), "a[571]", P_DOUBLE, 1, 578, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[572]), "a[572]", P_DOUBLE, 1, 579, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[573]), "a[573]", P_DOUBLE, 1, 580, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[574]), "a[574]", P_DOUBLE, 1, 581, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[575]), "a[575]", P_DOUBLE, 1, 582, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[576]), "a[576]", P_DOUBLE, 1, 583, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[577]), "a[577]", P_DOUBLE, 1, 584, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[578]), "a[578]", P_DOUBLE, 1, 585, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[579]), "a[579]", P_DOUBLE, 1, 586, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[580]), "a[580]", P_DOUBLE, 1, 587, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[581]), "a[581]", P_DOUBLE, 1, 588, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[582]), "a[582]", P_DOUBLE, 1, 589, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[583]), "a[583]", P_DOUBLE, 1, 590, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[584]), "a[584]", P_DOUBLE, 1, 591, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[585]), "a[585]", P_DOUBLE, 1, 592, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[586]), "a[586]", P_DOUBLE, 1, 593, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[587]), "a[587]", P_DOUBLE, 1, 594, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[588]), "a[588]", P_DOUBLE, 1, 595, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[589]), "a[589]", P_DOUBLE, 1, 596, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[590]), "a[590]", P_DOUBLE, 1, 597, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[591]), "a[591]", P_DOUBLE, 1, 598, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[592]), "a[592]", P_DOUBLE, 1, 599, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[593]), "a[593]", P_DOUBLE, 1, 600, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[594]), "a[594]", P_DOUBLE, 1, 601, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[595]), "a[595]", P_DOUBLE, 1, 602, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[596]), "a[596]", P_DOUBLE, 1, 603, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[597]), "a[597]", P_DOUBLE, 1, 604, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[598]), "a[598]", P_DOUBLE, 1, 605, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[599]), "a[599]", P_DOUBLE, 1, 606, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[600]), "a[600]", P_DOUBLE, 1, 607, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[601]), "a[601]", P_DOUBLE, 1, 608, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[602]), "a[602]", P_DOUBLE, 1, 609, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[603]), "a[603]", P_DOUBLE, 1, 610, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[604]), "a[604]", P_DOUBLE, 1, 611, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[605]), "a[605]", P_DOUBLE, 1, 612, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[606]), "a[606]", P_DOUBLE, 1, 613, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[607]), "a[607]", P_DOUBLE, 1, 614, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[608]), "a[608]", P_DOUBLE, 1, 615, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[609]), "a[609]", P_DOUBLE, 1, 616, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[610]), "a[610]", P_DOUBLE, 1, 617, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[611]), "a[611]", P_DOUBLE, 1, 618, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[612]), "a[612]", P_DOUBLE, 1, 619, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[613]), "a[613]", P_DOUBLE, 1, 620, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[614]), "a[614]", P_DOUBLE, 1, 621, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[615]), "a[615]", P_DOUBLE, 1, 622, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[616]), "a[616]", P_DOUBLE, 1, 623, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[617]), "a[617]", P_DOUBLE, 1, 624, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[618]), "a[618]", P_DOUBLE, 1, 625, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[619]), "a[619]", P_DOUBLE, 1, 626, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[620]), "a[620]", P_DOUBLE, 1, 627, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[621]), "a[621]", P_DOUBLE, 1, 628, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[622]), "a[622]", P_DOUBLE, 1, 629, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[623]), "a[623]", P_DOUBLE, 1, 630, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[624]), "a[624]", P_DOUBLE, 1, 631, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[625]), "a[625]", P_DOUBLE, 1, 632, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[626]), "a[626]", P_DOUBLE, 1, 633, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[627]), "a[627]", P_DOUBLE, 1, 634, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[628]), "a[628]", P_DOUBLE, 1, 635, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[629]), "a[629]", P_DOUBLE, 1, 636, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[630]), "a[630]", P_DOUBLE, 1, 637, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[631]), "a[631]", P_DOUBLE, 1, 638, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[632]), "a[632]", P_DOUBLE, 1, 639, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[633]), "a[633]", P_DOUBLE, 1, 640, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[634]), "a[634]", P_DOUBLE, 1, 641, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[635]), "a[635]", P_DOUBLE, 1, 642, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[636]), "a[636]", P_DOUBLE, 1, 643, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[637]), "a[637]", P_DOUBLE, 1, 644, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[638]), "a[638]", P_DOUBLE, 1, 645, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[639]), "a[639]", P_DOUBLE, 1, 646, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[640]), "a[640]", P_DOUBLE, 1, 647, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[641]), "a[641]", P_DOUBLE, 1, 648, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[642]), "a[642]", P_DOUBLE, 1, 649, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[643]), "a[643]", P_DOUBLE, 1, 650, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[644]), "a[644]", P_DOUBLE, 1, 651, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[645]), "a[645]", P_DOUBLE, 1, 652, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[646]), "a[646]", P_DOUBLE, 1, 653, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[647]), "a[647]", P_DOUBLE, 1, 654, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[648]), "a[648]", P_DOUBLE, 1, 655, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[649]), "a[649]", P_DOUBLE, 1, 656, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[650]), "a[650]", P_DOUBLE, 1, 657, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[651]), "a[651]", P_DOUBLE, 1, 658, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[652]), "a[652]", P_DOUBLE, 1, 659, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[653]), "a[653]", P_DOUBLE, 1, 660, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[654]), "a[654]", P_DOUBLE, 1, 661, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[655]), "a[655]", P_DOUBLE, 1, 662, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[656]), "a[656]", P_DOUBLE, 1, 663, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[657]), "a[657]", P_DOUBLE, 1, 664, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[658]), "a[658]", P_DOUBLE, 1, 665, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[659]), "a[659]", P_DOUBLE, 1, 666, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[660]), "a[660]", P_DOUBLE, 1, 667, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[661]), "a[661]", P_DOUBLE, 1, 668, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[662]), "a[662]", P_DOUBLE, 1, 669, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[663]), "a[663]", P_DOUBLE, 1, 670, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[664]), "a[664]", P_DOUBLE, 1, 671, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[665]), "a[665]", P_DOUBLE, 1, 672, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[666]), "a[666]", P_DOUBLE, 1, 673, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[667]), "a[667]", P_DOUBLE, 1, 674, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[668]), "a[668]", P_DOUBLE, 1, 675, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[669]), "a[669]", P_DOUBLE, 1, 676, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[670]), "a[670]", P_DOUBLE, 1, 677, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[671]), "a[671]", P_DOUBLE, 1, 678, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[672]), "a[672]", P_DOUBLE, 1, 679, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[673]), "a[673]", P_DOUBLE, 1, 680, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[674]), "a[674]", P_DOUBLE, 1, 681, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[675]), "a[675]", P_DOUBLE, 1, 682, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[676]), "a[676]", P_DOUBLE, 1, 683, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[677]), "a[677]", P_DOUBLE, 1, 684, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[678]), "a[678]", P_DOUBLE, 1, 685, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[679]), "a[679]", P_DOUBLE, 1, 686, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[680]), "a[680]", P_DOUBLE, 1, 687, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[681]), "a[681]", P_DOUBLE, 1, 688, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[682]), "a[682]", P_DOUBLE, 1, 689, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[683]), "a[683]", P_DOUBLE, 1, 690, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[684]), "a[684]", P_DOUBLE, 1, 691, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[685]), "a[685]", P_DOUBLE, 1, 692, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[686]), "a[686]", P_DOUBLE, 1, 693, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[687]), "a[687]", P_DOUBLE, 1, 694, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[688]), "a[688]", P_DOUBLE, 1, 695, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[689]), "a[689]", P_DOUBLE, 1, 696, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[690]), "a[690]", P_DOUBLE, 1, 697, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[691]), "a[691]", P_DOUBLE, 1, 698, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[692]), "a[692]", P_DOUBLE, 1, 699, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[693]), "a[693]", P_DOUBLE, 1, 700, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[694]), "a[694]", P_DOUBLE, 1, 701, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[695]), "a[695]", P_DOUBLE, 1, 702, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[696]), "a[696]", P_DOUBLE, 1, 703, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[697]), "a[697]", P_DOUBLE, 1, 704, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[698]), "a[698]", P_DOUBLE, 1, 705, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[699]), "a[699]", P_DOUBLE, 1, 706, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[700]), "a[700]", P_DOUBLE, 1, 707, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[701]), "a[701]", P_DOUBLE, 1, 708, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[702]), "a[702]", P_DOUBLE, 1, 709, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[703]), "a[703]", P_DOUBLE, 1, 710, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[704]), "a[704]", P_DOUBLE, 1, 711, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[705]), "a[705]", P_DOUBLE, 1, 712, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[706]), "a[706]", P_DOUBLE, 1, 713, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[707]), "a[707]", P_DOUBLE, 1, 714, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[708]), "a[708]", P_DOUBLE, 1, 715, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[709]), "a[709]", P_DOUBLE, 1, 716, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[710]), "a[710]", P_DOUBLE, 1, 717, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[711]), "a[711]", P_DOUBLE, 1, 718, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[712]), "a[712]", P_DOUBLE, 1, 719, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[713]), "a[713]", P_DOUBLE, 1, 720, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[714]), "a[714]", P_DOUBLE, 1, 721, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[715]), "a[715]", P_DOUBLE, 1, 722, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[716]), "a[716]", P_DOUBLE, 1, 723, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[717]), "a[717]", P_DOUBLE, 1, 724, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[718]), "a[718]", P_DOUBLE, 1, 725, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[719]), "a[719]", P_DOUBLE, 1, 726, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[720]), "a[720]", P_DOUBLE, 1, 727, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[721]), "a[721]", P_DOUBLE, 1, 728, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[722]), "a[722]", P_DOUBLE, 1, 729, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[723]), "a[723]", P_DOUBLE, 1, 730, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[724]), "a[724]", P_DOUBLE, 1, 731, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[725]), "a[725]", P_DOUBLE, 1, 732, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[726]), "a[726]", P_DOUBLE, 1, 733, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[727]), "a[727]", P_DOUBLE, 1, 734, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[728]), "a[728]", P_DOUBLE, 1, 735, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[729]), "a[729]", P_DOUBLE, 1, 736, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[730]), "a[730]", P_DOUBLE, 1, 737, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[731]), "a[731]", P_DOUBLE, 1, 738, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[732]), "a[732]", P_DOUBLE, 1, 739, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[733]), "a[733]", P_DOUBLE, 1, 740, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[734]), "a[734]", P_DOUBLE, 1, 741, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[735]), "a[735]", P_DOUBLE, 1, 742, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[736]), "a[736]", P_DOUBLE, 1, 743, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[737]), "a[737]", P_DOUBLE, 1, 744, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[738]), "a[738]", P_DOUBLE, 1, 745, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[739]), "a[739]", P_DOUBLE, 1, 746, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[740]), "a[740]", P_DOUBLE, 1, 747, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[741]), "a[741]", P_DOUBLE, 1, 748, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[742]), "a[742]", P_DOUBLE, 1, 749, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[743]), "a[743]", P_DOUBLE, 1, 750, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[744]), "a[744]", P_DOUBLE, 1, 751, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[745]), "a[745]", P_DOUBLE, 1, 752, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[746]), "a[746]", P_DOUBLE, 1, 753, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[747]), "a[747]", P_DOUBLE, 1, 754, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[748]), "a[748]", P_DOUBLE, 1, 755, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[749]), "a[749]", P_DOUBLE, 1, 756, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[750]), "a[750]", P_DOUBLE, 1, 757, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[751]), "a[751]", P_DOUBLE, 1, 758, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[752]), "a[752]", P_DOUBLE, 1, 759, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[753]), "a[753]", P_DOUBLE, 1, 760, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[754]), "a[754]", P_DOUBLE, 1, 761, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[755]), "a[755]", P_DOUBLE, 1, 762, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[756]), "a[756]", P_DOUBLE, 1, 763, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[757]), "a[757]", P_DOUBLE, 1, 764, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[758]), "a[758]", P_DOUBLE, 1, 765, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[759]), "a[759]", P_DOUBLE, 1, 766, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[760]), "a[760]", P_DOUBLE, 1, 767, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[761]), "a[761]", P_DOUBLE, 1, 768, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[762]), "a[762]", P_DOUBLE, 1, 769, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[763]), "a[763]", P_DOUBLE, 1, 770, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[764]), "a[764]", P_DOUBLE, 1, 771, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[765]), "a[765]", P_DOUBLE, 1, 772, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[766]), "a[766]", P_DOUBLE, 1, 773, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[767]), "a[767]", P_DOUBLE, 1, 774, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[768]), "a[768]", P_DOUBLE, 1, 775, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[769]), "a[769]", P_DOUBLE, 1, 776, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[770]), "a[770]", P_DOUBLE, 1, 777, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[771]), "a[771]", P_DOUBLE, 1, 778, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[772]), "a[772]", P_DOUBLE, 1, 779, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[773]), "a[773]", P_DOUBLE, 1, 780, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[774]), "a[774]", P_DOUBLE, 1, 781, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[775]), "a[775]", P_DOUBLE, 1, 782, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[776]), "a[776]", P_DOUBLE, 1, 783, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[777]), "a[777]", P_DOUBLE, 1, 784, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[778]), "a[778]", P_DOUBLE, 1, 785, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[779]), "a[779]", P_DOUBLE, 1, 786, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[780]), "a[780]", P_DOUBLE, 1, 787, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[781]), "a[781]", P_DOUBLE, 1, 788, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[782]), "a[782]", P_DOUBLE, 1, 789, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[783]), "a[783]", P_DOUBLE, 1, 790, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[784]), "a[784]", P_DOUBLE, 1, 791, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[785]), "a[785]", P_DOUBLE, 1, 792, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[786]), "a[786]", P_DOUBLE, 1, 793, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[787]), "a[787]", P_DOUBLE, 1, 794, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[788]), "a[788]", P_DOUBLE, 1, 795, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[789]), "a[789]", P_DOUBLE, 1, 796, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[790]), "a[790]", P_DOUBLE, 1, 797, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[791]), "a[791]", P_DOUBLE, 1, 798, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[792]), "a[792]", P_DOUBLE, 1, 799, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[793]), "a[793]", P_DOUBLE, 1, 800, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[794]), "a[794]", P_DOUBLE, 1, 801, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[795]), "a[795]", P_DOUBLE, 1, 802, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[796]), "a[796]", P_DOUBLE, 1, 803, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[797]), "a[797]", P_DOUBLE, 1, 804, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[798]), "a[798]", P_DOUBLE, 1, 805, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[799]), "a[799]", P_DOUBLE, 1, 806, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[800]), "a[800]", P_DOUBLE, 1, 807, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[801]), "a[801]", P_DOUBLE, 1, 808, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[802]), "a[802]", P_DOUBLE, 1, 809, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[803]), "a[803]", P_DOUBLE, 1, 810, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[804]), "a[804]", P_DOUBLE, 1, 811, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[805]), "a[805]", P_DOUBLE, 1, 812, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[806]), "a[806]", P_DOUBLE, 1, 813, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[807]), "a[807]", P_DOUBLE, 1, 814, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[808]), "a[808]", P_DOUBLE, 1, 815, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[809]), "a[809]", P_DOUBLE, 1, 816, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[810]), "a[810]", P_DOUBLE, 1, 817, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[811]), "a[811]", P_DOUBLE, 1, 818, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[812]), "a[812]", P_DOUBLE, 1, 819, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[813]), "a[813]", P_DOUBLE, 1, 820, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[814]), "a[814]", P_DOUBLE, 1, 821, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[815]), "a[815]", P_DOUBLE, 1, 822, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[816]), "a[816]", P_DOUBLE, 1, 823, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[817]), "a[817]", P_DOUBLE, 1, 824, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[818]), "a[818]", P_DOUBLE, 1, 825, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[819]), "a[819]", P_DOUBLE, 1, 826, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[820]), "a[820]", P_DOUBLE, 1, 827, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[821]), "a[821]", P_DOUBLE, 1, 828, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[822]), "a[822]", P_DOUBLE, 1, 829, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[823]), "a[823]", P_DOUBLE, 1, 830, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[824]), "a[824]", P_DOUBLE, 1, 831, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[825]), "a[825]", P_DOUBLE, 1, 832, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[826]), "a[826]", P_DOUBLE, 1, 833, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[827]), "a[827]", P_DOUBLE, 1, 834, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[828]), "a[828]", P_DOUBLE, 1, 835, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[829]), "a[829]", P_DOUBLE, 1, 836, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[830]), "a[830]", P_DOUBLE, 1, 837, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[831]), "a[831]", P_DOUBLE, 1, 838, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[832]), "a[832]", P_DOUBLE, 1, 839, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[833]), "a[833]", P_DOUBLE, 1, 840, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[834]), "a[834]", P_DOUBLE, 1, 841, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[835]), "a[835]", P_DOUBLE, 1, 842, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[836]), "a[836]", P_DOUBLE, 1, 843, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[837]), "a[837]", P_DOUBLE, 1, 844, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[838]), "a[838]", P_DOUBLE, 1, 845, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[839]), "a[839]", P_DOUBLE, 1, 846, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[840]), "a[840]", P_DOUBLE, 1, 847, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[841]), "a[841]", P_DOUBLE, 1, 848, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[842]), "a[842]", P_DOUBLE, 1, 849, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[843]), "a[843]", P_DOUBLE, 1, 850, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[844]), "a[844]", P_DOUBLE, 1, 851, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[845]), "a[845]", P_DOUBLE, 1, 852, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[846]), "a[846]", P_DOUBLE, 1, 853, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[847]), "a[847]", P_DOUBLE, 1, 854, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[848]), "a[848]", P_DOUBLE, 1, 855, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[849]), "a[849]", P_DOUBLE, 1, 856, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[850]), "a[850]", P_DOUBLE, 1, 857, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[851]), "a[851]", P_DOUBLE, 1, 858, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[852]), "a[852]", P_DOUBLE, 1, 859, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[853]), "a[853]", P_DOUBLE, 1, 860, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[854]), "a[854]", P_DOUBLE, 1, 861, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[855]), "a[855]", P_DOUBLE, 1, 862, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[856]), "a[856]", P_DOUBLE, 1, 863, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[857]), "a[857]", P_DOUBLE, 1, 864, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[858]), "a[858]", P_DOUBLE, 1, 865, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[859]), "a[859]", P_DOUBLE, 1, 866, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[860]), "a[860]", P_DOUBLE, 1, 867, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[861]), "a[861]", P_DOUBLE, 1, 868, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[862]), "a[862]", P_DOUBLE, 1, 869, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[863]), "a[863]", P_DOUBLE, 1, 870, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[864]), "a[864]", P_DOUBLE, 1, 871, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[865]), "a[865]", P_DOUBLE, 1, 872, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[866]), "a[866]", P_DOUBLE, 1, 873, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[867]), "a[867]", P_DOUBLE, 1, 874, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[868]), "a[868]", P_DOUBLE, 1, 875, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[869]), "a[869]", P_DOUBLE, 1, 876, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[870]), "a[870]", P_DOUBLE, 1, 877, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[871]), "a[871]", P_DOUBLE, 1, 878, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[872]), "a[872]", P_DOUBLE, 1, 879, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[873]), "a[873]", P_DOUBLE, 1, 880, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[874]), "a[874]", P_DOUBLE, 1, 881, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[875]), "a[875]", P_DOUBLE, 1, 882, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[876]), "a[876]", P_DOUBLE, 1, 883, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[877]), "a[877]", P_DOUBLE, 1, 884, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[878]), "a[878]", P_DOUBLE, 1, 885, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[879]), "a[879]", P_DOUBLE, 1, 886, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[880]), "a[880]", P_DOUBLE, 1, 887, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[881]), "a[881]", P_DOUBLE, 1, 888, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[882]), "a[882]", P_DOUBLE, 1, 889, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[883]), "a[883]", P_DOUBLE, 1, 890, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[884]), "a[884]", P_DOUBLE, 1, 891, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[885]), "a[885]", P_DOUBLE, 1, 892, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[886]), "a[886]", P_DOUBLE, 1, 893, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[887]), "a[887]", P_DOUBLE, 1, 894, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[888]), "a[888]", P_DOUBLE, 1, 895, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[889]), "a[889]", P_DOUBLE, 1, 896, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[890]), "a[890]", P_DOUBLE, 1, 897, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[891]), "a[891]", P_DOUBLE, 1, 898, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[892]), "a[892]", P_DOUBLE, 1, 899, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[893]), "a[893]", P_DOUBLE, 1, 900, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[894]), "a[894]", P_DOUBLE, 1, 901, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[895]), "a[895]", P_DOUBLE, 1, 902, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[896]), "a[896]", P_DOUBLE, 1, 903, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[897]), "a[897]", P_DOUBLE, 1, 904, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[898]), "a[898]", P_DOUBLE, 1, 905, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[899]), "a[899]", P_DOUBLE, 1, 906, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[900]), "a[900]", P_DOUBLE, 1, 907, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[901]), "a[901]", P_DOUBLE, 1, 908, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[902]), "a[902]", P_DOUBLE, 1, 909, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[903]), "a[903]", P_DOUBLE, 1, 910, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[904]), "a[904]", P_DOUBLE, 1, 911, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[905]), "a[905]", P_DOUBLE, 1, 912, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[906]), "a[906]", P_DOUBLE, 1, 913, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[907]), "a[907]", P_DOUBLE, 1, 914, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[908]), "a[908]", P_DOUBLE, 1, 915, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[909]), "a[909]", P_DOUBLE, 1, 916, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[910]), "a[910]", P_DOUBLE, 1, 917, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[911]), "a[911]", P_DOUBLE, 1, 918, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[912]), "a[912]", P_DOUBLE, 1, 919, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[913]), "a[913]", P_DOUBLE, 1, 920, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[914]), "a[914]", P_DOUBLE, 1, 921, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[915]), "a[915]", P_DOUBLE, 1, 922, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[916]), "a[916]", P_DOUBLE, 1, 923, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[917]), "a[917]", P_DOUBLE, 1, 924, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[918]), "a[918]", P_DOUBLE, 1, 925, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[919]), "a[919]", P_DOUBLE, 1, 926, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[920]), "a[920]", P_DOUBLE, 1, 927, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[921]), "a[921]", P_DOUBLE, 1, 928, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[922]), "a[922]", P_DOUBLE, 1, 929, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[923]), "a[923]", P_DOUBLE, 1, 930, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[924]), "a[924]", P_DOUBLE, 1, 931, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[925]), "a[925]", P_DOUBLE, 1, 932, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[926]), "a[926]", P_DOUBLE, 1, 933, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[927]), "a[927]", P_DOUBLE, 1, 934, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[928]), "a[928]", P_DOUBLE, 1, 935, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[929]), "a[929]", P_DOUBLE, 1, 936, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[930]), "a[930]", P_DOUBLE, 1, 937, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[931]), "a[931]", P_DOUBLE, 1, 938, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[932]), "a[932]", P_DOUBLE, 1, 939, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[933]), "a[933]", P_DOUBLE, 1, 940, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[934]), "a[934]", P_DOUBLE, 1, 941, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[935]), "a[935]", P_DOUBLE, 1, 942, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[936]), "a[936]", P_DOUBLE, 1, 943, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[937]), "a[937]", P_DOUBLE, 1, 944, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[938]), "a[938]", P_DOUBLE, 1, 945, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[939]), "a[939]", P_DOUBLE, 1, 946, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[940]), "a[940]", P_DOUBLE, 1, 947, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[941]), "a[941]", P_DOUBLE, 1, 948, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[942]), "a[942]", P_DOUBLE, 1, 949, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[943]), "a[943]", P_DOUBLE, 1, 950, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[944]), "a[944]", P_DOUBLE, 1, 951, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[945]), "a[945]", P_DOUBLE, 1, 952, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[946]), "a[946]", P_DOUBLE, 1, 953, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[947]), "a[947]", P_DOUBLE, 1, 954, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[948]), "a[948]", P_DOUBLE, 1, 955, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[949]), "a[949]", P_DOUBLE, 1, 956, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[950]), "a[950]", P_DOUBLE, 1, 957, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[951]), "a[951]", P_DOUBLE, 1, 958, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[952]), "a[952]", P_DOUBLE, 1, 959, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[953]), "a[953]", P_DOUBLE, 1, 960, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[954]), "a[954]", P_DOUBLE, 1, 961, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[955]), "a[955]", P_DOUBLE, 1, 962, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[956]), "a[956]", P_DOUBLE, 1, 963, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[957]), "a[957]", P_DOUBLE, 1, 964, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[958]), "a[958]", P_DOUBLE, 1, 965, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[959]), "a[959]", P_DOUBLE, 1, 966, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[960]), "a[960]", P_DOUBLE, 1, 967, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[961]), "a[961]", P_DOUBLE, 1, 968, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[962]), "a[962]", P_DOUBLE, 1, 969, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[963]), "a[963]", P_DOUBLE, 1, 970, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[964]), "a[964]", P_DOUBLE, 1, 971, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[965]), "a[965]", P_DOUBLE, 1, 972, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[966]), "a[966]", P_DOUBLE, 1, 973, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[967]), "a[967]", P_DOUBLE, 1, 974, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[968]), "a[968]", P_DOUBLE, 1, 975, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[969]), "a[969]", P_DOUBLE, 1, 976, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[970]), "a[970]", P_DOUBLE, 1, 977, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[971]), "a[971]", P_DOUBLE, 1, 978, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[972]), "a[972]", P_DOUBLE, 1, 979, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[973]), "a[973]", P_DOUBLE, 1, 980, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[974]), "a[974]", P_DOUBLE, 1, 981, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[975]), "a[975]", P_DOUBLE, 1, 982, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[976]), "a[976]", P_DOUBLE, 1, 983, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[977]), "a[977]", P_DOUBLE, 1, 984, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[978]), "a[978]", P_DOUBLE, 1, 985, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[979]), "a[979]", P_DOUBLE, 1, 986, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[980]), "a[980]", P_DOUBLE, 1, 987, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[981]), "a[981]", P_DOUBLE, 1, 988, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[982]), "a[982]", P_DOUBLE, 1, 989, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[983]), "a[983]", P_DOUBLE, 1, 990, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[984]), "a[984]", P_DOUBLE, 1, 991, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[985]), "a[985]", P_DOUBLE, 1, 992, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[986]), "a[986]", P_DOUBLE, 1, 993, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[987]), "a[987]", P_DOUBLE, 1, 994, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[988]), "a[988]", P_DOUBLE, 1, 995, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[989]), "a[989]", P_DOUBLE, 1, 996, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[990]), "a[990]", P_DOUBLE, 1, 997, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[991]), "a[991]", P_DOUBLE, 1, 998, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[992]), "a[992]", P_DOUBLE, 1, 999, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[993]), "a[993]", P_DOUBLE, 1, 1000, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[994]), "a[994]", P_DOUBLE, 1, 1001, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[995]), "a[995]", P_DOUBLE, 1, 1002, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[996]), "a[996]", P_DOUBLE, 1, 1003, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[997]), "a[997]", P_DOUBLE, 1, 1004, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[998]), "a[998]", P_DOUBLE, 1, 1005, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, a[999]), "a[999]", P_DOUBLE, 1, 1006, 2, 1, 0, 0},
};

/* Event masks for state set "pvSyncPut" */
static const seqMask seqg_mask_pvSyncPut_0_one[] = {
	0x00000010,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "pvSyncPut" */
static seqState seqg_states_pvSyncPut[] = {
	{
	/* state name */        "one",
	/* action function */   seqg_action_pvSyncPut_0_one,
	/* event function */    seqg_event_pvSyncPut_0_one,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvSyncPut_0_one,
	/* state options */     (0)
	},
};

/* Event masks for state set "pvSyncMonitor" */
static const seqMask seqg_mask_pvSyncMonitor_1_idle[] = {
	0x00000002,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "pvSyncMonitor" */
static seqState seqg_states_pvSyncMonitor[] = {
	{
	/* state name */        "idle",
	/* action function */   seqg_action_pvSyncMonitor_1_idle,
	/* event function */    seqg_event_pvSyncMonitor_1_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvSyncMonitor_1_idle,
	/* state options */     (0)
	},
};

/* Event masks for state set "pvSyncY" */
static const seqMask seqg_mask_pvSyncY_2_pvSync[] = {
	0x00000008,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_pvSyncY_2_pvUnsync[] = {
	0xffffffc4,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0xffffffff,
	0x00007fff,
};
static const seqMask seqg_mask_pvSyncY_2_done[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "pvSyncY" */
static seqState seqg_states_pvSyncY[] = {
	{
	/* state name */        "pvSync",
	/* action function */   seqg_action_pvSyncY_2_pvSync,
	/* event function */    seqg_event_pvSyncY_2_pvSync,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvSyncY_2_pvSync,
	/* state options */     (0)
	},
	{
	/* state name */        "pvUnsync",
	/* action function */   seqg_action_pvSyncY_2_pvUnsync,
	/* event function */    seqg_event_pvSyncY_2_pvUnsync,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvSyncY_2_pvUnsync,
	/* state options */     (0)
	},
	{
	/* state name */        "done",
	/* action function */   seqg_action_pvSyncY_2_done,
	/* event function */    seqg_event_pvSyncY_2_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_pvSyncY_2_done,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "pvSyncPut",
	/* states */            seqg_states_pvSyncPut,
	/* number of states */  1
	},

	{
	/* state set name */    "pvSyncMonitor",
	/* states */            seqg_states_pvSyncMonitor,
	/* number of states */  1
	},

	{
	/* state set name */    "pvSyncY",
	/* states */            seqg_states_pvSyncY,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram pvSyncNoDbTest = {
	/* magic number */      2002005,
	/* program name */      "pvSyncNoDbTest",
	/* channels */          seqg_chans,
	/* num. channels */     1002,
	/* state sets */        seqg_statesets,
	/* num. state sets */   3,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  4,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME pvSyncNoDbTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void pvSyncNoDbTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&pvSyncNoDbTest);
}
epicsExportRegistrar(pvSyncNoDbTestRegistrar);
