/* C code for program safeModeNotAssignedTest, generated by snc from ../safeModeNotAssigned.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../safeModeNotAssigned.st"
#include "../testSupport.h"

/* Variable declarations */
struct seqg_vars {
# line 13 "../safeModeNotAssigned.st"
	int v;
	struct seqg_vars_ss1 {
# line 22 "../safeModeNotAssigned.st"
		int i;
	} seqg_vars_ss1;
	struct seqg_vars_ss2 {
		struct {
# line 40 "../safeModeNotAssigned.st"
			int i;
		} seqg_vars_idle;
	} seqg_vars_ss2;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 13 "../safeModeNotAssigned.st"
	static int seqg_initvar_v = 0;
	memcpy(&seqg_var->v, &seqg_initvar_v, sizeof(seqg_initvar_v));
	}
	{
# line 22 "../safeModeNotAssigned.st"
	static int seqg_initvar_i = 0;
	memcpy(&seqg_var->seqg_vars_ss1.i, &seqg_initvar_i, sizeof(seqg_initvar_i));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 18 "../safeModeNotAssigned.st"
	seq_test_init(10 * 2);
}

/****** Code for state "idle" in state set "ss1" ******/

/* Event function for state "idle" in state set "ss1" */
static seqBool seqg_event_ss1_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 24 "../safeModeNotAssigned.st"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 29 "../safeModeNotAssigned.st"
	if (seqg_var->v == 10)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "ss1" */
static void seqg_action_ss1_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 25 "../safeModeNotAssigned.st"
			testOk(seqg_var->v == seqg_var->seqg_vars_ss1.i, "ss1: v=%d==%d=i", seqg_var->v, seqg_var->seqg_vars_ss1.i);
# line 26 "../safeModeNotAssigned.st"
			seqg_var->v++;
# line 27 "../safeModeNotAssigned.st"
			seqg_var->seqg_vars_ss1.i++;
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "done" in state set "ss1" ******/

/* Event function for state "done" in state set "ss1" */
static seqBool seqg_event_ss1_0_done(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 33 "../safeModeNotAssigned.st"
	if (seq_delay(seqg_env, 0.2))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "done" in state set "ss1" */
static void seqg_action_ss1_0_done(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "idle" in state set "ss2" ******/

/* Event function for state "idle" in state set "ss2" */
static seqBool seqg_event_ss2_1_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 41 "../safeModeNotAssigned.st"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "ss2" */
static void seqg_action_ss2_1_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 42 "../safeModeNotAssigned.st"
			if (seqg_var->seqg_vars_ss2.seqg_vars_idle.i < 10)
			{
# line 43 "../safeModeNotAssigned.st"
				testOk(seqg_var->v == 0, "ss2: v=%d==0", seqg_var->v);
			}
# line 45 "../safeModeNotAssigned.st"
			seqg_var->seqg_vars_ss2.seqg_vars_idle.i++;
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 51 "../safeModeNotAssigned.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "ss1" */
static const seqMask seqg_mask_ss1_0_idle[] = {
	0x00000000,
};
static const seqMask seqg_mask_ss1_0_done[] = {
	0x00000000,
};

/* State table for state set "ss1" */
static seqState seqg_states_ss1[] = {
	{
	/* state name */        "idle",
	/* action function */   seqg_action_ss1_0_idle,
	/* event function */    seqg_event_ss1_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_idle,
	/* state options */     (0)
	},
	{
	/* state name */        "done",
	/* action function */   seqg_action_ss1_0_done,
	/* event function */    seqg_event_ss1_0_done,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss1_0_done,
	/* state options */     (0)
	},
};

/* Event masks for state set "ss2" */
static const seqMask seqg_mask_ss2_1_idle[] = {
	0x00000000,
};

/* State table for state set "ss2" */
static seqState seqg_states_ss2[] = {
	{
	/* state name */        "idle",
	/* action function */   seqg_action_ss2_1_idle,
	/* event function */    seqg_event_ss2_1_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ss2_1_idle,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ss1",
	/* states */            seqg_states_ss1,
	/* number of states */  2
	},

	{
	/* state set name */    "ss2",
	/* states */            seqg_states_ss2,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram safeModeNotAssignedTest = {
	/* magic number */      2002005,
	/* program name */      "safeModeNotAssignedTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME safeModeNotAssignedTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void safeModeNotAssignedTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&safeModeNotAssignedTest);
}
epicsExportRegistrar(safeModeNotAssignedTestRegistrar);
