/* C code for program sizeofTest, generated by snc from ../sizeof.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../sizeof.st"
#include "../testSupport.h"

/* Variable declarations */


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 12 "../sizeof.st"
	seq_test_init(9);
}

/****** Code for state "sizes" in state set "test" ******/

/* Event function for state "sizes" in state set "test" */
static seqBool seqg_event_test_0_sizes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "sizes" in state set "test" */
static void seqg_action_test_0_sizes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 18 "../sizeof.st"
			char c;
# line 19 "../sizeof.st"
			char *p = &c;
# line 20 "../sizeof.st"
			testOk1(sizeof(char) == 1);
# line 21 "../sizeof.st"
			testOk1(sizeof((*p)) == 1);
# line 22 "../sizeof.st"
			testOk1(sizeof(string) >= 40);
# line 23 "../sizeof.st"
			testOk1(sizeof(epicsInt8) == 1);
# line 24 "../sizeof.st"
			testOk1(sizeof(epicsUInt8) == 1);
# line 25 "../sizeof.st"
			testOk1(sizeof(epicsInt16) == 2);
# line 26 "../sizeof.st"
			testOk1(sizeof(epicsUInt16) == 2);
# line 27 "../sizeof.st"
			testOk1(sizeof(epicsInt32) == 4);
# line 28 "../sizeof.st"
			testOk1(sizeof(epicsUInt32) == 4);
# line 29 "../sizeof.st"
			c = *p;
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 35 "../sizeof.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "test" */
static const seqMask seqg_mask_test_0_sizes[] = {
	0x00000000,
};

/* State table for state set "test" */
static seqState seqg_states_test[] = {
	{
	/* state name */        "sizes",
	/* action function */   seqg_action_test_0_sizes,
	/* event function */    seqg_event_test_0_sizes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_sizes,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "test",
	/* states */            seqg_states_test,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram sizeofTest = {
	/* magic number */      2002005,
	/* program name */      "sizeofTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME sizeofTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sizeofTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sizeofTest);
}
epicsExportRegistrar(sizeofTestRegistrar);
