/* C code for program userfuncTest, generated by snc from ../userfunc.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../userfunc.st"
#include "../testSupport.h"
# line 13 "../userfunc.st"

static void incr(SS_ID ssId, int *pv, VAR_ID v);
static void incr_compat(SS_ID ssId, int *pv, VAR_ID v);
static void set_i(USER_VAR *const pVar, int value);
static void null(void);


/* Variable declarations */
struct seqg_vars {
# line 20 "../userfunc.st"
	int i;
	struct seqg_vars_myss {
		struct {
# line 29 "../userfunc.st"
			int i_saved;
		} seqg_vars_doit;
	} seqg_vars_myss;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 20 "../userfunc.st"
	static int seqg_initvar_i = 0;
	memcpy(&seqg_var->i, &seqg_initvar_i, sizeof(seqg_initvar_i));
	}
	{
# line 29 "../userfunc.st"
	static int seqg_initvar_i_saved = 0;
	memcpy(&seqg_var->seqg_vars_myss.seqg_vars_doit.i_saved, &seqg_initvar_i_saved, sizeof(seqg_initvar_i_saved));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 24 "../userfunc.st"
	seq_test_init(20);
}

/****** Code for state "doit" in state set "myss" ******/

/* Event function for state "doit" in state set "myss" */
static seqBool seqg_event_myss_0_doit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 30 "../userfunc.st"
	if (seq_delay(seqg_env, 0.1))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 41 "../userfunc.st"
	if (seqg_var->seqg_vars_myss.seqg_vars_doit.i_saved == 10)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "doit" in state set "myss" */
static void seqg_action_myss_0_doit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 31 "../userfunc.st"
			if (seqg_var->i % 2)
# line 32 "../userfunc.st"
				incr(ssId, &seqg_var->i, seq_pvIndex(seqg_env, 0/*i*/));
			else
# line 34 "../userfunc.st"
				incr_compat(ssId, &seqg_var->i, seq_pvIndex(seqg_env, 0/*i*/));
# line 35 "../userfunc.st"
			testOk1(seqg_var->seqg_vars_myss.seqg_vars_doit.i_saved == seqg_var->i - 1);
# line 36 "../userfunc.st"
			seqg_var->seqg_vars_myss.seqg_vars_doit.i_saved = seqg_var->i;
# line 37 "../userfunc.st"
			set_i(pVar, 1);
# line 38 "../userfunc.st"
			testOk1(seqg_var->i == 1);
# line 39 "../userfunc.st"
			null();
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 47 "../userfunc.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, i), "i", P_INT, 1, 1, 0, 0, 0, 0},
};

/* Event masks for state set "myss" */
static const seqMask seqg_mask_myss_0_doit[] = {
	0x00000000,
};

/* State table for state set "myss" */
static seqState seqg_states_myss[] = {
	{
	/* state name */        "doit",
	/* action function */   seqg_action_myss_0_doit,
	/* event function */    seqg_event_myss_0_doit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_myss_0_doit,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "myss",
	/* states */            seqg_states_myss,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram userfuncTest = {
	/* magic number */      2002005,
	/* program name */      "userfuncTest",
	/* channels */          seqg_chans,
	/* num. channels */     1,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};
# line 50 "../userfunc.st"

static void incr_compat(SS_ID ssId, int *pv, VAR_ID v)
{
    seq_pvGet(ssId, v, SYNC);
    *pv += 1;
    seq_pvPut(ssId, v, SYNC);
}

static void incr(SS_ID ssId, int *pv, VAR_ID v)
{
    seq_pvGetTmo(ssId, v, SYNC, 1.0);
    *pv += 1;
    seq_pvPutTmo(ssId, v, SYNC, 1.0);
}

static void set_i(USER_VAR *const pVar, int value)
{
    pVar->i = value;
}

static void null(void)
{
}


#define PROG_NAME userfuncTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void userfuncTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&userfuncTest);
}
epicsExportRegistrar(userfuncTestRegistrar);
