/* C code for program userfuncEfTest, generated by snc from ../userfuncEf.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../userfuncEf.st"
#include "../testSupport.h"
# line 13 "../userfuncEf.st"
static const EF_ID x = 1;
# line 15 "../userfuncEf.st"

static void efSet_x(SS_ID ssId, EV_ID x)
{
    seq_efSet(ssId, x);
}


/* Variable declarations */
struct seqg_vars {
	char seqg_dummy;
	char dummy;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 23 "../userfuncEf.st"
	seq_test_init(2);
}

/****** Code for state "check_not_set" in state set "myss" ******/

/* Event function for state "check_not_set" in state set "myss" */
static seqBool seqg_event_myss_0_check_not_set(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 28 "../userfuncEf.st"
	if (seq_efTestAndClear(seqg_env, x))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 31 "../userfuncEf.st"
	if (seq_delay(seqg_env, 0.5))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "check_not_set" in state set "myss" */
static void seqg_action_myss_0_check_not_set(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 29 "../userfuncEf.st"
			testFail("argh, no timeout!");
		}
		return;
	case 1:
		{
# line 32 "../userfuncEf.st"
			testPass("cool, we came here");
		}
		return;
	}
}

/****** Code for state "set" in state set "myss" ******/

/* Event function for state "set" in state set "myss" */
static seqBool seqg_event_myss_0_set(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "set" in state set "myss" */
static void seqg_action_myss_0_set(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 37 "../userfuncEf.st"
			efSet_x(ssId, x);
		}
		return;
	}
}

/****** Code for state "check_set" in state set "myss" ******/

/* Event function for state "check_set" in state set "myss" */
static seqBool seqg_event_myss_0_check_set(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 41 "../userfuncEf.st"
	if (seq_efTestAndClear(seqg_env, x))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 44 "../userfuncEf.st"
	if (seq_delay(seqg_env, 0.5))
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "check_set" in state set "myss" */
static void seqg_action_myss_0_check_set(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 42 "../userfuncEf.st"
			testPass("cool, we came here");
		}
		return;
	case 1:
		{
# line 45 "../userfuncEf.st"
			testFail("argh, timeout!");
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 51 "../userfuncEf.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "myss" */
static const seqMask seqg_mask_myss_0_check_not_set[] = {
	0x00000002,
};
static const seqMask seqg_mask_myss_0_set[] = {
	0x00000000,
};
static const seqMask seqg_mask_myss_0_check_set[] = {
	0x00000002,
};

/* State table for state set "myss" */
static seqState seqg_states_myss[] = {
	{
	/* state name */        "check_not_set",
	/* action function */   seqg_action_myss_0_check_not_set,
	/* event function */    seqg_event_myss_0_check_not_set,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_myss_0_check_not_set,
	/* state options */     (0)
	},
	{
	/* state name */        "set",
	/* action function */   seqg_action_myss_0_set,
	/* event function */    seqg_event_myss_0_set,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_myss_0_set,
	/* state options */     (0)
	},
	{
	/* state name */        "check_set",
	/* action function */   seqg_action_myss_0_check_set,
	/* event function */    seqg_event_myss_0_check_set,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_myss_0_check_set,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "myss",
	/* states */            seqg_states_myss,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram userfuncEfTest = {
	/* magic number */      2002005,
	/* program name */      "userfuncEfTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  1,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT | OPT_SAFE),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME userfuncEfTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void userfuncEfTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&userfuncEfTest);
}
epicsExportRegistrar(userfuncEfTestRegistrar);
