/* C code for program voidTest, generated by snc from ../void.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 9 "../void.st"
#include "../testSupport.h"

/* Variable declarations */
# line 11 "../void.st"
static	int x;
# line 12 "../void.st"
static	void *p;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 11 "../void.st"
	static int seqg_initvar_x = 42;
	memcpy(&x, &seqg_initvar_x, sizeof(seqg_initvar_x));
	}
	{
# line 12 "../void.st"
	static void *seqg_initvar_p = &x;
	memcpy(&p, &seqg_initvar_p, sizeof(seqg_initvar_p));
	}
}

/* Program entry func */
static void seqg_entry(SS_ID seqg_env)
{
# line 15 "../void.st"
	seq_test_init(1);
}

/****** Code for state "sizes" in state set "test" ******/

/* Event function for state "sizes" in state set "test" */
static seqBool seqg_event_test_0_sizes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "sizes" in state set "test" */
static void seqg_action_test_0_sizes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 21 "../void.st"
			testOk1(*(int *)p == x);
		}
		return;
	}
}

/* Program exit func */
static void seqg_exit(SS_ID seqg_env)
{
# line 27 "../void.st"
	seq_test_done();
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "test" */
static const seqMask seqg_mask_test_0_sizes[] = {
	0x00000000,
};

/* State table for state set "test" */
static seqState seqg_states_test[] = {
	{
	/* state name */        "sizes",
	/* action function */   seqg_action_test_0_sizes,
	/* event function */    seqg_event_test_0_sizes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_test_0_sizes,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "test",
	/* states */            seqg_states_test,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram voidTest = {
	/* magic number */      2002005,
	/* program name */      "voidTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        seqg_entry,
	/* exit func */         seqg_exit,
	/* num. queues */       0
};

#define PROG_NAME voidTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void voidTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&voidTest);
}
epicsExportRegistrar(voidTestRegistrar);
